import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'

const translateSchema = z.object({ word: z.string().min(1).trim() })

// ─── Mini dictionary: common German → Vietnamese ───
// This serves as a fast lookup for frequent words across A1-C2 levels.
// Covers ~400 most common words that learners encounter in reading exercises.
const MINI_DICT: Record<string, string> = {
  // ── Articles & Pronouns ──
  der: 'cái, người (mạo từ giống đực)',
  die: 'cái, người (mạo từ giống cái/số nhiều)',
  das: 'cái (mạo từ giống trung)',
  ein: 'một (mạo từ)',
  eine: 'một (mạo từ giống cái)',
  ich: 'tôi',
  du: 'bạn',
  er: 'anh ấy',
  sie: 'cô ấy / họ',
  es: 'nó',
  wir: 'chúng tôi',
  ihr: 'các bạn',
  Sie: 'Bạn (trang trọng)',
  mein: 'của tôi',
  dein: 'của bạn',
  sein: 'của anh ấy / là, ở',
  ihre: 'của cô ấy / của họ',
  unser: 'của chúng tôi',
  haben: 'có',
  werden: 'trở thành, sẽ',
  können: 'có thể',
  müssen: 'phải',
  sollen: 'nên',
  wollen: 'muốn',
  dürfen: 'được phép',
  mögen: 'thích',
  machen: 'làm',
  gehen: 'đi',
  kommen: 'đến',
  geben: 'cho',
  nehmen: 'lấy',
  sehen: 'nhìn, thấy',
  finden: 'tìm thấy',
  sagen: 'nói',
  wissen: 'biết',
  denken: 'nghĩ',
  glauben: 'tin',
  stehen: 'đứng',
  lesen: 'đọc',
  schreiben: 'viết',
  lernen: 'học',
  arbeiten: 'làm việc',
  spielen: 'chơi',
  sprechen: 'nói',
  verstehen: 'hiểu',
  kaufen: 'mua',
  brauchen: 'cần',
  essen: 'ăn',
  trinken: 'uống',
  kochen: 'nấu',
  wohnen: 'sống, ở',
  heißen: 'tên là',
  helfen: 'giúp',
  bringen: 'mang đến',
  laufen: 'chạy',
  fahren: 'lái, đi (xe)',
  fliegen: 'bay',
  schlafen: 'ngủ',
  beginnen: 'bắt đầu',
  anfangen: 'bắt đầu',
  aufhören: 'dừng lại',
  öffnen: 'mở',
  schließen: 'đóng',
  vergessen: 'quên',
  erinnern: 'nhớ',
  besuchen: 'thăm',
  zeigen: 'chỉ, cho thấy',
  erklären: 'giải thích',
  beschreiben: 'mô tả',
  versuchen: 'thử',
  empfehlen: 'gợi ý',
  entwickeln: 'phát triển',
  verbessern: 'cải thiện',
  verändern: 'thay đổi',
  unterstützen: 'hỗ trợ',
  // ── Nouns ──
  Haus: 'nhà',
  Schule: 'trường học',
  Stadt: 'thành phố',
  Land: 'đất nước',
  Wasser: 'nước',
  Mensch: 'con người',
  Kind: 'trẻ em',
  Frau: 'phụ nữ',
  Mann: 'đàn ông',
  Freund: 'bạn',
  Familie: 'gia đình',
  Arbeit: 'công việc',
  Zeit: 'thời gian',
  Jahr: 'năm',
  Tag: 'ngày',
  Stunde: 'giờ',
  Minute: 'phút',
  Morgen: 'buổi sáng',
  Abend: 'buổi tối',
  Nacht: 'đêm',
  Buch: 'sách',
  Sprache: 'ngôn ngữ',
  Wort: 'từ',
  Frage: 'câu hỏi',
  Antwort: 'câu trả lời',
  Beispiel: 'ví dụ',
  Problem: 'vấn đề',
  Lösung: 'giải pháp',
  Meinung: 'ý kiến',
  Erfahrung: 'kinh nghiệm',
  Bedeutung: 'ý nghĩa',
  Gesellschaft: 'xã hội',
  Wirtschaft: 'kinh tế',
  Umwelt: 'môi trường',
  Bildung: 'giáo dục',
  Gesundheit: 'sức khỏe',
  Kultur: 'văn hóa',
  Wissenschaft: 'khoa học',
  Forschung: 'nghiên cứu',
  Technologie: 'công nghệ',
  Regierung: 'chính phủ',
  Supermarkt: 'siêu thị',
  Restaurant: 'nhà hàng',
  Bahnhof: 'nhà ga',
  Flughafen: 'sân bay',
  Krankenhaus: 'bệnh viện',
  Universität: 'đại học',
  Bibliothek: 'thư viện',
  Straße: 'đường phố',
  // ── Adjectives ──
  gut: 'tốt',
  schlecht: 'xấu, tệ',
  groß: 'lớn',
  klein: 'nhỏ',
  alt: 'cũ, già',
  neu: 'mới',
  jung: 'trẻ',
  schön: 'đẹp',
  wichtig: 'quan trọng',
  richtig: 'đúng',
  falsch: 'sai',
  möglich: 'có thể',
  nötig: 'cần thiết',
  schnell: 'nhanh',
  langsam: 'chậm',
  einfach: 'đơn giản',
  schwierig: 'khó',
  verschieden: 'khác nhau',
  besonder: 'đặc biệt',
  öffentlich: 'công cộng',
  politisch: 'chính trị',
  wirtschaftlich: 'kinh tế',
  // ── Adverbs ──
  hier: 'ở đây',
  dort: 'ở đó',
  heute: 'hôm nay',
  morgen: 'ngày mai',
  gestern: 'hôm qua',
  immer: 'luôn luôn',
  manchmal: 'thỉnh thoảng',
  oft: 'thường',
  nie: 'không bao giờ',
  schon: 'đã, rồi',
  noch: 'vẫn, còn',
  auch: 'cũng',
  sehr: 'rất',
  ganz: 'hoàn toàn',
  vielleicht: 'có lẽ',
  trotzdem: 'mặc dù vậy',
  deshalb: 'vì vậy',
  außerdem: 'ngoài ra',
  // ── Prepositions ──
  in: 'trong',
  auf: 'trên',
  an: 'ở, tại',
  mit: 'với',
  für: 'cho',
  von: 'từ, của',
  zu: 'đến, để',
  nach: 'sau, đến',
  über: 'về, trên',
  unter: 'dưới',
  vor: 'trước',
  hinter: 'sau, phía sau',
  neben: 'bên cạnh',
  zwischen: 'giữa',
  ohne: 'không có',
  gegen: 'chống lại',
  während: 'trong khi',
  wegen: 'vì',
  // ── Conjunctions ──
  und: 'và',
  oder: 'hoặc',
  aber: 'nhưng',
  denn: 'vì',
  weil: 'vì',
  dass: 'rằng',
  wenn: 'nếu, khi',
  als: 'khi (quá khứ)',
  obwohl: 'mặc dù',
  sondern: 'mà (là)',
  sowohl: 'cả...lẫn',
  weder: 'không...cũng không',
  jedoch: 'tuy nhiên',
  dennoch: 'tuy nhiên',
  folglich: 'do đó',
  // ── Numbers / Time ──
  Uhr: 'giờ (đồng hồ)',
  Montag: 'thứ Hai',
  Dienstag: 'thứ Ba',
  Mittwoch: 'thứ Tư',
  Donnerstag: 'thứ Năm',
  Freitag: 'thứ Sáu',
  Samstag: 'thứ Bảy',
  Sonntag: 'Chủ nhật',
  // ── Food / Daily ──
  Brot: 'bánh mì',
  Milch: 'sữa',
  Käse: 'phô mai',
  Butter: 'bơ',
  Obst: 'trái cây',
  Gemüse: 'rau',
  Fleisch: 'thịt',
  Fisch: 'cá',
  Kaffee: 'cà phê',
  Tee: 'trà',
  Schokolade: 'sô-cô-la',
  Kuchen: 'bánh',
  Geld: 'tiền',
  Preis: 'giá',
  Euro: 'Euro',
}

export async function GET(req: NextRequest) {
  const parsed = translateSchema.safeParse({
    word: req.nextUrl.searchParams.get('word'),
  })
  if (!parsed.success) {
    return NextResponse.json({ error: 'Missing word parameter' }, { status: 400 })
  }
  const cleanWord = parsed.data.word

  // 1) Check mini dictionary (case-insensitive)
  const dictEntry = MINI_DICT[cleanWord] || MINI_DICT[cleanWord.toLowerCase()] || MINI_DICT[cleanWord.charAt(0).toUpperCase() + cleanWord.slice(1).toLowerCase()]
  if (dictEntry) {
    return NextResponse.json({ word: cleanWord, translation: dictEntry, source: 'dict' })
  }

  // 2) Fallback: return a "not found" message — in production, call an external API
  return NextResponse.json({
    word: cleanWord,
    translation: `"${cleanWord}" — Nachschlagen im Wörterbuch`,
    source: 'fallback',
  })
}
