/**
 * audit-audio-json.ts — Deep QA Audit for Exported Audio Factory JSONs
 * 
 * Verifies that the JSON manifests generated by Gemini conform perfectly
 * to the `8-Audio-Factory` pipeline requirements:
 * 
 * 1. Strict Schema Compliance (all required keys exist)
 * 2. Voice Registry Validation (no hallucinated voice descriptions)
 * 3. Voice Consistency (A speaker must not change voices mid-script)
 * 4. Gender Sanity Check (Herr X cannot have a female voice, Frau X cannot be male)
 * 5. Formatting checks (No empty text, valid pause durations)
 * 
 * Run: npx tsx scripts/audit-audio-json.ts
 */

import * as fs from 'fs';
import * as path from 'path';

const AUDIO_FACTORY_DIR = "C:\\Users\\DMF Schule\\8-Audio-Factory\\data\\exams";

// The single source of truth for allowed voices
const VOICES = {
    narrator_f: "A 45-year-old formal German female narrator with a warm low contralto register, precise diction, controlled intonation, and no regional accent. Studio-quality microphone, close distance.",
    young_f: "A 26-year-old casual German female with a warm, natural, mid-register voice. Friendly conversational pacing, clear articulation, slight smile in delivery. Studio-quality microphone.",
    young_m: "A 24-year-old casual German male with a clear, energetic tenor voice. Natural conversational rhythm, friendly and engaged. Studio-quality microphone.",
    mid_m: "A 42-year-old formal German male with a calm, authoritative baritone voice. Precise enunciation, steady tempo, professional broadcast quality. Studio-quality microphone.",
    mid_f: "A 40-year-old professional German female with a clear, warm mezzo-soprano voice. Balanced pacing, confident delivery. Studio-quality microphone.",
    senior_m: "A 54-year-old formal German male professor voice with a deep, measured baritone. Academic authority, thoughtful pacing. Studio-quality microphone.",
    radio_f: "A 35-year-old German female radio host with a bright, engaging voice. Professional broadcast quality, varied intonation. Studio-quality microphone.",
    expert_f: "A 47-year-old formal German female scientist with a precise, analytical voice. Measured pace, academic register. Studio-quality microphone.",
};
const VALID_VOICE_DESCS = Object.values(VOICES);

interface Issue {
    severity: 'CRITICAL' | 'HIGH' | 'WARNING';
    type: string;
    detail: string;
}

function walkDir(dir: string): string[] {
    let results: string[] = [];
    const list = fs.readdirSync(dir);
    list.forEach((file) => {
        const fullPath = path.join(dir, file);
        const stat = fs.statSync(fullPath);
        if (stat && stat.isDirectory()) {
            results = results.concat(walkDir(fullPath));
        } else if (file.endsWith('.json')) {
            results.push(fullPath);
        }
    });
    return results;
}

function normalizeVoiceDesc(desc: string) {
    return desc.trim().replace(/\s+/g, ' ').toLowerCase();
}

function auditScript(filePath: string): Issue[] {
    const issues: Issue[] = [];
    let script: any;

    try {
        script = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
    } catch (e: any) {
        return [{ severity: 'CRITICAL', type: 'JSON_PARSE', detail: `Invalid JSON format: ${e.message}` }];
    }

    if (!script.lines || !Array.isArray(script.lines)) {
        return [{ severity: 'CRITICAL', type: 'SCHEMA', detail: `Missing or invalid 'lines' array.` }];
    }

    const speakerVoices = new Map<string, Set<string>>();

    script.lines.forEach((line: any, idx: number) => {
        const ln = idx + 1;
        
        // 1. Schema completeness
        const requiredKeys = ['speaker', 'speaker_role', 'voice_description', 'emotion', 'speed', 'pause_after', 'text', 'engine'];
        for (const k of requiredKeys) {
            if (line[k] === undefined || line[k] === null) {
                issues.push({ severity: 'CRITICAL', type: 'SCHEMA', detail: `Line ${ln} missing required key: ${k}` });
            }
        }

        // 2. Strict text check
        if (typeof line.text === 'string' && line.text.trim().length === 0) {
            issues.push({ severity: 'HIGH', type: 'EMPTY_TEXT', detail: `Line ${ln} has empty spoken text.` });
        }

        // 3. Pause & Speed bounds
        if (line.speed < 0.5 || line.speed > 2.0) {
            issues.push({ severity: 'HIGH', type: 'SPEED_OOB', detail: `Line ${ln} speed ${line.speed} is out of safe bounds (0.5 - 2.0)` });
        }
        if (line.pause_after < 0 || line.pause_after > 5) {
            issues.push({ severity: 'WARNING', type: 'PAUSE_OOB', detail: `Line ${ln} pause ${line.pause_after}s is strangely long or negative.` });
        }

        // 4. Voice Registry Match
        if (line.voice_description) {
            const descNorm = normalizeVoiceDesc(line.voice_description);
            const isValid = VALID_VOICE_DESCS.some(v => normalizeVoiceDesc(v) === descNorm);
            if (!isValid) {
                issues.push({ severity: 'CRITICAL', type: 'HALLUCINATED_VOICE', detail: `Line ${ln} uses a voice description not in Fuxie Registry: "${line.voice_description.substring(0, 40)}..."` });
            }

            // Track for consistency
            if (line.speaker) {
                const s = line.speaker.trim();
                if (!speakerVoices.has(s)) speakerVoices.set(s, new Set());
                speakerVoices.get(s)!.add(descNorm);

                // 5. Gender Sanity Checks
                const lowerName = s.toLowerCase();
                const isFemaleVoice = descNorm.includes("female");
                const isMaleVoice = /\bmale\b/.test(descNorm);

                if (lowerName.includes("herr ") && isFemaleVoice) {
                    issues.push({ severity: 'HIGH', type: 'GENDER_MISMATCH', detail: `Speaker '${s}' assigned a female voice.` });
                }
                if (lowerName.includes("frau ") && isMaleVoice) {
                    issues.push({ severity: 'HIGH', type: 'GENDER_MISMATCH', detail: `Speaker '${s}' assigned a male voice.` });
                }
            }
        }
    });

    // 6. Voice Consistency (Speaker shouldn't change voice mid-script)
    for (const [speaker, voices] of speakerVoices.entries()) {
        if (voices.size > 1) {
            issues.push({ severity: 'CRITICAL', type: 'VOICE_DRIFT', detail: `Speaker '${speaker}' switches between ${voices.size} different voice descriptions within the same script.` });
        }
    }

    return issues;
}

function main() {
    if (!fs.existsSync(AUDIO_FACTORY_DIR)) {
        console.error(`❌ Audio Factory export dir not found: ${AUDIO_FACTORY_DIR}`);
        return;
    }

    const files = walkDir(AUDIO_FACTORY_DIR);
    console.log(`\n🔍 Found ${files.length} JSON scripts to audit in 8-Audio-Factory\\data\\exams`);
    console.log('='.repeat(70));

    let clean = 0;
    let totalCritical = 0;
    let totalHigh = 0;

    let allIssues: any[] = [];
    files.forEach(file => {
        const issues = auditScript(file);
        if (issues.length === 0) {
            clean++;
        } else {
            allIssues.push({
                file: file.split('8-Audio-Factory\\data\\exams\\')[1],
                issues: issues
            });
            if (issues.some(i => i.severity === 'CRITICAL')) totalCritical++;
            if (issues.some(i => i.severity === 'HIGH')) totalHigh++;
        }
    });

    const reportFile = path.join(__dirname, 'audit-audio-issues.json');
    fs.writeFileSync(reportFile, JSON.stringify({
        totalScripts: files.length,
        cleanScripts: clean,
        totalCritical,
        totalHigh,
        failures: allIssues
    }, null, 2));

    console.log(`\n💾 Saved detailed report to ${reportFile}`);

    if (totalCritical > 0 || totalHigh > 0) {
         console.log('\n❌ QA FAILED. Scripts contain errors that will break the Audio Factory pipeline.');
         process.exit(1);
    } else {
        console.log('\n✅ QA PASSED. All exported JSON scripts meet the strict rendering requirements.');
    }
}

main();
