/**
 * A2 Vocabulary — Themes 11–14
 */
import { writeFileSync } from 'fs'
import path from 'path'
const D = 'content/a2/vocabulary'
function w(f: string, t: any, ws: any[]) { writeFileSync(path.join(D, f), JSON.stringify({ theme: t, words: ws }, null, 4) + '\n'); console.log(`  ✅ ${f}: ${ws.length} words — ${t.name}`); return ws.length }
let total = 0

// 11 — Freizeit & Kultur
total += w('11-freizeit-kultur.json', { slug: 'a2-freizeit-kultur', name: 'Freizeit & Kultur', nameVi: 'Giải trí & Văn hóa', nameEn: 'Leisure & Culture', sortOrder: 11 }, [
    { word: 'Veranstaltung', article: 'FEMININ', plural: 'die Veranstaltungen', wordType: 'NOMEN', meaningVi: 'sự kiện', meaningEn: 'event', exampleSentence1: 'Die Veranstaltung war toll.', exampleTranslation1: 'Sự kiện tuyệt vời.', exampleSentence2: 'Welche Veranstaltung besuchst du?', exampleTranslation2: 'Bạn đi sự kiện nào?' },
    { word: 'Konzert', article: 'NEUTRUM', plural: 'die Konzerte', wordType: 'NOMEN', meaningVi: 'buổi hòa nhạc', meaningEn: 'concert', exampleSentence1: 'Das Konzert war super.', exampleTranslation1: 'Buổi hòa nhạc tuyệt.', exampleSentence2: 'Wir gehen ins Konzert.', exampleTranslation2: 'Chúng tôi đi xem hòa nhạc.' },
    { word: 'Ausstellung', article: 'FEMININ', plural: 'die Ausstellungen', wordType: 'NOMEN', meaningVi: 'triển lãm', meaningEn: 'exhibition', exampleSentence1: 'Die Ausstellung ist interessant.', exampleTranslation1: 'Triển lãm thú vị.', exampleSentence2: 'Wir besuchen eine Ausstellung.', exampleTranslation2: 'Chúng tôi thăm triển lãm.' },
    { word: 'Museum', article: 'NEUTRUM', plural: 'die Museen', wordType: 'NOMEN', meaningVi: 'bảo tàng', meaningEn: 'museum', exampleSentence1: 'Das Museum ist groß.', exampleTranslation1: 'Bảo tàng rộng.', exampleSentence2: 'Wir gehen ins Museum.', exampleTranslation2: 'Đi bảo tàng.' },
    { word: 'Theater', article: 'NEUTRUM', plural: 'die Theater', wordType: 'NOMEN', meaningVi: 'nhà hát', meaningEn: 'theater', exampleSentence1: 'Wir gehen ins Theater.', exampleTranslation1: 'Đi xem kịch.', exampleSentence2: 'Das Theater ist alt.', exampleTranslation2: 'Nhà hát cũ.' },
    { word: 'Verein', article: 'MASKULIN', plural: 'die Vereine', wordType: 'NOMEN', meaningVi: 'câu lạc bộ, hiệp hội', meaningEn: 'club, association', exampleSentence1: 'Ich bin im Fußballverein.', exampleTranslation1: 'Tôi ở CLB bóng đá.', exampleSentence2: 'Der Verein hat 100 Mitglieder.', exampleTranslation2: 'CLB có 100 thành viên.' },
    { word: 'Mitglied', article: 'NEUTRUM', plural: 'die Mitglieder', wordType: 'NOMEN', meaningVi: 'thành viên', meaningEn: 'member', exampleSentence1: 'Ich bin Mitglied im Verein.', exampleTranslation1: 'Tôi là thành viên CLB.', exampleSentence2: 'Neue Mitglieder willkommen!', exampleTranslation2: 'Chào mừng thành viên mới!' },
    { word: 'Mannschaft', article: 'FEMININ', plural: 'die Mannschaften', wordType: 'NOMEN', meaningVi: 'đội', meaningEn: 'team', exampleSentence1: 'Die Mannschaft hat gewonnen.', exampleTranslation1: 'Đội đã thắng.', exampleSentence2: 'Unsere Mannschaft ist stark.', exampleTranslation2: 'Đội chúng tôi mạnh.' },
    { word: 'Wettbewerb', article: 'MASKULIN', plural: 'die Wettbewerbe', wordType: 'NOMEN', meaningVi: 'cuộc thi', meaningEn: 'competition', exampleSentence1: 'Der Wettbewerb war spannend.', exampleTranslation1: 'Cuộc thi hấp dẫn.', exampleSentence2: 'Ich nehme am Wettbewerb teil.', exampleTranslation2: 'Tôi tham gia cuộc thi.' },
    { word: 'gewinnen', wordType: 'VERB', meaningVi: 'thắng', meaningEn: 'to win', conjugation: { praesens: { ich: 'gewinne', du: 'gewinnst', er_sie_es: 'gewinnt', wir: 'gewinnen', ihr: 'gewinnt', sie_Sie: 'gewinnen' }, isIrregular: true, isSeparable: false }, exampleSentence1: 'Wir haben gewonnen!', exampleTranslation1: 'Chúng tôi thắng!', exampleSentence2: 'Wer hat gewonnen?', exampleTranslation2: 'Ai thắng?' },
    { word: 'verlieren', wordType: 'VERB', meaningVi: 'thua, mất', meaningEn: 'to lose', conjugation: { praesens: { ich: 'verliere', du: 'verlierst', er_sie_es: 'verliert', wir: 'verlieren', ihr: 'verliert', sie_Sie: 'verlieren' }, isIrregular: true, isSeparable: false }, exampleSentence1: 'Wir haben verloren.', exampleTranslation1: 'Chúng tôi thua.', exampleSentence2: 'Verliere nicht den Mut.', exampleTranslation2: 'Đừng mất can đảm.' },
    { word: 'trainieren', wordType: 'VERB', meaningVi: 'tập luyện', meaningEn: 'to train', conjugation: { praesens: { ich: 'trainiere', du: 'trainierst', er_sie_es: 'trainiert', wir: 'trainieren', ihr: 'trainiert', sie_Sie: 'trainieren' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Er trainiert jeden Tag.', exampleTranslation1: 'Anh ấy tập mỗi ngày.', exampleSentence2: 'Wir trainieren im Fitnessstudio.', exampleTranslation2: 'Tập ở phòng gym.' },
    { word: 'Leidenschaft', article: 'FEMININ', plural: 'die Leidenschaften', wordType: 'NOMEN', meaningVi: 'đam mê', meaningEn: 'passion', exampleSentence1: 'Musik ist meine Leidenschaft.', exampleTranslation1: 'Âm nhạc là đam mê.', exampleSentence2: 'Mit Leidenschaft arbeiten.', exampleTranslation2: 'Làm việc với đam mê.' },
    { word: 'sich entspannen', wordType: 'VERB', meaningVi: 'thư giãn', meaningEn: 'to relax', conjugation: { praesens: { ich: 'entspanne mich', du: 'entspannst dich', er_sie_es: 'entspannt sich', wir: 'entspannen uns', ihr: 'entspannt euch', sie_Sie: 'entspannen sich' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Ich muss mich entspannen.', exampleTranslation1: 'Tôi cần thư giãn.', exampleSentence2: 'Am Wochenende entspanne ich mich.', exampleTranslation2: 'Cuối tuần tôi thư giãn.' },
    { word: 'sich langweilen', wordType: 'VERB', meaningVi: 'chán', meaningEn: 'to be bored', conjugation: { praesens: { ich: 'langweile mich', du: 'langweilst dich', er_sie_es: 'langweilt sich', wir: 'langweilen uns', ihr: 'langweilt euch', sie_Sie: 'langweilen sich' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Ich langweile mich.', exampleTranslation1: 'Tôi chán.', exampleSentence2: 'Langweilst du dich?', exampleTranslation2: 'Bạn chán à?' },
    { word: 'Eintrittskarte', article: 'FEMININ', plural: 'die Eintrittskarten', wordType: 'NOMEN', meaningVi: 'vé vào cửa', meaningEn: 'admission ticket', exampleSentence1: 'Zwei Eintrittskarten, bitte.', exampleTranslation1: 'Hai vé, xin.', exampleSentence2: 'Die Eintrittskarte kostet 10 Euro.', exampleTranslation2: 'Vé vào cửa 10 Euro.' },
    { word: 'Ermäßigung', article: 'FEMININ', plural: 'die Ermäßigungen', wordType: 'NOMEN', meaningVi: 'giảm giá', meaningEn: 'discount, reduction', exampleSentence1: 'Gibt es eine Ermäßigung?', exampleTranslation1: 'Có giảm giá không?', exampleSentence2: 'Studenten bekommen Ermäßigung.', exampleTranslation2: 'Sinh viên được giảm giá.' },
    { word: 'spannend', wordType: 'ADJEKTIV', meaningVi: 'hấp dẫn, gay cấn', meaningEn: 'exciting, thrilling', exampleSentence1: 'Der Film war spannend.', exampleTranslation1: 'Phim hấp dẫn.', exampleSentence2: 'Ein spannendes Buch.', exampleTranslation2: 'Sách hay.' },
    { word: 'langweilig', wordType: 'ADJEKTIV', meaningVi: 'nhàm chán', meaningEn: 'boring', exampleSentence1: 'Der Film war langweilig.', exampleTranslation1: 'Phim nhàm chán.', exampleSentence2: 'Mir ist langweilig.', exampleTranslation2: 'Tôi chán.' },
    { word: 'unterhaltsam', wordType: 'ADJEKTIV', meaningVi: 'giải trí, thú vị', meaningEn: 'entertaining', exampleSentence1: 'Die Show war unterhaltsam.', exampleTranslation1: 'Show thú vị.', exampleSentence2: 'Ein unterhaltsamer Abend.', exampleTranslation2: 'Buổi tối thú vị.' },
])

// 12 — Kommunikation & Medien
total += w('12-kommunikation-medien.json', { slug: 'a2-kommunikation-medien', name: 'Kommunikation & Medien', nameVi: 'Truyền thông & Phương tiện', nameEn: 'Communication & Media', sortOrder: 12 }, [
    { word: 'Nachricht', article: 'FEMININ', plural: 'die Nachrichten', wordType: 'NOMEN', meaningVi: 'tin nhắn, tin tức', meaningEn: 'message, news', exampleSentence1: 'Hast du die Nachricht gelesen?', exampleTranslation1: 'Bạn đọc tin chưa?', exampleSentence2: 'Die Nachrichten kommen um 8.', exampleTranslation2: 'Tin tức lúc 8 giờ.' },
    { word: 'Bericht', article: 'MASKULIN', plural: 'die Berichte', wordType: 'NOMEN', meaningVi: 'báo cáo', meaningEn: 'report', exampleSentence1: 'Der Bericht ist fertig.', exampleTranslation1: 'Báo cáo xong.', exampleSentence2: 'Schreiben Sie einen Bericht.', exampleTranslation2: 'Viết báo cáo.' },
    { word: 'Artikel', article: 'MASKULIN', plural: 'die Artikel', wordType: 'NOMEN', meaningVi: 'bài báo', meaningEn: 'article', exampleSentence1: 'Der Artikel ist interessant.', exampleTranslation1: 'Bài báo thú vị.', exampleSentence2: 'Ich lese einen Artikel.', exampleTranslation2: 'Tôi đọc bài báo.' },
    { word: 'Zeitschrift', article: 'FEMININ', plural: 'die Zeitschriften', wordType: 'NOMEN', meaningVi: 'tạp chí', meaningEn: 'magazine', exampleSentence1: 'Die Zeitschrift kommt monatlich.', exampleTranslation1: 'Tạp chí ra hàng tháng.', exampleSentence2: 'Welche Zeitschrift liest du?', exampleTranslation2: 'Bạn đọc tạp chí nào?' },
    { word: 'Sendung', article: 'FEMININ', plural: 'die Sendungen', wordType: 'NOMEN', meaningVi: 'chương trình (TV)', meaningEn: 'program, show', exampleSentence1: 'Die Sendung ist um 20 Uhr.', exampleTranslation1: 'Chương trình lúc 20h.', exampleSentence2: 'Welche Sendung siehst du?', exampleTranslation2: 'Bạn xem chương trình gì?' },
    { word: 'Werbung', article: 'FEMININ', plural: 'die Werbungen', wordType: 'NOMEN', meaningVi: 'quảng cáo', meaningEn: 'advertising', exampleSentence1: 'Die Werbung ist überall.', exampleTranslation1: 'Quảng cáo khắp nơi.', exampleSentence2: 'Zu viel Werbung.', exampleTranslation2: 'Quá nhiều quảng cáo.' },
    { word: 'Bildschirm', article: 'MASKULIN', plural: 'die Bildschirme', wordType: 'NOMEN', meaningVi: 'màn hình', meaningEn: 'screen', exampleSentence1: 'Der Bildschirm ist groß.', exampleTranslation1: 'Màn hình lớn.', exampleSentence2: 'Schau auf den Bildschirm.', exampleTranslation2: 'Nhìn lên màn hình.' },
    { word: 'Drucker', article: 'MASKULIN', plural: 'die Drucker', wordType: 'NOMEN', meaningVi: 'máy in', meaningEn: 'printer', exampleSentence1: 'Der Drucker funktioniert nicht.', exampleTranslation1: 'Máy in không hoạt động.', exampleSentence2: 'Ich brauche einen neuen Drucker.', exampleTranslation2: 'Tôi cần máy in mới.' },
    { word: 'herunterladen', wordType: 'VERB', meaningVi: 'tải xuống', meaningEn: 'to download', conjugation: { praesens: { ich: 'lade herunter', du: 'lädst herunter', er_sie_es: 'lädt herunter', wir: 'laden herunter', ihr: 'ladet herunter', sie_Sie: 'laden herunter' }, isIrregular: true, isSeparable: true }, exampleSentence1: 'Ich lade die App herunter.', exampleTranslation1: 'Tôi tải app.', exampleSentence2: 'Lade das Dokument herunter!', exampleTranslation2: 'Tải tài liệu!' },
    { word: 'ausdrucken', wordType: 'VERB', meaningVi: 'in ra', meaningEn: 'to print out', conjugation: { praesens: { ich: 'drucke aus', du: 'druckst aus', er_sie_es: 'druckt aus', wir: 'drucken aus', ihr: 'druckt aus', sie_Sie: 'drucken aus' }, isIrregular: false, isSeparable: true }, exampleSentence1: 'Kannst du das ausdrucken?', exampleTranslation1: 'Bạn in được không?', exampleSentence2: 'Ich drucke den Brief aus.', exampleTranslation2: 'Tôi in thư.' },
    { word: 'Passwort', article: 'NEUTRUM', plural: 'die Passwörter', wordType: 'NOMEN', meaningVi: 'mật khẩu', meaningEn: 'password', exampleSentence1: 'Vergiss dein Passwort nicht!', exampleTranslation1: 'Đừng quên mật khẩu!', exampleSentence2: 'Ändern Sie Ihr Passwort.', exampleTranslation2: 'Đổi mật khẩu.' },
    { word: 'Datei', article: 'FEMININ', plural: 'die Dateien', wordType: 'NOMEN', meaningVi: 'tệp tin', meaningEn: 'file', exampleSentence1: 'Die Datei ist groß.', exampleTranslation1: 'Tệp tin lớn.', exampleSentence2: 'Öffne die Datei.', exampleTranslation2: 'Mở tệp tin.' },
    { word: 'Daten', plural: 'die Daten', wordType: 'NOMEN', meaningVi: 'dữ liệu', meaningEn: 'data', notes: 'Nur Plural', exampleSentence1: 'Die Daten sind wichtig.', exampleTranslation1: 'Dữ liệu quan trọng.', exampleSentence2: 'Speichern Sie die Daten.', exampleTranslation2: 'Lưu dữ liệu.' },
    { word: 'Verbindung', article: 'FEMININ', plural: 'die Verbindungen', wordType: 'NOMEN', meaningVi: 'kết nối, liên lạc', meaningEn: 'connection', exampleSentence1: 'Die Verbindung ist schlecht.', exampleTranslation1: 'Kết nối kém.', exampleSentence2: 'Keine Internetverbindung.', exampleTranslation2: 'Không có kết nối Internet.' },
    { word: 'Anruf', article: 'MASKULIN', plural: 'die Anrufe', wordType: 'NOMEN', meaningVi: 'cuộc gọi', meaningEn: 'phone call', exampleSentence1: 'Danke für den Anruf.', exampleTranslation1: 'Cảm ơn đã gọi.', exampleSentence2: 'Ich erwarte einen Anruf.', exampleTranslation2: 'Tôi đợi cuộc gọi.' },
    { word: 'anrufen', wordType: 'VERB', meaningVi: 'gọi điện', meaningEn: 'to call', conjugation: { praesens: { ich: 'rufe an', du: 'rufst an', er_sie_es: 'ruft an', wir: 'rufen an', ihr: 'ruft an', sie_Sie: 'rufen an' }, isIrregular: true, isSeparable: true }, exampleSentence1: 'Ich rufe dich an.', exampleTranslation1: 'Tôi gọi cho bạn.', exampleSentence2: 'Ruf mich an!', exampleTranslation2: 'Gọi cho tôi!' },
    { word: 'sich unterhalten', wordType: 'VERB', meaningVi: 'trò chuyện', meaningEn: 'to chat, converse', conjugation: { praesens: { ich: 'unterhalte mich', du: 'unterhältst dich', er_sie_es: 'unterhält sich', wir: 'unterhalten uns', ihr: 'unterhaltet euch', sie_Sie: 'unterhalten sich' }, isIrregular: true, isSeparable: false }, exampleSentence1: 'Wir unterhalten uns gern.', exampleTranslation1: 'Chúng tôi thích trò chuyện.', exampleSentence2: 'Worüber unterhältst du dich?', exampleTranslation2: 'Bạn nói về gì?' },
    { word: 'online', wordType: 'ADJEKTIV', meaningVi: 'trực tuyến', meaningEn: 'online', exampleSentence1: 'Ich kaufe online ein.', exampleTranslation1: 'Tôi mua hàng trực tuyến.', exampleSentence2: 'Der Kurs ist online.', exampleTranslation2: 'Khóa học trực tuyến.' },
])

// 13 — Reisen & Tourismus
total += w('13-reisen-tourismus.json', { slug: 'a2-reisen-tourismus', name: 'Reisen & Tourismus', nameVi: 'Du lịch & Tham quan', nameEn: 'Travel & Tourism', sortOrder: 13 }, [
    { word: 'Reise', article: 'FEMININ', plural: 'die Reisen', wordType: 'NOMEN', meaningVi: 'chuyến đi', meaningEn: 'trip, journey', exampleSentence1: 'Die Reise war toll.', exampleTranslation1: 'Chuyến đi tuyệt.', exampleSentence2: 'Wir planen eine Reise.', exampleTranslation2: 'Chúng tôi lên kế hoạch chuyến đi.' },
    { word: 'Unterkunft', article: 'FEMININ', plural: 'die Unterkünfte', wordType: 'NOMEN', meaningVi: 'chỗ ở', meaningEn: 'accommodation', exampleSentence1: 'Wir suchen eine Unterkunft.', exampleTranslation1: 'Chúng tôi tìm chỗ ở.', exampleSentence2: 'Die Unterkunft ist günstig.', exampleTranslation2: 'Chỗ ở rẻ.' },
    { word: 'Sehenswürdigkeit', article: 'FEMININ', plural: 'die Sehenswürdigkeiten', wordType: 'NOMEN', meaningVi: 'điểm tham quan', meaningEn: 'sight, attraction', exampleSentence1: 'Berlin hat viele Sehenswürdigkeiten.', exampleTranslation1: 'Berlin có nhiều điểm tham quan.', exampleSentence2: 'Welche Sehenswürdigkeiten gibt es?', exampleTranslation2: 'Có điểm tham quan nào?' },
    { word: 'Reiseführer', article: 'MASKULIN', plural: 'die Reiseführer', wordType: 'NOMEN', meaningVi: 'sách hướng dẫn du lịch', meaningEn: 'travel guide', exampleSentence1: 'Der Reiseführer ist hilfreich.', exampleTranslation1: 'Sách HDL hữu ích.', exampleSentence2: 'Kaufst du einen Reiseführer?', exampleTranslation2: 'Bạn mua sách HDL không?' },
    { word: 'Rundfahrt', article: 'FEMININ', plural: 'die Rundfahrten', wordType: 'NOMEN', meaningVi: 'tour tham quan', meaningEn: 'sightseeing tour', exampleSentence1: 'Wir machen eine Rundfahrt.', exampleTranslation1: 'Chúng tôi đi tour.', exampleSentence2: 'Die Rundfahrt dauert 2 Stunden.', exampleTranslation2: 'Tour kéo dài 2 giờ.' },
    { word: 'buchen', wordType: 'VERB', meaningVi: 'đặt (vé, phòng)', meaningEn: 'to book', conjugation: { praesens: { ich: 'buche', du: 'buchst', er_sie_es: 'bucht', wir: 'buchen', ihr: 'bucht', sie_Sie: 'buchen' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Ich buche ein Hotelzimmer.', exampleTranslation1: 'Tôi đặt phòng khách sạn.', exampleSentence2: 'Hast du den Flug gebucht?', exampleTranslation2: 'Bạn đặt vé máy bay chưa?' },
    { word: 'Buchung', article: 'FEMININ', plural: 'die Buchungen', wordType: 'NOMEN', meaningVi: 'đặt chỗ', meaningEn: 'booking, reservation', exampleSentence1: 'Die Buchung ist bestätigt.', exampleTranslation1: 'Đặt chỗ xác nhận.', exampleSentence2: 'Ich möchte die Buchung stornieren.', exampleTranslation2: 'Tôi muốn hủy đặt chỗ.' },
    { word: 'Verspätung', article: 'FEMININ', plural: 'die Verspätungen', wordType: 'NOMEN', meaningVi: 'sự chậm trễ', meaningEn: 'delay', exampleSentence1: 'Der Zug hat Verspätung.', exampleTranslation1: 'Tàu bị trễ.', exampleSentence2: '20 Minuten Verspätung.', exampleTranslation2: 'Trễ 20 phút.' },
    { word: 'Ankunft', article: 'FEMININ', plural: 'die Ankünfte', wordType: 'NOMEN', meaningVi: 'sự đến', meaningEn: 'arrival', exampleSentence1: 'Die Ankunft ist um 14 Uhr.', exampleTranslation1: 'Đến lúc 14h.', exampleSentence2: 'Nach der Ankunft.', exampleTranslation2: 'Sau khi đến nơi.' },
    { word: 'Abfahrt', article: 'FEMININ', plural: 'die Abfahrten', wordType: 'NOMEN', meaningVi: 'sự khởi hành', meaningEn: 'departure', exampleSentence1: 'Die Abfahrt ist um 8 Uhr.', exampleTranslation1: 'Khởi hành lúc 8h.', exampleSentence2: 'Vor der Abfahrt.', exampleTranslation2: 'Trước khi khởi hành.' },
    { word: 'umsteigen', wordType: 'VERB', meaningVi: 'chuyển (tàu/xe)', meaningEn: 'to change (trains)', conjugation: { praesens: { ich: 'steige um', du: 'steigst um', er_sie_es: 'steigt um', wir: 'steigen um', ihr: 'steigt um', sie_Sie: 'steigen um' }, isIrregular: true, isSeparable: true }, exampleSentence1: 'Sie müssen in München umsteigen.', exampleTranslation1: 'Bạn phải đổi tàu ở München.', exampleSentence2: 'Wo muss ich umsteigen?', exampleTranslation2: 'Tôi phải đổi ở đâu?' },
    { word: 'Hin- und Rückfahrt', wordType: 'PHRASE', meaningVi: 'vé khứ hồi', meaningEn: 'round trip', exampleSentence1: 'Hin- und Rückfahrt, bitte.', exampleTranslation1: 'Vé khứ hồi.', exampleSentence2: 'Nur Hinfahrt oder Hin- und Rückfahrt?', exampleTranslation2: 'Một chiều hay khứ hồi?' },
    { word: 'Gepäck', article: 'NEUTRUM', plural: '-', wordType: 'NOMEN', meaningVi: 'hành lý', meaningEn: 'luggage', exampleSentence1: 'Das Gepäck ist schwer.', exampleTranslation1: 'Hành lý nặng.', exampleSentence2: 'Wo ist mein Gepäck?', exampleTranslation2: 'Hành lý tôi đâu?' },
    { word: 'Koffer', article: 'MASKULIN', plural: 'die Koffer', wordType: 'NOMEN', meaningVi: 'vali', meaningEn: 'suitcase', exampleSentence1: 'Pack den Koffer!', exampleTranslation1: 'Xếp vali!', exampleSentence2: 'Der Koffer ist voll.', exampleTranslation2: 'Vali đầy.' },
    { word: 'Rezeption', article: 'FEMININ', plural: 'die Rezeptionen', wordType: 'NOMEN', meaningVi: 'lễ tân', meaningEn: 'reception', exampleSentence1: 'Fragen Sie an der Rezeption.', exampleTranslation1: 'Hỏi lễ tân.', exampleSentence2: 'Die Rezeption ist im Erdgeschoss.', exampleTranslation2: 'Lễ tân ở tầng trệt.' },
    { word: 'Einzelzimmer', article: 'NEUTRUM', plural: 'die Einzelzimmer', wordType: 'NOMEN', meaningVi: 'phòng đơn', meaningEn: 'single room', exampleSentence1: 'Ein Einzelzimmer, bitte.', exampleTranslation1: 'Phòng đơn.', exampleSentence2: 'Das Einzelzimmer kostet 80 Euro.', exampleTranslation2: 'Phòng đơn 80 Euro.' },
    { word: 'Doppelzimmer', article: 'NEUTRUM', plural: 'die Doppelzimmer', wordType: 'NOMEN', meaningVi: 'phòng đôi', meaningEn: 'double room', exampleSentence1: 'Ein Doppelzimmer für zwei Nächte.', exampleTranslation1: 'Phòng đôi cho 2 đêm.', exampleSentence2: 'Das Doppelzimmer mit Frühstück.', exampleTranslation2: 'Phòng đôi có ăn sáng.' },
    { word: 'sich beschweren', wordType: 'VERB', meaningVi: 'phàn nàn', meaningEn: 'to complain', conjugation: { praesens: { ich: 'beschwere mich', du: 'beschwerst dich', er_sie_es: 'beschwert sich', wir: 'beschweren uns', ihr: 'beschwert euch', sie_Sie: 'beschweren sich' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Ich möchte mich beschweren.', exampleTranslation1: 'Tôi muốn phàn nàn.', exampleSentence2: 'Worüber beschweren Sie sich?', exampleTranslation2: 'Bạn phàn nàn gì?' },
])

// 14 — Zeit & Feiertage
total += w('14-zeit-feiertage.json', { slug: 'a2-zeit-feiertage', name: 'Zeit & Feiertage', nameVi: 'Thời gian & Lễ hội', nameEn: 'Time & Holidays', sortOrder: 14 }, [
    { word: 'Weihnachten', article: 'NEUTRUM', plural: '-', wordType: 'NOMEN', meaningVi: 'Giáng sinh', meaningEn: 'Christmas', exampleSentence1: 'Frohe Weihnachten!', exampleTranslation1: 'Giáng sinh vui vẻ!', exampleSentence2: 'Weihnachten ist am 25. Dezember.', exampleTranslation2: 'Giáng sinh ngày 25/12.' },
    { word: 'Ostern', article: 'NEUTRUM', plural: '-', wordType: 'NOMEN', meaningVi: 'lễ Phục sinh', meaningEn: 'Easter', exampleSentence1: 'Frohe Ostern!', exampleTranslation1: 'Phục sinh vui vẻ!', exampleSentence2: 'Ostern ist im Frühling.', exampleTranslation2: 'Phục sinh vào mùa xuân.' },
    { word: 'Silvester', article: 'NEUTRUM', plural: '-', wordType: 'NOMEN', meaningVi: 'đêm giao thừa', meaningEn: 'New Year\'s Eve', exampleSentence1: 'An Silvester feiern wir.', exampleTranslation1: 'Đêm giao thừa chúng tôi ăn mừng.', exampleSentence2: 'Was machst du an Silvester?', exampleTranslation2: 'Bạn làm gì đêm giao thừa?' },
    { word: 'Feiertag', article: 'MASKULIN', plural: 'die Feiertage', wordType: 'NOMEN', meaningVi: 'ngày lễ', meaningEn: 'holiday', exampleSentence1: 'Morgen ist ein Feiertag.', exampleTranslation1: 'Ngày mai là ngày lễ.', exampleSentence2: 'An Feiertagen arbeiten wir nicht.', exampleTranslation2: 'Ngày lễ không làm việc.' },
    { word: 'Jahreszeit', article: 'FEMININ', plural: 'die Jahreszeiten', wordType: 'NOMEN', meaningVi: 'mùa', meaningEn: 'season', exampleSentence1: 'Welche Jahreszeit magst du?', exampleTranslation1: 'Bạn thích mùa nào?', exampleSentence2: 'Es gibt vier Jahreszeiten.', exampleTranslation2: 'Có 4 mùa.' },
    { word: 'Frühling', article: 'MASKULIN', plural: '-', wordType: 'NOMEN', meaningVi: 'mùa xuân', meaningEn: 'spring', exampleSentence1: 'Im Frühling blühen die Blumen.', exampleTranslation1: 'Mùa xuân hoa nở.', exampleSentence2: 'Der Frühling ist warm.', exampleTranslation2: 'Mùa xuân ấm.' },
    { word: 'Herbst', article: 'MASKULIN', plural: '-', wordType: 'NOMEN', meaningVi: 'mùa thu', meaningEn: 'autumn', exampleSentence1: 'Im Herbst fallen die Blätter.', exampleTranslation1: 'Mùa thu lá rụng.', exampleSentence2: 'Der Herbst ist bunt.', exampleTranslation2: 'Mùa thu sắc màu.' },
    { word: 'Zukunft', article: 'FEMININ', plural: '-', wordType: 'NOMEN', meaningVi: 'tương lai', meaningEn: 'future', exampleSentence1: 'Was planst du für die Zukunft?', exampleTranslation1: 'Bạn kế hoạch gì cho tương lai?', exampleSentence2: 'In Zukunft.', exampleTranslation2: 'Trong tương lai.' },
    { word: 'Vergangenheit', article: 'FEMININ', plural: '-', wordType: 'NOMEN', meaningVi: 'quá khứ', meaningEn: 'past', exampleSentence1: 'Das liegt in der Vergangenheit.', exampleTranslation1: 'Điều đó ở quá khứ.', exampleSentence2: 'Die Vergangenheit ist vorbei.', exampleTranslation2: 'Quá khứ đã qua.' },
    { word: 'Gegenwart', article: 'FEMININ', plural: '-', wordType: 'NOMEN', meaningVi: 'hiện tại', meaningEn: 'present', exampleSentence1: 'Lebe in der Gegenwart.', exampleTranslation1: 'Sống ở hiện tại.', exampleSentence2: 'Die Gegenwart ist wichtig.', exampleTranslation2: 'Hiện tại quan trọng.' },
    { word: 'Zeitraum', article: 'MASKULIN', plural: 'die Zeiträume', wordType: 'NOMEN', meaningVi: 'khoảng thời gian', meaningEn: 'period of time', exampleSentence1: 'In welchem Zeitraum?', exampleTranslation1: 'Trong khoảng thời gian nào?', exampleSentence2: 'Der Zeitraum ist kurz.', exampleTranslation2: 'Khoảng thời gian ngắn.' },
    { word: 'Termin', article: 'MASKULIN', plural: 'die Termine', wordType: 'NOMEN', meaningVi: 'cuộc hẹn', meaningEn: 'appointment', exampleSentence1: 'Ich habe einen Termin.', exampleTranslation1: 'Tôi có cuộc hẹn.', exampleSentence2: 'Können wir einen Termin machen?', exampleTranslation2: 'Chúng ta hẹn được không?' },
    { word: 'verschieben', wordType: 'VERB', meaningVi: 'hoãn lại, dời', meaningEn: 'to postpone', conjugation: { praesens: { ich: 'verschiebe', du: 'verschiebst', er_sie_es: 'verschiebt', wir: 'verschieben', ihr: 'verschiebt', sie_Sie: 'verschieben' }, isIrregular: true, isSeparable: false }, exampleSentence1: 'Können wir den Termin verschieben?', exampleTranslation1: 'Dời cuộc hẹn được không?', exampleSentence2: 'Das Meeting wurde verschoben.', exampleTranslation2: 'Cuộc họp bị hoãn.' },
    { word: 'absagen', wordType: 'VERB', meaningVi: 'hủy bỏ', meaningEn: 'to cancel', conjugation: { praesens: { ich: 'sage ab', du: 'sagst ab', er_sie_es: 'sagt ab', wir: 'sagen ab', ihr: 'sagt ab', sie_Sie: 'sagen ab' }, isIrregular: false, isSeparable: true }, exampleSentence1: 'Ich muss den Termin absagen.', exampleTranslation1: 'Tôi phải hủy cuộc hẹn.', exampleSentence2: 'Die Party wurde abgesagt.', exampleTranslation2: 'Buổi tiệc bị hủy.' },
    { word: 'zusagen', wordType: 'VERB', meaningVi: 'nhận lời', meaningEn: 'to accept, confirm', conjugation: { praesens: { ich: 'sage zu', du: 'sagst zu', er_sie_es: 'sagt zu', wir: 'sagen zu', ihr: 'sagt zu', sie_Sie: 'sagen zu' }, isIrregular: false, isSeparable: true }, exampleSentence1: 'Ich sage gern zu.', exampleTranslation1: 'Tôi nhận lời.', exampleSentence2: 'Wer hat zugesagt?', exampleTranslation2: 'Ai đã nhận lời?' },
    { word: 'dauern', wordType: 'VERB', meaningVi: 'kéo dài', meaningEn: 'to last, take (time)', conjugation: { praesens: { ich: 'dauere', du: 'dauerst', er_sie_es: 'dauert', wir: 'dauern', ihr: 'dauert', sie_Sie: 'dauern' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Wie lange dauert das?', exampleTranslation1: 'Mất bao lâu?', exampleSentence2: 'Die Reise dauert 3 Stunden.', exampleTranslation2: 'Chuyến đi mất 3 giờ.' },
    { word: 'pünktlich', wordType: 'ADJEKTIV', meaningVi: 'đúng giờ', meaningEn: 'punctual, on time', exampleSentence1: 'Sei bitte pünktlich!', exampleTranslation1: 'Hãy đúng giờ!', exampleSentence2: 'Der Zug kommt pünktlich.', exampleTranslation2: 'Tàu đến đúng giờ.' },
    { word: 'rechtzeitig', wordType: 'ADVERB', meaningVi: 'kịp lúc', meaningEn: 'in time, timely', exampleSentence1: 'Komm rechtzeitig!', exampleTranslation1: 'Đến kịp lúc!', exampleSentence2: 'Wir sind rechtzeitig angekommen.', exampleTranslation2: 'Chúng tôi đến kịp.' },
])

console.log(`\n📊 Batch 6 total: ${total} words (themes 11-14)`)
