/**
 * A2 Vocabulary — Themes 02–10 (batch 2)
 */
import { writeFileSync } from 'fs'
import path from 'path'
const D = 'content/a2/vocabulary'
function w(f: string, t: any, ws: any[]) { writeFileSync(path.join(D, f), JSON.stringify({ theme: t, words: ws }, null, 4) + '\n'); console.log(`  ✅ ${f}: ${ws.length} words — ${t.name}`); return ws.length }
let total = 0

// 02 — Familie & Soziales
total += w('02-familie-soziales.json', { slug: 'a2-familie-soziales', name: 'Familie & Soziales', nameVi: 'Gia đình & Xã hội', nameEn: 'Family & Social Life', sortOrder: 2 }, [
    { word: 'Beziehung', article: 'FEMININ', plural: 'die Beziehungen', wordType: 'NOMEN', meaningVi: 'mối quan hệ', meaningEn: 'relationship', exampleSentence1: 'Sie sind in einer Beziehung.', exampleTranslation1: 'Họ đang hẹn hò.', exampleSentence2: 'Die Beziehung ist gut.', exampleTranslation2: 'Mối quan hệ tốt đẹp.' },
    { word: 'Partner', article: 'MASKULIN', plural: 'die Partner', wordType: 'NOMEN', meaningVi: 'bạn đời, đối tác', meaningEn: 'partner', exampleSentence1: 'Mein Partner heißt Tom.', exampleTranslation1: 'Bạn đời của tôi tên Tom.', exampleSentence2: 'Er ist ein guter Partner.', exampleTranslation2: 'Anh ấy là đối tác tốt.' },
    { word: 'Partnerin', article: 'FEMININ', plural: 'die Partnerinnen', wordType: 'NOMEN', meaningVi: 'bạn đời nữ', meaningEn: 'female partner', exampleSentence1: 'Meine Partnerin arbeitet hier.', exampleTranslation1: 'Bạn đời của tôi làm việc ở đây.', exampleSentence2: 'Die Partnerin kommt mit.', exampleTranslation2: 'Bạn đời nữ đi cùng.' },
    { word: 'Hochzeit', article: 'FEMININ', plural: 'die Hochzeiten', wordType: 'NOMEN', meaningVi: 'đám cưới', meaningEn: 'wedding', exampleSentence1: 'Die Hochzeit ist im Juni.', exampleTranslation1: 'Đám cưới vào tháng 6.', exampleSentence2: 'Wir feiern Hochzeit.', exampleTranslation2: 'Chúng tôi tổ chức đám cưới.' },
    { word: 'Ehe', article: 'FEMININ', plural: 'die Ehen', wordType: 'NOMEN', meaningVi: 'hôn nhân', meaningEn: 'marriage', exampleSentence1: 'Sie führen eine glückliche Ehe.', exampleTranslation1: 'Họ có hôn nhân hạnh phúc.', exampleSentence2: 'Die Ehe dauert 20 Jahre.', exampleTranslation2: 'Hôn nhân kéo dài 20 năm.' },
    { word: 'Scheidung', article: 'FEMININ', plural: 'die Scheidungen', wordType: 'NOMEN', meaningVi: 'ly hôn', meaningEn: 'divorce', exampleSentence1: 'Die Scheidung war schwer.', exampleTranslation1: 'Việc ly hôn khó khăn.', exampleSentence2: 'Sie wollen die Scheidung.', exampleTranslation2: 'Họ muốn ly hôn.' },
    { word: 'Nachbar', article: 'MASKULIN', plural: 'die Nachbarn', wordType: 'NOMEN', meaningVi: 'hàng xóm', meaningEn: 'neighbor', exampleSentence1: 'Mein Nachbar ist nett.', exampleTranslation1: 'Hàng xóm tôi tốt bụng.', exampleSentence2: 'Die Nachbarn feiern.', exampleTranslation2: 'Hàng xóm ăn mừng.' },
    { word: 'Verwandte', article: 'MASKULIN', plural: 'die Verwandten', wordType: 'NOMEN', meaningVi: 'họ hàng', meaningEn: 'relative', exampleSentence1: 'Wir besuchen Verwandte.', exampleTranslation1: 'Chúng tôi thăm họ hàng.', exampleSentence2: 'Viele Verwandte kommen.', exampleTranslation2: 'Nhiều họ hàng đến.' },
    { word: 'Jugendliche', article: 'MASKULIN', plural: 'die Jugendlichen', wordType: 'NOMEN', meaningVi: 'thanh thiếu niên', meaningEn: 'teenager, youth', exampleSentence1: 'Die Jugendlichen spielen Fußball.', exampleTranslation1: 'Thanh thiếu niên chơi bóng đá.', exampleSentence2: 'Jugendliche brauchen Freiheit.', exampleTranslation2: 'Thanh thiếu niên cần tự do.' },
    { word: 'Erwachsene', article: 'MASKULIN', plural: 'die Erwachsenen', wordType: 'NOMEN', meaningVi: 'người lớn', meaningEn: 'adult', exampleSentence1: 'Nur für Erwachsene.', exampleTranslation1: 'Chỉ dành cho người lớn.', exampleSentence2: 'Erwachsene bezahlen mehr.', exampleTranslation2: 'Người lớn trả nhiều hơn.' },
    { word: 'Rentner', article: 'MASKULIN', plural: 'die Rentner', wordType: 'NOMEN', meaningVi: 'người nghỉ hưu', meaningEn: 'retiree', exampleSentence1: 'Er ist Rentner.', exampleTranslation1: 'Ông ấy đã nghỉ hưu.', exampleSentence2: 'Rentner haben viel Freizeit.', exampleTranslation2: 'Người nghỉ hưu có nhiều thời gian rảnh.' },
    { word: 'heiraten', wordType: 'VERB', meaningVi: 'kết hôn', meaningEn: 'to marry', conjugation: { praesens: { ich: 'heirate', du: 'heiratest', er_sie_es: 'heiratet', wir: 'heiraten', ihr: 'heiratet', sie_Sie: 'heiraten' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Wir heiraten nächstes Jahr.', exampleTranslation1: 'Chúng tôi kết hôn năm sau.', exampleSentence2: 'Sie hat geheiratet.', exampleTranslation2: 'Cô ấy đã kết hôn.' },
    { word: 'sich trennen', wordType: 'VERB', meaningVi: 'chia tay', meaningEn: 'to separate', conjugation: { praesens: { ich: 'trenne mich', du: 'trennst dich', er_sie_es: 'trennt sich', wir: 'trennen uns', ihr: 'trennt euch', sie_Sie: 'trennen sich' }, isIrregular: false, isSeparable: true }, exampleSentence1: 'Sie haben sich getrennt.', exampleTranslation1: 'Họ đã chia tay.', exampleSentence2: 'Wir trennen uns.', exampleTranslation2: 'Chúng tôi chia tay.' },
    { word: 'erziehen', wordType: 'VERB', meaningVi: 'nuôi dạy', meaningEn: 'to raise, educate', conjugation: { praesens: { ich: 'erziehe', du: 'erziehst', er_sie_es: 'erzieht', wir: 'erziehen', ihr: 'erzieht', sie_Sie: 'erziehen' }, isIrregular: true, isSeparable: false }, exampleSentence1: 'Sie erzieht drei Kinder.', exampleTranslation1: 'Cô ấy nuôi 3 con.', exampleSentence2: 'Kinder gut erziehen.', exampleTranslation2: 'Nuôi dạy con tốt.' },
    { word: 'sich kümmern', wordType: 'VERB', meaningVi: 'chăm sóc, lo lắng', meaningEn: 'to take care of', conjugation: { praesens: { ich: 'kümmere mich', du: 'kümmerst dich', er_sie_es: 'kümmert sich', wir: 'kümmern uns', ihr: 'kümmert euch', sie_Sie: 'kümmern sich' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Ich kümmere mich um die Kinder.', exampleTranslation1: 'Tôi chăm sóc bọn trẻ.', exampleSentence2: 'Wer kümmert sich darum?', exampleTranslation2: 'Ai lo việc đó?' },
    { word: 'Geburt', article: 'FEMININ', plural: 'die Geburten', wordType: 'NOMEN', meaningVi: 'sự sinh, sự ra đời', meaningEn: 'birth', exampleSentence1: 'Die Geburt war gut.', exampleTranslation1: 'Ca sinh tốt.', exampleSentence2: 'Seit meiner Geburt.', exampleTranslation2: 'Kể từ khi tôi sinh ra.' },
    { word: 'Tod', article: 'MASKULIN', plural: 'die Tode', wordType: 'NOMEN', meaningVi: 'cái chết', meaningEn: 'death', exampleSentence1: 'Der Tod kam plötzlich.', exampleTranslation1: 'Cái chết đến bất ngờ.', exampleSentence2: 'Nach dem Tod seines Vaters.', exampleTranslation2: 'Sau cái chết của cha anh ấy.' },
    { word: 'Streit', article: 'MASKULIN', plural: 'die Streite', wordType: 'NOMEN', meaningVi: 'cuộc cãi vã', meaningEn: 'argument, quarrel', exampleSentence1: 'Sie hatten einen Streit.', exampleTranslation1: 'Họ đã cãi nhau.', exampleSentence2: 'Der Streit ist vorbei.', exampleTranslation2: 'Cuộc cãi vã đã qua.' },
    { word: 'sich streiten', wordType: 'VERB', meaningVi: 'cãi nhau', meaningEn: 'to argue, quarrel', conjugation: { praesens: { ich: 'streite mich', du: 'streitest dich', er_sie_es: 'streitet sich', wir: 'streiten uns', ihr: 'streitet euch', sie_Sie: 'streiten sich' }, isIrregular: true, isSeparable: false }, exampleSentence1: 'Sie streiten sich immer.', exampleTranslation1: 'Họ luôn cãi nhau.', exampleSentence2: 'Streitet euch nicht!', exampleTranslation2: 'Đừng cãi nhau!' },
    { word: 'sich versöhnen', wordType: 'VERB', meaningVi: 'làm hòa', meaningEn: 'to reconcile', conjugation: { praesens: { ich: 'versöhne mich', du: 'versöhnst dich', er_sie_es: 'versöhnt sich', wir: 'versöhnen uns', ihr: 'versöhnt euch', sie_Sie: 'versöhnen sich' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Sie haben sich versöhnt.', exampleTranslation1: 'Họ đã làm hòa.', exampleSentence2: 'Versöhnt euch!', exampleTranslation2: 'Hãy làm hòa!' },
    { word: 'ledig', wordType: 'ADJEKTIV', meaningVi: 'độc thân', meaningEn: 'single, unmarried', exampleSentence1: 'Sind Sie ledig?', exampleTranslation1: 'Bạn độc thân?', exampleSentence2: 'Er ist noch ledig.', exampleTranslation2: 'Anh ấy vẫn độc thân.' },
    { word: 'verheiratet', wordType: 'ADJEKTIV', meaningVi: 'đã kết hôn', meaningEn: 'married', exampleSentence1: 'Sie ist verheiratet.', exampleTranslation1: 'Cô ấy đã kết hôn.', exampleSentence2: 'Seit wann bist du verheiratet?', exampleTranslation2: 'Bạn kết hôn từ khi nào?' },
    { word: 'geschieden', wordType: 'ADJEKTIV', meaningVi: 'đã ly hôn', meaningEn: 'divorced', exampleSentence1: 'Er ist geschieden.', exampleTranslation1: 'Anh ấy đã ly hôn.', exampleSentence2: 'Sie lebt geschieden.', exampleTranslation2: 'Cô ấy sống sau ly hôn.' },
    { word: 'schwanger', wordType: 'ADJEKTIV', meaningVi: 'mang thai', meaningEn: 'pregnant', exampleSentence1: 'Sie ist schwanger.', exampleTranslation1: 'Cô ấy mang thai.', exampleSentence2: 'Im dritten Monat schwanger.', exampleTranslation2: 'Mang thai tháng thứ 3.' },
    { word: 'Einladung', article: 'FEMININ', plural: 'die Einladungen', wordType: 'NOMEN', meaningVi: 'lời mời', meaningEn: 'invitation', exampleSentence1: 'Danke für die Einladung!', exampleTranslation1: 'Cảm ơn vì lời mời!', exampleSentence2: 'Die Einladung kommt per Post.', exampleTranslation2: 'Lời mời gửi qua thư.' },
    { word: 'einladen', wordType: 'VERB', meaningVi: 'mời', meaningEn: 'to invite', conjugation: { praesens: { ich: 'lade ein', du: 'lädst ein', er_sie_es: 'lädt ein', wir: 'laden ein', ihr: 'ladet ein', sie_Sie: 'laden ein' }, isIrregular: true, isSeparable: true }, exampleSentence1: 'Ich lade dich zum Essen ein.', exampleTranslation1: 'Tôi mời bạn ăn.', exampleSentence2: 'Wir laden Gäste ein.', exampleTranslation2: 'Chúng tôi mời khách.' },
    { word: 'Feier', article: 'FEMININ', plural: 'die Feiern', wordType: 'NOMEN', meaningVi: 'buổi tiệc, lễ kỷ niệm', meaningEn: 'celebration, party', exampleSentence1: 'Die Feier war schön.', exampleTranslation1: 'Buổi tiệc rất đẹp.', exampleSentence2: 'Wir planen eine Feier.', exampleTranslation2: 'Chúng tôi lên kế hoạch tiệc.' },
    { word: 'feiern', wordType: 'VERB', meaningVi: 'ăn mừng', meaningEn: 'to celebrate', conjugation: { praesens: { ich: 'feiere', du: 'feierst', er_sie_es: 'feiert', wir: 'feiern', ihr: 'feiert', sie_Sie: 'feiern' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Wir feiern Geburtstag.', exampleTranslation1: 'Chúng tôi mừng sinh nhật.', exampleSentence2: 'Lasst uns feiern!', exampleTranslation2: 'Hãy ăn mừng!' },
    { word: 'Geschenk', article: 'NEUTRUM', plural: 'die Geschenke', wordType: 'NOMEN', meaningVi: 'quà tặng', meaningEn: 'gift, present', exampleSentence1: 'Das ist ein schönes Geschenk.', exampleTranslation1: 'Đây là món quà đẹp.', exampleSentence2: 'Ich brauche ein Geschenk.', exampleTranslation2: 'Tôi cần mua quà.' },
    { word: 'schenken', wordType: 'VERB', meaningVi: 'tặng', meaningEn: 'to give (a gift)', conjugation: { praesens: { ich: 'schenke', du: 'schenkst', er_sie_es: 'schenkt', wir: 'schenken', ihr: 'schenkt', sie_Sie: 'schenken' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Was soll ich ihr schenken?', exampleTranslation1: 'Tôi nên tặng gì cho cô ấy?', exampleSentence2: 'Er schenkt Blumen.', exampleTranslation2: 'Anh ấy tặng hoa.' },
    { word: 'gratulieren', wordType: 'VERB', meaningVi: 'chúc mừng', meaningEn: 'to congratulate', conjugation: { praesens: { ich: 'gratuliere', du: 'gratulierst', er_sie_es: 'gratuliert', wir: 'gratulieren', ihr: 'gratuliert', sie_Sie: 'gratulieren' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Herzlichen Glückwunsch! Ich gratuliere!', exampleTranslation1: 'Chúc mừng! Tôi xin chúc mừng!', exampleSentence2: 'Wir gratulieren zum Geburtstag.', exampleTranslation2: 'Chúng tôi chúc mừng sinh nhật.' },
    { word: 'Vertrauen', article: 'NEUTRUM', plural: '-', wordType: 'NOMEN', meaningVi: 'sự tin tưởng', meaningEn: 'trust', exampleSentence1: 'Vertrauen ist wichtig.', exampleTranslation1: 'Tin tưởng rất quan trọng.', exampleSentence2: 'Ich habe Vertrauen in dich.', exampleTranslation2: 'Tôi tin tưởng bạn.' },
    { word: 'vertrauen', wordType: 'VERB', meaningVi: 'tin tưởng', meaningEn: 'to trust', conjugation: { praesens: { ich: 'vertraue', du: 'vertraust', er_sie_es: 'vertraut', wir: 'vertrauen', ihr: 'vertraut', sie_Sie: 'vertrauen' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Ich vertraue dir.', exampleTranslation1: 'Tôi tin tưởng bạn.', exampleSentence2: 'Vertrau mir!', exampleTranslation2: 'Tin tôi đi!' },
    { word: 'Zusammenleben', article: 'NEUTRUM', plural: '-', wordType: 'NOMEN', meaningVi: 'cuộc sống chung', meaningEn: 'cohabitation, living together', exampleSentence1: 'Das Zusammenleben ist nicht einfach.', exampleTranslation1: 'Cuộc sống chung không dễ.', exampleSentence2: 'Regeln für das Zusammenleben.', exampleTranslation2: 'Quy tắc sống chung.' },
])

// 03 — Gesundheit & Körperpflege
total += w('03-gesundheit-koerperpflege.json', { slug: 'a2-gesundheit-koerperpflege', name: 'Gesundheit & Körperpflege', nameVi: 'Sức khỏe & Vệ sinh', nameEn: 'Health & Hygiene', sortOrder: 3 }, [
    { word: 'Krankheit', article: 'FEMININ', plural: 'die Krankheiten', wordType: 'NOMEN', meaningVi: 'bệnh tật', meaningEn: 'illness, disease', exampleSentence1: 'Es ist eine schwere Krankheit.', exampleTranslation1: 'Đây là bệnh nặng.', exampleSentence2: 'Die Krankheit dauert lange.', exampleTranslation2: 'Bệnh kéo dài.' },
    { word: 'Unfall', article: 'MASKULIN', plural: 'die Unfälle', wordType: 'NOMEN', meaningVi: 'tai nạn', meaningEn: 'accident', exampleSentence1: 'Er hatte einen Unfall.', exampleTranslation1: 'Anh ấy bị tai nạn.', exampleSentence2: 'Der Unfall war schlimm.', exampleTranslation2: 'Tai nạn rất nghiêm trọng.' },
    { word: 'Verletzung', article: 'FEMININ', plural: 'die Verletzungen', wordType: 'NOMEN', meaningVi: 'chấn thương', meaningEn: 'injury', exampleSentence1: 'Die Verletzung ist nicht schlimm.', exampleTranslation1: 'Chấn thương không nặng.', exampleSentence2: 'Er hat eine Verletzung am Bein.', exampleTranslation2: 'Anh ấy bị thương ở chân.' },
    { word: 'Allergie', article: 'FEMININ', plural: 'die Allergien', wordType: 'NOMEN', meaningVi: 'dị ứng', meaningEn: 'allergy', exampleSentence1: 'Ich habe eine Allergie gegen Nüsse.', exampleTranslation1: 'Tôi bị dị ứng hạt.', exampleSentence2: 'Die Allergie ist stark.', exampleTranslation2: 'Dị ứng nặng.' },
    { word: 'Versicherung', article: 'FEMININ', plural: 'die Versicherungen', wordType: 'NOMEN', meaningVi: 'bảo hiểm', meaningEn: 'insurance', exampleSentence1: 'Haben Sie eine Versicherung?', exampleTranslation1: 'Bạn có bảo hiểm không?', exampleSentence2: 'Die Versicherung bezahlt alles.', exampleTranslation2: 'Bảo hiểm chi trả hết.' },
    { word: 'Rezept', article: 'NEUTRUM', plural: 'die Rezepte', wordType: 'NOMEN', meaningVi: 'đơn thuốc, công thức', meaningEn: 'prescription, recipe', exampleSentence1: 'Der Arzt schreibt ein Rezept.', exampleTranslation1: 'Bác sĩ kê đơn thuốc.', exampleSentence2: 'Ich brauche ein Rezept.', exampleTranslation2: 'Tôi cần đơn thuốc.' },
    { word: 'Sprechstunde', article: 'FEMININ', plural: 'die Sprechstunden', wordType: 'NOMEN', meaningVi: 'giờ khám bệnh', meaningEn: 'consultation hours', exampleSentence1: 'Die Sprechstunde ist von 8 bis 12.', exampleTranslation1: 'Giờ khám từ 8 đến 12.', exampleSentence2: 'Kommen Sie in die Sprechstunde.', exampleTranslation2: 'Hãy đến giờ khám.' },
    { word: 'Behandlung', article: 'FEMININ', plural: 'die Behandlungen', wordType: 'NOMEN', meaningVi: 'điều trị', meaningEn: 'treatment', exampleSentence1: 'Die Behandlung dauert 2 Wochen.', exampleTranslation1: 'Điều trị kéo dài 2 tuần.', exampleSentence2: 'Die Behandlung war erfolgreich.', exampleTranslation2: 'Điều trị thành công.' },
    { word: 'Untersuchung', article: 'FEMININ', plural: 'die Untersuchungen', wordType: 'NOMEN', meaningVi: 'kiểm tra, xét nghiệm', meaningEn: 'examination', exampleSentence1: 'Die Untersuchung dauert 30 Minuten.', exampleTranslation1: 'Kiểm tra mất 30 phút.', exampleSentence2: 'Er braucht eine Untersuchung.', exampleTranslation2: 'Anh ấy cần xét nghiệm.' },
    { word: 'Impfung', article: 'FEMININ', plural: 'die Impfungen', wordType: 'NOMEN', meaningVi: 'tiêm chủng', meaningEn: 'vaccination', exampleSentence1: 'Die Impfung ist wichtig.', exampleTranslation1: 'Tiêm chủng rất quan trọng.', exampleSentence2: 'Haben Sie alle Impfungen?', exampleTranslation2: 'Bạn đã tiêm đủ chưa?' },
    { word: 'Notfall', article: 'MASKULIN', plural: 'die Notfälle', wordType: 'NOMEN', meaningVi: 'trường hợp khẩn cấp', meaningEn: 'emergency', exampleSentence1: 'Das ist ein Notfall!', exampleTranslation1: 'Đây là trường hợp khẩn cấp!', exampleSentence2: 'Rufen Sie im Notfall 112 an.', exampleTranslation2: 'Khi khẩn cấp gọi 112.' },
    { word: 'Krankenwagen', article: 'MASKULIN', plural: 'die Krankenwagen', wordType: 'NOMEN', meaningVi: 'xe cứu thương', meaningEn: 'ambulance', exampleSentence1: 'Der Krankenwagen kommt sofort.', exampleTranslation1: 'Xe cứu thương đến ngay.', exampleSentence2: 'Rufen Sie den Krankenwagen!', exampleTranslation2: 'Gọi xe cứu thương!' },
    { word: 'sich erkälten', wordType: 'VERB', meaningVi: 'bị cảm', meaningEn: 'to catch a cold', conjugation: { praesens: { ich: 'erkälte mich', du: 'erkältest dich', er_sie_es: 'erkältet sich', wir: 'erkälten uns', ihr: 'erkältet euch', sie_Sie: 'erkälten sich' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Ich habe mich erkältet.', exampleTranslation1: 'Tôi bị cảm.', exampleSentence2: 'Erkälte dich nicht!', exampleTranslation2: 'Đừng bị cảm!' },
    { word: 'sich fühlen', wordType: 'VERB', meaningVi: 'cảm thấy', meaningEn: 'to feel', conjugation: { praesens: { ich: 'fühle mich', du: 'fühlst dich', er_sie_es: 'fühlt sich', wir: 'fühlen uns', ihr: 'fühlt euch', sie_Sie: 'fühlen sich' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Ich fühle mich krank.', exampleTranslation1: 'Tôi cảm thấy bệnh.', exampleSentence2: 'Wie fühlen Sie sich?', exampleTranslation2: 'Bạn cảm thấy thế nào?' },
    { word: 'untersuchen', wordType: 'VERB', meaningVi: 'kiểm tra, khám', meaningEn: 'to examine', conjugation: { praesens: { ich: 'untersuche', du: 'untersuchst', er_sie_es: 'untersucht', wir: 'untersuchen', ihr: 'untersucht', sie_Sie: 'untersuchen' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Der Arzt untersucht mich.', exampleTranslation1: 'Bác sĩ khám cho tôi.', exampleSentence2: 'Wir müssen das untersuchen.', exampleTranslation2: 'Chúng tôi phải kiểm tra điều đó.' },
    { word: 'operieren', wordType: 'VERB', meaningVi: 'phẫu thuật', meaningEn: 'to operate', conjugation: { praesens: { ich: 'operiere', du: 'operierst', er_sie_es: 'operiert', wir: 'operieren', ihr: 'operiert', sie_Sie: 'operieren' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Der Arzt muss operieren.', exampleTranslation1: 'Bác sĩ phải phẫu thuật.', exampleSentence2: 'Er wurde am Knie operiert.', exampleTranslation2: 'Anh ấy được phẫu thuật đầu gối.' },
    { word: 'bluten', wordType: 'VERB', meaningVi: 'chảy máu', meaningEn: 'to bleed', conjugation: { praesens: { ich: 'blute', du: 'blutest', er_sie_es: 'blutet', wir: 'bluten', ihr: 'blutet', sie_Sie: 'bluten' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Die Wunde blutet.', exampleTranslation1: 'Vết thương chảy máu.', exampleSentence2: 'Mein Finger blutet.', exampleTranslation2: 'Ngón tay tôi chảy máu.' },
    { word: 'heilen', wordType: 'VERB', meaningVi: 'chữa lành', meaningEn: 'to heal, cure', conjugation: { praesens: { ich: 'heile', du: 'heilst', er_sie_es: 'heilt', wir: 'heilen', ihr: 'heilt', sie_Sie: 'heilen' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Die Wunde heilt gut.', exampleTranslation1: 'Vết thương lành tốt.', exampleSentence2: 'Die Medizin heilt die Krankheit.', exampleTranslation2: 'Thuốc chữa bệnh.' },
    { word: 'Zahnbürste', article: 'FEMININ', plural: 'die Zahnbürsten', wordType: 'NOMEN', meaningVi: 'bàn chải đánh răng', meaningEn: 'toothbrush', exampleSentence1: 'Ich brauche eine neue Zahnbürste.', exampleTranslation1: 'Tôi cần bàn chải mới.', exampleSentence2: 'Die Zahnbürste ist im Bad.', exampleTranslation2: 'Bàn chải ở phòng tắm.' },
    { word: 'Zahnpasta', article: 'FEMININ', plural: 'die Zahnpasten', wordType: 'NOMEN', meaningVi: 'kem đánh răng', meaningEn: 'toothpaste', exampleSentence1: 'Wo ist die Zahnpasta?', exampleTranslation1: 'Kem đánh răng ở đâu?', exampleSentence2: 'Kaufe bitte Zahnpasta.', exampleTranslation2: 'Mua giúp kem đánh răng.' },
    { word: 'Seife', article: 'FEMININ', plural: 'die Seifen', wordType: 'NOMEN', meaningVi: 'xà phòng', meaningEn: 'soap', exampleSentence1: 'Bitte waschen Sie sich mit Seife.', exampleTranslation1: 'Hãy rửa tay bằng xà phòng.', exampleSentence2: 'Die Seife riecht gut.', exampleTranslation2: 'Xà phòng thơm.' },
    { word: 'Handtuch', article: 'NEUTRUM', plural: 'die Handtücher', wordType: 'NOMEN', meaningVi: 'khăn tắm', meaningEn: 'towel', exampleSentence1: 'Das Handtuch ist nass.', exampleTranslation1: 'Khăn tắm ướt.', exampleSentence2: 'Wo sind die Handtücher?', exampleTranslation2: 'Khăn tắm ở đâu?' },
    { word: 'Pflaster', article: 'NEUTRUM', plural: 'die Pflaster', wordType: 'NOMEN', meaningVi: 'băng dán', meaningEn: 'bandage, plaster', exampleSentence1: 'Ich brauche ein Pflaster.', exampleTranslation1: 'Tôi cần băng dán.', exampleSentence2: 'Hast du ein Pflaster?', exampleTranslation2: 'Bạn có băng dán không?' },
    { word: 'Salbe', article: 'FEMININ', plural: 'die Salben', wordType: 'NOMEN', meaningVi: 'thuốc mỡ', meaningEn: 'ointment', exampleSentence1: 'Die Salbe hilft gegen Schmerzen.', exampleTranslation1: 'Thuốc mỡ giảm đau.', exampleSentence2: 'Tragen Sie die Salbe auf.', exampleTranslation2: 'Bôi thuốc mỡ lên.' },
    { word: 'Tablette', article: 'FEMININ', plural: 'die Tabletten', wordType: 'NOMEN', meaningVi: 'viên thuốc', meaningEn: 'tablet, pill', exampleSentence1: 'Nehmen Sie drei Tabletten pro Tag.', exampleTranslation1: 'Uống 3 viên thuốc mỗi ngày.', exampleSentence2: 'Die Tabletten helfen gegen Kopfschmerzen.', exampleTranslation2: 'Viên thuốc trị đau đầu.' },
    { word: 'Tropfen', article: 'MASKULIN', plural: 'die Tropfen', wordType: 'NOMEN', meaningVi: 'giọt thuốc', meaningEn: 'drops', exampleSentence1: 'Nehmen Sie 10 Tropfen.', exampleTranslation1: 'Uống 10 giọt.', exampleSentence2: 'Augentropfen gegen Allergie.', exampleTranslation2: 'Thuốc nhỏ mắt trị dị ứng.' },
    { word: 'Verband', article: 'MASKULIN', plural: 'die Verbände', wordType: 'NOMEN', meaningVi: 'băng bó', meaningEn: 'bandage', exampleSentence1: 'Der Verband muss gewechselt werden.', exampleTranslation1: 'Băng bó phải được thay.', exampleSentence2: 'Legen Sie einen Verband an.', exampleTranslation2: 'Hãy băng bó.' },
    { word: 'Symptom', article: 'NEUTRUM', plural: 'die Symptome', wordType: 'NOMEN', meaningVi: 'triệu chứng', meaningEn: 'symptom', exampleSentence1: 'Welche Symptome haben Sie?', exampleTranslation1: 'Bạn có triệu chứng gì?', exampleSentence2: 'Das sind typische Symptome.', exampleTranslation2: 'Đây là triệu chứng điển hình.' },
    { word: 'Diagnose', article: 'FEMININ', plural: 'die Diagnosen', wordType: 'NOMEN', meaningVi: 'chẩn đoán', meaningEn: 'diagnosis', exampleSentence1: 'Die Diagnose ist sicher.', exampleTranslation1: 'Chẩn đoán chắc chắn.', exampleSentence2: 'Der Arzt stellt die Diagnose.', exampleTranslation2: 'Bác sĩ đưa ra chẩn đoán.' },
    { word: 'gesund', wordType: 'ADJEKTIV', meaningVi: 'khỏe mạnh', meaningEn: 'healthy', exampleSentence1: 'Bleiben Sie gesund!', exampleTranslation1: 'Hãy giữ gìn sức khỏe!', exampleSentence2: 'Obst ist gesund.', exampleTranslation2: 'Hoa quả tốt cho sức khỏe.' },
    { word: 'krank', wordType: 'ADJEKTIV', meaningVi: 'ốm, bệnh', meaningEn: 'sick, ill', exampleSentence1: 'Er ist krank.', exampleTranslation1: 'Anh ấy bị ốm.', exampleSentence2: 'Ich war letzte Woche krank.', exampleTranslation2: 'Tuần trước tôi bị ốm.' },
    { word: 'Grippe', article: 'FEMININ', plural: 'die Grippen', wordType: 'NOMEN', meaningVi: 'cúm', meaningEn: 'flu, influenza', exampleSentence1: 'Er hat die Grippe.', exampleTranslation1: 'Anh ấy bị cúm.', exampleSentence2: 'Die Grippe dauert eine Woche.', exampleTranslation2: 'Cúm kéo dài một tuần.' },
    { word: 'Fieber', article: 'NEUTRUM', plural: '-', wordType: 'NOMEN', meaningVi: 'sốt', meaningEn: 'fever', exampleSentence1: 'Das Kind hat Fieber.', exampleTranslation1: 'Đứa trẻ bị sốt.', exampleSentence2: 'Das Fieber ist hoch.', exampleTranslation2: 'Sốt cao.' },
    { word: 'Husten', article: 'MASKULIN', plural: '-', wordType: 'NOMEN', meaningVi: 'ho', meaningEn: 'cough', exampleSentence1: 'Er hat starken Husten.', exampleTranslation1: 'Anh ấy ho nặng.', exampleSentence2: 'Der Husten geht nicht weg.', exampleTranslation2: 'Ho không hết.' },
    { word: 'Schnupfen', article: 'MASKULIN', plural: '-', wordType: 'NOMEN', meaningVi: 'sổ mũi', meaningEn: 'runny nose, cold', exampleSentence1: 'Ich habe Schnupfen.', exampleTranslation1: 'Tôi bị sổ mũi.', exampleSentence2: 'Schnupfen im Winter ist normal.', exampleTranslation2: 'Sổ mũi mùa đông bình thường.' },
])

console.log(`\n📊 Batch 2 total: ${total} words (themes 02-03)`)
