/**
 * A2 Vocabulary — Themes 18–20 (final batch)
 */
import { writeFileSync } from 'fs'
import path from 'path'
const D = 'content/a2/vocabulary'
function w(f: string, t: any, ws: any[]) { writeFileSync(path.join(D, f), JSON.stringify({ theme: t, words: ws }, null, 4) + '\n'); console.log(`  ✅ ${f}: ${ws.length} words — ${t.name}`); return ws.length }
let total = 0

// 18 — Geld & Finanzen
total += w('18-geld-finanzen.json', { slug: 'a2-geld-finanzen', name: 'Geld & Finanzen', nameVi: 'Tiền & Tài chính', nameEn: 'Money & Finance', sortOrder: 18 }, [
    { word: 'Bargeld', article: 'NEUTRUM', plural: '-', wordType: 'NOMEN', meaningVi: 'tiền mặt', meaningEn: 'cash', exampleSentence1: 'Haben Sie Bargeld?', exampleTranslation1: 'Bạn có tiền mặt không?', exampleSentence2: 'Ich bezahle mit Bargeld.', exampleTranslation2: 'Tôi trả tiền mặt.' },
    { word: 'Kredit', article: 'MASKULIN', plural: 'die Kredite', wordType: 'NOMEN', meaningVi: 'khoản vay', meaningEn: 'credit, loan', exampleSentence1: 'Er hat einen Kredit aufgenommen.', exampleTranslation1: 'Anh ấy đã vay.', exampleSentence2: 'Der Kredit ist teuer.', exampleTranslation2: 'Khoản vay đắt.' },
    { word: 'Schulden', plural: 'die Schulden', wordType: 'NOMEN', meaningVi: 'nợ', meaningEn: 'debts', notes: 'Nur Plural', exampleSentence1: 'Er hat Schulden.', exampleTranslation1: 'Anh ấy nợ.', exampleSentence2: 'Keine Schulden machen.', exampleTranslation2: 'Đừng mắc nợ.' },
    { word: 'sparen', wordType: 'VERB', meaningVi: 'tiết kiệm', meaningEn: 'to save (money)', conjugation: { praesens: { ich: 'spare', du: 'sparst', er_sie_es: 'spart', wir: 'sparen', ihr: 'spart', sie_Sie: 'sparen' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Ich spare für den Urlaub.', exampleTranslation1: 'Tôi tiết kiệm cho kỳ nghỉ.', exampleSentence2: 'Wir müssen Geld sparen.', exampleTranslation2: 'Chúng tôi phải tiết kiệm.' },
    { word: 'ausgeben', wordType: 'VERB', meaningVi: 'tiêu (tiền)', meaningEn: 'to spend (money)', conjugation: { praesens: { ich: 'gebe aus', du: 'gibst aus', er_sie_es: 'gibt aus', wir: 'geben aus', ihr: 'gebt aus', sie_Sie: 'geben aus' }, isIrregular: true, isSeparable: true }, exampleSentence1: 'Ich gebe zu viel Geld aus.', exampleTranslation1: 'Tôi tiêu quá nhiều tiền.', exampleSentence2: 'Wofür gibst du Geld aus?', exampleTranslation2: 'Bạn tiêu tiền vào gì?' },
    { word: 'Preis', article: 'MASKULIN', plural: 'die Preise', wordType: 'NOMEN', meaningVi: 'giá', meaningEn: 'price', exampleSentence1: 'Der Preis ist hoch.', exampleTranslation1: 'Giá cao.', exampleSentence2: 'Was ist der Preis?', exampleTranslation2: 'Giá bao nhiêu?' },
    { word: 'Rechnung', article: 'FEMININ', plural: 'die Rechnungen', wordType: 'NOMEN', meaningVi: 'hóa đơn', meaningEn: 'invoice, bill', exampleSentence1: 'Die Rechnung bezahlen.', exampleTranslation1: 'Thanh toán hóa đơn.', exampleSentence2: 'Die Rechnung ist fällig.', exampleTranslation2: 'Hóa đơn đến hạn.' },
    { word: 'Ermäßigung', article: 'FEMININ', plural: 'die Ermäßigungen', wordType: 'NOMEN', meaningVi: 'giảm giá', meaningEn: 'discount', exampleSentence1: 'Gibt es eine Ermäßigung?', exampleTranslation1: 'Có giảm giá không?', exampleSentence2: '50% Ermäßigung.', exampleTranslation2: 'Giảm 50%.' },
    { word: 'leisten', wordType: 'VERB', meaningVi: 'chi trả được', meaningEn: 'to afford', conjugation: { praesens: { ich: 'leiste', du: 'leistest', er_sie_es: 'leistet', wir: 'leisten', ihr: 'leistet', sie_Sie: 'leisten' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Ich kann mir das nicht leisten.', exampleTranslation1: 'Tôi không đủ điều kiện.', exampleSentence2: 'Das können wir uns leisten.', exampleTranslation2: 'Chúng tôi đủ điều kiện.' },
    { word: 'günstig', wordType: 'ADJEKTIV', meaningVi: 'rẻ, thuận lợi', meaningEn: 'affordable, favorable', exampleSentence1: 'Das ist günstig.', exampleTranslation1: 'Rẻ.', exampleSentence2: 'Ein günstiges Angebot.', exampleTranslation2: 'Ưu đãi hời.' },
    { word: 'teuer', wordType: 'ADJEKTIV', meaningVi: 'đắt', meaningEn: 'expensive', exampleSentence1: 'Das ist zu teuer.', exampleTranslation1: 'Quá đắt.', exampleSentence2: 'Die Miete ist teuer.', exampleTranslation2: 'Tiền thuê nhà đắt.' },
    { word: 'kostenlos', wordType: 'ADJEKTIV', meaningVi: 'miễn phí', meaningEn: 'free (of charge)', exampleSentence1: 'Der Eintritt ist kostenlos.', exampleTranslation1: 'Vào cửa miễn phí.', exampleSentence2: 'Kostenloser Download.', exampleTranslation2: 'Tải miễn phí.' },
    { word: 'gratis', wordType: 'ADJEKTIV', meaningVi: 'miễn phí', meaningEn: 'free, gratis', exampleSentence1: 'Das Frühstück ist gratis.', exampleTranslation1: 'Ăn sáng miễn phí.', exampleSentence2: 'Gratis testen.', exampleTranslation2: 'Dùng thử miễn phí.' },
    { word: 'Steuererklärung', article: 'FEMININ', plural: 'die Steuererklärungen', wordType: 'NOMEN', meaningVi: 'khai thuế', meaningEn: 'tax return', exampleSentence1: 'Ich mache die Steuererklärung.', exampleTranslation1: 'Tôi làm khai thuế.', exampleSentence2: 'Die Frist für die Steuererklärung.', exampleTranslation2: 'Hạn khai thuế.' },
    { word: 'Einkommen', article: 'NEUTRUM', plural: 'die Einkommen', wordType: 'NOMEN', meaningVi: 'thu nhập', meaningEn: 'income', exampleSentence1: 'Das Einkommen ist gut.', exampleTranslation1: 'Thu nhập tốt.', exampleSentence2: 'Hohes Einkommen.', exampleTranslation2: 'Thu nhập cao.' },
])

// 19 — Verkehr & Mobilität
total += w('19-verkehr-mobilitaet.json', { slug: 'a2-verkehr-mobilitaet', name: 'Verkehr & Mobilität', nameVi: 'Giao thông & Di chuyển', nameEn: 'Traffic & Mobility', sortOrder: 19 }, [
    { word: 'Verkehr', article: 'MASKULIN', plural: '-', wordType: 'NOMEN', meaningVi: 'giao thông', meaningEn: 'traffic', exampleSentence1: 'Der Verkehr ist dicht.', exampleTranslation1: 'Giao thông đông đúc.', exampleSentence2: 'Viel Verkehr auf der Autobahn.', exampleTranslation2: 'Đông xe trên cao tốc.' },
    { word: 'Stau', article: 'MASKULIN', plural: 'die Staus', wordType: 'NOMEN', meaningVi: 'kẹt xe', meaningEn: 'traffic jam', exampleSentence1: 'Wir stehen im Stau.', exampleTranslation1: 'Chúng tôi bị kẹt xe.', exampleSentence2: 'Es gibt einen Stau.', exampleTranslation2: 'Bị tắc đường.' },
    { word: 'Führerschein', article: 'MASKULIN', plural: 'die Führerscheine', wordType: 'NOMEN', meaningVi: 'bằng lái xe', meaningEn: 'driver\'s license', exampleSentence1: 'Hast du einen Führerschein?', exampleTranslation1: 'Bạn có bằng lái không?', exampleSentence2: 'Ich mache den Führerschein.', exampleTranslation2: 'Tôi đang thi bằng lái.' },
    { word: 'Tankstelle', article: 'FEMININ', plural: 'die Tankstellen', wordType: 'NOMEN', meaningVi: 'trạm xăng', meaningEn: 'gas station', exampleSentence1: 'Wo ist die nächste Tankstelle?', exampleTranslation1: 'Trạm xăng gần nhất ở đâu?', exampleSentence2: 'Die Tankstelle ist rechts.', exampleTranslation2: 'Trạm xăng bên phải.' },
    { word: 'Parkplatz', article: 'MASKULIN', plural: 'die Parkplätze', wordType: 'NOMEN', meaningVi: 'bãi đậu xe', meaningEn: 'parking lot', exampleSentence1: 'Ich suche einen Parkplatz.', exampleTranslation1: 'Tôi tìm chỗ đậu xe.', exampleSentence2: 'Der Parkplatz ist voll.', exampleTranslation2: 'Bãi đậu xe đầy.' },
    { word: 'Kreuzung', article: 'FEMININ', plural: 'die Kreuzungen', wordType: 'NOMEN', meaningVi: 'ngã tư', meaningEn: 'intersection', exampleSentence1: 'An der Kreuzung links abbiegen.', exampleTranslation1: 'Rẽ trái ở ngã tư.', exampleSentence2: 'Die Kreuzung ist gefährlich.', exampleTranslation2: 'Ngã tư nguy hiểm.' },
    { word: 'Ampel', article: 'FEMININ', plural: 'die Ampeln', wordType: 'NOMEN', meaningVi: 'đèn giao thông', meaningEn: 'traffic light', exampleSentence1: 'Die Ampel ist rot.', exampleTranslation1: 'Đèn đỏ.', exampleSentence2: 'Warten Sie an der Ampel.', exampleTranslation2: 'Đợi ở đèn giao thông.' },
    { word: 'Geschwindigkeit', article: 'FEMININ', plural: 'die Geschwindigkeiten', wordType: 'NOMEN', meaningVi: 'tốc độ', meaningEn: 'speed', exampleSentence1: 'Die Geschwindigkeit ist begrenzt.', exampleTranslation1: 'Tốc độ bị giới hạn.', exampleSentence2: 'Maximale Geschwindigkeit 50 km/h.', exampleTranslation2: 'Tốc độ tối đa 50 km/h.' },
    { word: 'Fahrkarte', article: 'FEMININ', plural: 'die Fahrkarten', wordType: 'NOMEN', meaningVi: 'vé (xe/tàu)', meaningEn: 'ticket (transport)', exampleSentence1: 'Eine Fahrkarte, bitte.', exampleTranslation1: 'Một vé.', exampleSentence2: 'Die Fahrkarte ist gültig.', exampleTranslation2: 'Vé hợp lệ.' },
    { word: 'Monatskarte', article: 'FEMININ', plural: 'die Monatskarten', wordType: 'NOMEN', meaningVi: 'vé tháng', meaningEn: 'monthly pass', exampleSentence1: 'Ich habe eine Monatskarte.', exampleTranslation1: 'Tôi có vé tháng.', exampleSentence2: 'Die Monatskarte kostet 80 Euro.', exampleTranslation2: 'Vé tháng 80 Euro.' },
    { word: 'Haltestelle', article: 'FEMININ', plural: 'die Haltestellen', wordType: 'NOMEN', meaningVi: 'trạm (xe buýt)', meaningEn: 'stop (bus/tram)', exampleSentence1: 'Die Haltestelle ist dort.', exampleTranslation1: 'Trạm xe buýt ở kia.', exampleSentence2: 'Nächste Haltestelle: Marktplatz.', exampleTranslation2: 'Trạm tiếp: Marktplatz.' },
    { word: 'Linie', article: 'FEMININ', plural: 'die Linien', wordType: 'NOMEN', meaningVi: 'tuyến (xe)', meaningEn: 'line (transport)', exampleSentence1: 'Nehmen Sie die Linie 5.', exampleTranslation1: 'Đi tuyến 5.', exampleSentence2: 'Welche Linie fährt zum Bahnhof?', exampleTranslation2: 'Tuyến nào đến ga?' },
    { word: 'abbiegen', wordType: 'VERB', meaningVi: 'rẽ', meaningEn: 'to turn', conjugation: { praesens: { ich: 'biege ab', du: 'biegst ab', er_sie_es: 'biegt ab', wir: 'biegen ab', ihr: 'biegt ab', sie_Sie: 'biegen ab' }, isIrregular: true, isSeparable: true }, exampleSentence1: 'Biegen Sie rechts ab.', exampleTranslation1: 'Rẽ phải.', exampleSentence2: 'Links abbiegen.', exampleTranslation2: 'Rẽ trái.' },
    { word: 'überholen', wordType: 'VERB', meaningVi: 'vượt (xe)', meaningEn: 'to overtake', conjugation: { praesens: { ich: 'überhole', du: 'überholst', er_sie_es: 'überholt', wir: 'überholen', ihr: 'überholt', sie_Sie: 'überholen' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Hier darf man nicht überholen.', exampleTranslation1: 'Ở đây không được vượt.', exampleSentence2: 'Er überholt den LKW.', exampleTranslation2: 'Anh ấy vượt xe tải.' },
    { word: 'parken', wordType: 'VERB', meaningVi: 'đậu xe', meaningEn: 'to park', conjugation: { praesens: { ich: 'parke', du: 'parkst', er_sie_es: 'parkt', wir: 'parken', ihr: 'parkt', sie_Sie: 'parken' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Wo kann ich parken?', exampleTranslation1: 'Đậu xe ở đâu?', exampleSentence2: 'Parken verboten!', exampleTranslation2: 'Cấm đậu xe!' },
    { word: 'Fußgänger', article: 'MASKULIN', plural: 'die Fußgänger', wordType: 'NOMEN', meaningVi: 'người đi bộ', meaningEn: 'pedestrian', exampleSentence1: 'Fußgänger haben Vorrang.', exampleTranslation1: 'Người đi bộ được ưu tiên.', exampleSentence2: 'Die Fußgängerzone.', exampleTranslation2: 'Khu phố đi bộ.' },
    { word: 'Radweg', article: 'MASKULIN', plural: 'die Radwege', wordType: 'NOMEN', meaningVi: 'đường dành cho xe đạp', meaningEn: 'bike path', exampleSentence1: 'Benutzen Sie den Radweg.', exampleTranslation1: 'Đi đường dành cho xe đạp.', exampleSentence2: 'Der Radweg ist neu.', exampleTranslation2: 'Đường xe đạp mới.' },
    { word: 'Autobahn', article: 'FEMININ', plural: 'die Autobahnen', wordType: 'NOMEN', meaningVi: 'đường cao tốc', meaningEn: 'highway, motorway', exampleSentence1: 'Wir fahren auf der Autobahn.', exampleTranslation1: 'Đi trên cao tốc.', exampleSentence2: 'Die Autobahn ist voll.', exampleTranslation2: 'Cao tốc đông.' },
])

// 20 — Wetter & Klima
total += w('20-wetter-klima.json', { slug: 'a2-wetter-klima', name: 'Wetter & Klima', nameVi: 'Thời tiết & Khí hậu', nameEn: 'Weather & Climate', sortOrder: 20 }, [
    { word: 'Wettervorhersage', article: 'FEMININ', plural: 'die Wettervorhersagen', wordType: 'NOMEN', meaningVi: 'dự báo thời tiết', meaningEn: 'weather forecast', exampleSentence1: 'Die Wettervorhersage sagt Regen.', exampleTranslation1: 'Dự báo nói sẽ mưa.', exampleSentence2: 'Hast du die Wettervorhersage gesehen?', exampleTranslation2: 'Bạn xem dự báo chưa?' },
    { word: 'Wetterbericht', article: 'MASKULIN', plural: 'die Wetterberichte', wordType: 'NOMEN', meaningVi: 'bản tin thời tiết', meaningEn: 'weather report', exampleSentence1: 'Laut Wetterbericht wird es warm.', exampleTranslation1: 'Theo bản tin sẽ ấm.', exampleSentence2: 'Der Wetterbericht für morgen.', exampleTranslation2: 'Bản tin thời tiết ngày mai.' },
    { word: 'Sonnenschein', article: 'MASKULIN', plural: '-', wordType: 'NOMEN', meaningVi: 'nắng', meaningEn: 'sunshine', exampleSentence1: 'Heute gibt es Sonnenschein.', exampleTranslation1: 'Hôm nay có nắng.', exampleSentence2: 'Endlich Sonnenschein!', exampleTranslation2: 'Cuối cùng cũng có nắng!' },
    { word: 'Regenschauer', article: 'MASKULIN', plural: 'die Regenschauer', wordType: 'NOMEN', meaningVi: 'mưa rào', meaningEn: 'rain shower', exampleSentence1: 'Es gibt kurze Regenschauer.', exampleTranslation1: 'Có mưa rào ngắn.', exampleSentence2: 'Ein Regenschauer am Nachmittag.', exampleTranslation2: 'Mưa rào chiều.' },
    { word: 'Hagel', article: 'MASKULIN', plural: '-', wordType: 'NOMEN', meaningVi: 'mưa đá', meaningEn: 'hail', exampleSentence1: 'Es gibt Hagel.', exampleTranslation1: 'Có mưa đá.', exampleSentence2: 'Hagel kann Autos beschädigen.', exampleTranslation2: 'Mưa đá có thể hỏng xe.' },
    { word: 'Donner', article: 'MASKULIN', plural: '-', wordType: 'NOMEN', meaningVi: 'sấm', meaningEn: 'thunder', exampleSentence1: 'Ich höre Donner.', exampleTranslation1: 'Tôi nghe sấm.', exampleSentence2: 'Donner und Blitz.', exampleTranslation2: 'Sấm và sét.' },
    { word: 'Blitz', article: 'MASKULIN', plural: 'die Blitze', wordType: 'NOMEN', meaningVi: 'sét, tia chớp', meaningEn: 'lightning', exampleSentence1: 'Der Blitz war nah.', exampleTranslation1: 'Sét đánh gần.', exampleSentence2: 'Vorsicht vor Blitzen!', exampleTranslation2: 'Cẩn thận sét!' },
    { word: 'Regenschirm', article: 'MASKULIN', plural: 'die Regenschirme', wordType: 'NOMEN', meaningVi: 'ô, dù', meaningEn: 'umbrella', exampleSentence1: 'Nimm den Regenschirm mit!', exampleTranslation1: 'Mang ô đi!', exampleSentence2: 'Wo ist mein Regenschirm?', exampleTranslation2: 'Ô tôi đâu?' },
    { word: 'Sonnencreme', article: 'FEMININ', plural: 'die Sonnencremes', wordType: 'NOMEN', meaningVi: 'kem chống nắng', meaningEn: 'sunscreen', exampleSentence1: 'Vergiss die Sonnencreme nicht!', exampleTranslation1: 'Đừng quên kem chống nắng!', exampleSentence2: 'Sonnencreme mit Faktor 50.', exampleTranslation2: 'Kem chống nắng SPF 50.' },
    { word: 'Sonnenbrille', article: 'FEMININ', plural: 'die Sonnenbrillen', wordType: 'NOMEN', meaningVi: 'kính râm', meaningEn: 'sunglasses', exampleSentence1: 'Wo ist meine Sonnenbrille?', exampleTranslation1: 'Kính râm tôi đâu?', exampleSentence2: 'Die Sonnenbrille ist modisch.', exampleTranslation2: 'Kính râm thời trang.' },
    { word: 'bewölkt', wordType: 'ADJEKTIV', meaningVi: 'nhiều mây', meaningEn: 'cloudy', exampleSentence1: 'Heute ist es bewölkt.', exampleTranslation1: 'Hôm nay nhiều mây.', exampleSentence2: 'Bewölkt mit etwas Regen.', exampleTranslation2: 'Mây kèm mưa nhỏ.' },
    { word: 'heiter', wordType: 'ADJEKTIV', meaningVi: 'quang đãng', meaningEn: 'clear, bright', exampleSentence1: 'Der Himmel ist heiter.', exampleTranslation1: 'Trời quang đãng.', exampleSentence2: 'Heiter bis wolkig.', exampleTranslation2: 'Quang đãng đến mây.' },
    { word: 'windig', wordType: 'ADJEKTIV', meaningVi: 'có gió', meaningEn: 'windy', exampleSentence1: 'Es ist sehr windig.', exampleTranslation1: 'Gió rất mạnh.', exampleSentence2: 'Ein windiger Tag.', exampleTranslation2: 'Ngày nhiều gió.' },
    { word: 'sonnig', wordType: 'ADJEKTIV', meaningVi: 'có nắng', meaningEn: 'sunny', exampleSentence1: 'Es ist sonnig.', exampleTranslation1: 'Trời nắng.', exampleSentence2: 'Ein sonniger Tag.', exampleTranslation2: 'Ngày nắng.' },
    { word: 'regnerisch', wordType: 'ADJEKTIV', meaningVi: 'mưa nhiều', meaningEn: 'rainy', exampleSentence1: 'Es ist regnerisch.', exampleTranslation1: 'Thời tiết mưa.', exampleSentence2: 'Ein regnerischer Herbst.', exampleTranslation2: 'Mùa thu mưa.' },
    { word: 'stürmisch', wordType: 'ADJEKTIV', meaningVi: 'bão tố', meaningEn: 'stormy', exampleSentence1: 'Das Wetter ist stürmisch.', exampleTranslation1: 'Thời tiết bão tố.', exampleSentence2: 'Ein stürmischer Abend.', exampleTranslation2: 'Buổi tối bão tố.' },
    { word: 'mild', wordType: 'ADJEKTIV', meaningVi: 'ôn hòa', meaningEn: 'mild', exampleSentence1: 'Das Wetter ist mild.', exampleTranslation1: 'Thời tiết ôn hòa.', exampleSentence2: 'Ein milder Winter.', exampleTranslation2: 'Mùa đông ôn hòa.' },
    { word: 'kühl', wordType: 'ADJEKTIV', meaningVi: 'mát mẻ', meaningEn: 'cool', exampleSentence1: 'Es ist kühl draußen.', exampleTranslation1: 'Bên ngoài mát mẻ.', exampleSentence2: 'Kühle Nächte.', exampleTranslation2: 'Đêm mát mẻ.' },
    { word: 'schwül', wordType: 'ADJEKTIV', meaningVi: 'oi bức', meaningEn: 'humid, muggy', exampleSentence1: 'Es ist schwül heute.', exampleTranslation1: 'Hôm nay oi bức.', exampleSentence2: 'Schwüles Sommerwetter.', exampleTranslation2: 'Thời tiết hè oi bức.' },
])

console.log(`\n📊 FINAL Batch total: ${total} words (themes 18-20)`)
