/**
 * A2 Vocabulary — Themes 09–10
 */
import { writeFileSync } from 'fs'
import path from 'path'
const D = 'content/a2/vocabulary'
function w(f: string, t: any, ws: any[]) { writeFileSync(path.join(D, f), JSON.stringify({ theme: t, words: ws }, null, 4) + '\n'); console.log(`  ✅ ${f}: ${ws.length} words — ${t.name}`); return ws.length }
let total = 0

// 09 — Bildung & Berufsleben
total += w('09-bildung-berufsleben.json', { slug: 'a2-bildung-berufsleben', name: 'Bildung & Berufsleben', nameVi: 'Giáo dục & Đời sống nghề nghiệp', nameEn: 'Education & Professional Life', sortOrder: 9 }, [
    { word: 'Ausbildung', article: 'FEMININ', plural: 'die Ausbildungen', wordType: 'NOMEN', meaningVi: 'đào tạo nghề', meaningEn: 'vocational training', exampleSentence1: 'Er macht eine Ausbildung.', exampleTranslation1: 'Anh ấy đang học nghề.', exampleSentence2: 'Die Ausbildung dauert 3 Jahre.', exampleTranslation2: 'Đào tạo nghề kéo dài 3 năm.' },
    { word: 'Studium', article: 'NEUTRUM', plural: 'die Studien', wordType: 'NOMEN', meaningVi: 'việc học đại học', meaningEn: 'studies (university)', exampleSentence1: 'Das Studium ist schwer.', exampleTranslation1: 'Học đại học khó.', exampleSentence2: 'Nach dem Studium.', exampleTranslation2: 'Sau khi tốt nghiệp đại học.' },
    { word: 'studieren', wordType: 'VERB', meaningVi: 'học đại học', meaningEn: 'to study (at university)', conjugation: { praesens: { ich: 'studiere', du: 'studierst', er_sie_es: 'studiert', wir: 'studieren', ihr: 'studiert', sie_Sie: 'studieren' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Ich studiere Medizin.', exampleTranslation1: 'Tôi học y khoa.', exampleSentence2: 'Was studierst du?', exampleTranslation2: 'Bạn học ngành gì?' },
    { word: 'Abschluss', article: 'MASKULIN', plural: 'die Abschlüsse', wordType: 'NOMEN', meaningVi: 'bằng tốt nghiệp', meaningEn: 'degree, diploma', exampleSentence1: 'Er hat einen guten Abschluss.', exampleTranslation1: 'Anh ấy có bằng tốt.', exampleSentence2: 'Welchen Abschluss haben Sie?', exampleTranslation2: 'Bạn có bằng gì?' },
    { word: 'Kenntnisse', plural: 'die Kenntnisse', wordType: 'NOMEN', meaningVi: 'kiến thức', meaningEn: 'knowledge, skills', notes: 'Nur Plural', exampleSentence1: 'Er hat gute Deutschkenntnisse.', exampleTranslation1: 'Anh ấy giỏi tiếng Đức.', exampleSentence2: 'Computer-Kenntnisse sind wichtig.', exampleTranslation2: 'Kiến thức máy tính quan trọng.' },
    { word: 'Qualifikation', article: 'FEMININ', plural: 'die Qualifikationen', wordType: 'NOMEN', meaningVi: 'trình độ chuyên môn', meaningEn: 'qualification', exampleSentence1: 'Welche Qualifikationen haben Sie?', exampleTranslation1: 'Bạn có trình độ gì?', exampleSentence2: 'Die Qualifikation ist notwendig.', exampleTranslation2: 'Trình độ này cần thiết.' },
    { word: 'Bewerbung', article: 'FEMININ', plural: 'die Bewerbungen', wordType: 'NOMEN', meaningVi: 'đơn xin việc', meaningEn: 'job application', exampleSentence1: 'Ich schreibe eine Bewerbung.', exampleTranslation1: 'Tôi viết đơn xin việc.', exampleSentence2: 'Schicken Sie Ihre Bewerbung.', exampleTranslation2: 'Gửi đơn xin việc.' },
    { word: 'sich bewerben', wordType: 'VERB', meaningVi: 'xin việc, ứng tuyển', meaningEn: 'to apply (for a job)', conjugation: { praesens: { ich: 'bewerbe mich', du: 'bewirbst dich', er_sie_es: 'bewirbt sich', wir: 'bewerben uns', ihr: 'bewerbt euch', sie_Sie: 'bewerben sich' }, isIrregular: true, isSeparable: false }, exampleSentence1: 'Ich bewerbe mich um die Stelle.', exampleTranslation1: 'Tôi ứng tuyển vị trí.', exampleSentence2: 'Er hat sich beworben.', exampleTranslation2: 'Anh ấy đã ứng tuyển.' },
    { word: 'Vorstellungsgespräch', article: 'NEUTRUM', plural: 'die Vorstellungsgespräche', wordType: 'NOMEN', meaningVi: 'phỏng vấn xin việc', meaningEn: 'job interview', exampleSentence1: 'Ich habe ein Vorstellungsgespräch.', exampleTranslation1: 'Tôi có buổi phỏng vấn.', exampleSentence2: 'Das Gespräch war gut.', exampleTranslation2: 'Buổi phỏng vấn tốt.' },
    { word: 'Praktikum', article: 'NEUTRUM', plural: 'die Praktika', wordType: 'NOMEN', meaningVi: 'thực tập', meaningEn: 'internship', exampleSentence1: 'Ich mache ein Praktikum.', exampleTranslation1: 'Tôi đang thực tập.', exampleSentence2: 'Das Praktikum dauert 6 Monate.', exampleTranslation2: 'Thực tập kéo dài 6 tháng.' },
    { word: 'Weiterbildung', article: 'FEMININ', plural: 'die Weiterbildungen', wordType: 'NOMEN', meaningVi: 'đào tạo nâng cao', meaningEn: 'further education', exampleSentence1: 'Weiterbildung ist wichtig.', exampleTranslation1: 'Đào tạo nâng cao quan trọng.', exampleSentence2: 'Ich mache eine Weiterbildung.', exampleTranslation2: 'Tôi tham gia đào tạo nâng cao.' },
    { word: 'Seminar', article: 'NEUTRUM', plural: 'die Seminare', wordType: 'NOMEN', meaningVi: 'hội thảo', meaningEn: 'seminar', exampleSentence1: 'Das Seminar war interessant.', exampleTranslation1: 'Hội thảo thú vị.', exampleSentence2: 'Ich besuche ein Seminar.', exampleTranslation2: 'Tôi tham gia hội thảo.' },
    { word: 'Vortrag', article: 'MASKULIN', plural: 'die Vorträge', wordType: 'NOMEN', meaningVi: 'bài thuyết trình', meaningEn: 'lecture, presentation', exampleSentence1: 'Er hält einen Vortrag.', exampleTranslation1: 'Anh ấy thuyết trình.', exampleSentence2: 'Der Vortrag war lang.', exampleTranslation2: 'Bài thuyết trình dài.' },
    { word: 'Teilnehmer', article: 'MASKULIN', plural: 'die Teilnehmer', wordType: 'NOMEN', meaningVi: 'người tham gia', meaningEn: 'participant', exampleSentence1: 'Es gibt 20 Teilnehmer.', exampleTranslation1: 'Có 20 người tham gia.', exampleSentence2: 'Die Teilnehmer sind motiviert.', exampleTranslation2: 'Người tham gia có động lực.' },
    { word: 'teilnehmen', wordType: 'VERB', meaningVi: 'tham gia', meaningEn: 'to participate', conjugation: { praesens: { ich: 'nehme teil', du: 'nimmst teil', er_sie_es: 'nimmt teil', wir: 'nehmen teil', ihr: 'nehmt teil', sie_Sie: 'nehmen teil' }, isIrregular: true, isSeparable: true }, exampleSentence1: 'Ich nehme am Kurs teil.', exampleTranslation1: 'Tôi tham gia khóa học.', exampleSentence2: 'Möchtest du teilnehmen?', exampleTranslation2: 'Bạn muốn tham gia không?' },
    { word: 'bestehen', wordType: 'VERB', meaningVi: 'đậu, vượt qua', meaningEn: 'to pass (an exam)', conjugation: { praesens: { ich: 'bestehe', du: 'bestehst', er_sie_es: 'besteht', wir: 'bestehen', ihr: 'besteht', sie_Sie: 'bestehen' }, isIrregular: true, isSeparable: false }, exampleSentence1: 'Ich habe die Prüfung bestanden.', exampleTranslation1: 'Tôi đã đậu kỳ thi.', exampleSentence2: 'Hast du bestanden?', exampleTranslation2: 'Bạn đậu chưa?' },
    { word: 'durchfallen', wordType: 'VERB', meaningVi: 'trượt, rớt', meaningEn: 'to fail (an exam)', conjugation: { praesens: { ich: 'falle durch', du: 'fällst durch', er_sie_es: 'fällt durch', wir: 'fallen durch', ihr: 'fallt durch', sie_Sie: 'fallen durch' }, isIrregular: true, isSeparable: true }, exampleSentence1: 'Er ist durchgefallen.', exampleTranslation1: 'Anh ấy trượt.', exampleSentence2: 'Ich will nicht durchfallen.', exampleTranslation2: 'Tôi không muốn trượt.' },
    { word: 'Nachhilfe', article: 'FEMININ', plural: '-', wordType: 'NOMEN', meaningVi: 'dạy kèm', meaningEn: 'tutoring', exampleSentence1: 'Ich brauche Nachhilfe.', exampleTranslation1: 'Tôi cần dạy kèm.', exampleSentence2: 'Sie gibt Nachhilfe in Mathe.', exampleTranslation2: 'Cô ấy dạy kèm toán.' },
    { word: 'Stipendium', article: 'NEUTRUM', plural: 'die Stipendien', wordType: 'NOMEN', meaningVi: 'học bổng', meaningEn: 'scholarship', exampleSentence1: 'Er hat ein Stipendium.', exampleTranslation1: 'Anh ấy có học bổng.', exampleSentence2: 'Ich bewerbe mich um ein Stipendium.', exampleTranslation2: 'Tôi xin học bổng.' },
    { word: 'Fach', article: 'NEUTRUM', plural: 'die Fächer', wordType: 'NOMEN', meaningVi: 'môn học', meaningEn: 'subject', exampleSentence1: 'Was ist dein Lieblingsfach?', exampleTranslation1: 'Môn học yêu thích của bạn?', exampleSentence2: 'Mathe ist ein schweres Fach.', exampleTranslation2: 'Toán là môn khó.' },
])

// 10 — Arbeit & Wirtschaft
total += w('10-arbeit-wirtschaft.json', { slug: 'a2-arbeit-wirtschaft', name: 'Arbeit & Wirtschaft', nameVi: 'Công việc & Kinh tế', nameEn: 'Work & Economy', sortOrder: 10 }, [
    { word: 'Gehalt', article: 'NEUTRUM', plural: 'die Gehälter', wordType: 'NOMEN', meaningVi: 'lương', meaningEn: 'salary', exampleSentence1: 'Das Gehalt ist gut.', exampleTranslation1: 'Lương tốt.', exampleSentence2: 'Wie hoch ist das Gehalt?', exampleTranslation2: 'Lương bao nhiêu?' },
    { word: 'Lohn', article: 'MASKULIN', plural: 'die Löhne', wordType: 'NOMEN', meaningVi: 'tiền công', meaningEn: 'wage', exampleSentence1: 'Der Lohn ist fair.', exampleTranslation1: 'Tiền công công bằng.', exampleSentence2: 'Mindestlohn in Deutschland.', exampleTranslation2: 'Lương tối thiểu ở Đức.' },
    { word: 'Vertrag', article: 'MASKULIN', plural: 'die Verträge', wordType: 'NOMEN', meaningVi: 'hợp đồng', meaningEn: 'contract', exampleSentence1: 'Der Vertrag ist unterschrieben.', exampleTranslation1: 'Hợp đồng đã ký.', exampleSentence2: 'Lesen Sie den Vertrag.', exampleTranslation2: 'Đọc hợp đồng.' },
    { word: 'Kündigung', article: 'FEMININ', plural: 'die Kündigungen', wordType: 'NOMEN', meaningVi: 'thông báo nghỉ việc', meaningEn: 'notice, termination', exampleSentence1: 'Er hat die Kündigung bekommen.', exampleTranslation1: 'Anh ấy nhận thông báo sa thải.', exampleSentence2: 'Die Kündigung war ein Schock.', exampleTranslation2: 'Việc sa thải gây sốc.' },
    { word: 'kündigen', wordType: 'VERB', meaningVi: 'nghỉ việc, sa thải', meaningEn: 'to resign, to terminate', conjugation: { praesens: { ich: 'kündige', du: 'kündigst', er_sie_es: 'kündigt', wir: 'kündigen', ihr: 'kündigt', sie_Sie: 'kündigen' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Er hat gekündigt.', exampleTranslation1: 'Anh ấy đã nghỉ việc.', exampleSentence2: 'Die Firma kündigt Mitarbeiter.', exampleTranslation2: 'Công ty sa thải nhân viên.' },
    { word: 'Überstunden', plural: 'die Überstunden', wordType: 'NOMEN', meaningVi: 'giờ làm thêm', meaningEn: 'overtime', notes: 'Nur Plural', exampleSentence1: 'Ich mache Überstunden.', exampleTranslation1: 'Tôi làm thêm giờ.', exampleSentence2: 'Überstunden werden bezahlt.', exampleTranslation2: 'Giờ làm thêm được trả tiền.' },
    { word: 'Urlaub', article: 'MASKULIN', plural: 'die Urlaube', wordType: 'NOMEN', meaningVi: 'kỳ nghỉ phép', meaningEn: 'vacation, leave', exampleSentence1: 'Ich nehme Urlaub.', exampleTranslation1: 'Tôi nghỉ phép.', exampleSentence2: '30 Tage Urlaub im Jahr.', exampleTranslation2: '30 ngày phép mỗi năm.' },
    { word: 'Kollege', article: 'MASKULIN', plural: 'die Kollegen', wordType: 'NOMEN', meaningVi: 'đồng nghiệp nam', meaningEn: 'colleague (male)', exampleSentence1: 'Mein Kollege hilft mir.', exampleTranslation1: 'Đồng nghiệp tôi giúp tôi.', exampleSentence2: 'Die Kollegen sind nett.', exampleTranslation2: 'Đồng nghiệp tốt bụng.' },
    { word: 'Kollegin', article: 'FEMININ', plural: 'die Kolleginnen', wordType: 'NOMEN', meaningVi: 'đồng nghiệp nữ', meaningEn: 'colleague (female)', exampleSentence1: 'Meine Kollegin ist krank.', exampleTranslation1: 'Đồng nghiệp nữ tôi bị ốm.', exampleSentence2: 'Die Kollegin kommt aus Spanien.', exampleTranslation2: 'Đồng nghiệp đến từ Tây Ban Nha.' },
    { word: 'Chef', article: 'MASKULIN', plural: 'die Chefs', wordType: 'NOMEN', meaningVi: 'sếp', meaningEn: 'boss', exampleSentence1: 'Der Chef ist streng.', exampleTranslation1: 'Sếp nghiêm khắc.', exampleSentence2: 'Ich spreche mit dem Chef.', exampleTranslation2: 'Tôi nói chuyện với sếp.' },
    { word: 'Abteilung', article: 'FEMININ', plural: 'die Abteilungen', wordType: 'NOMEN', meaningVi: 'phòng ban', meaningEn: 'department', exampleSentence1: 'Welche Abteilung?', exampleTranslation1: 'Phòng ban nào?', exampleSentence2: 'Die Abteilung hat 10 Mitarbeiter.', exampleTranslation2: 'Phòng ban có 10 nhân viên.' },
    { word: 'Mitarbeiter', article: 'MASKULIN', plural: 'die Mitarbeiter', wordType: 'NOMEN', meaningVi: 'nhân viên', meaningEn: 'employee', exampleSentence1: 'Wir suchen neue Mitarbeiter.', exampleTranslation1: 'Tuyển nhân viên mới.', exampleSentence2: 'Die Mitarbeiter sind zufrieden.', exampleTranslation2: 'Nhân viên hài lòng.' },
    { word: 'Stelle', article: 'FEMININ', plural: 'die Stellen', wordType: 'NOMEN', meaningVi: 'vị trí (việc làm)', meaningEn: 'position, job', exampleSentence1: 'Die Stelle ist frei.', exampleTranslation1: 'Vị trí trống.', exampleSentence2: 'Ich suche eine neue Stelle.', exampleTranslation2: 'Tôi tìm việc mới.' },
    { word: 'Vollzeit', article: 'FEMININ', plural: '-', wordType: 'NOMEN', meaningVi: 'toàn thời gian', meaningEn: 'full-time', exampleSentence1: 'Ich arbeite Vollzeit.', exampleTranslation1: 'Tôi làm toàn thời gian.', exampleSentence2: 'Eine Vollzeitstelle.', exampleTranslation2: 'Vị trí toàn thời gian.' },
    { word: 'Teilzeit', article: 'FEMININ', plural: '-', wordType: 'NOMEN', meaningVi: 'bán thời gian', meaningEn: 'part-time', exampleSentence1: 'Sie arbeitet Teilzeit.', exampleTranslation1: 'Cô ấy làm bán thời gian.', exampleSentence2: 'Teilzeit ist flexibel.', exampleTranslation2: 'Bán thời gian linh hoạt.' },
    { word: 'Schicht', article: 'FEMININ', plural: 'die Schichten', wordType: 'NOMEN', meaningVi: 'ca làm việc', meaningEn: 'shift', exampleSentence1: 'Ich arbeite in Schichten.', exampleTranslation1: 'Tôi làm theo ca.', exampleSentence2: 'Nachtschicht ist hart.', exampleTranslation2: 'Ca đêm vất vả.' },
    { word: 'Besprechung', article: 'FEMININ', plural: 'die Besprechungen', wordType: 'NOMEN', meaningVi: 'cuộc họp', meaningEn: 'meeting', exampleSentence1: 'Wir haben eine Besprechung.', exampleTranslation1: 'Chúng tôi có cuộc họp.', exampleSentence2: 'Die Besprechung ist um 10 Uhr.', exampleTranslation2: 'Cuộc họp lúc 10 giờ.' },
    { word: 'Aufgabe', article: 'FEMININ', plural: 'die Aufgaben', wordType: 'NOMEN', meaningVi: 'nhiệm vụ', meaningEn: 'task', exampleSentence1: 'Das ist meine Aufgabe.', exampleTranslation1: 'Đó là nhiệm vụ cua tôi.', exampleSentence2: 'Ich habe viele Aufgaben.', exampleTranslation2: 'Tôi có nhiều nhiệm vụ.' },
    { word: 'Ergebnis', article: 'NEUTRUM', plural: 'die Ergebnisse', wordType: 'NOMEN', meaningVi: 'kết quả', meaningEn: 'result', exampleSentence1: 'Das Ergebnis ist gut.', exampleTranslation1: 'Kết quả tốt.', exampleSentence2: 'Wir warten auf das Ergebnis.', exampleTranslation2: 'Chúng tôi chờ kết quả.' },
    { word: 'verdienen', wordType: 'VERB', meaningVi: 'kiếm tiền', meaningEn: 'to earn', conjugation: { praesens: { ich: 'verdiene', du: 'verdienst', er_sie_es: 'verdient', wir: 'verdienen', ihr: 'verdient', sie_Sie: 'verdienen' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Wie viel verdienst du?', exampleTranslation1: 'Bạn kiếm bao nhiêu?', exampleSentence2: 'Er verdient gut.', exampleTranslation2: 'Anh ấy kiếm tốt.' },
    { word: 'einstellen', wordType: 'VERB', meaningVi: 'tuyển dụng', meaningEn: 'to hire', conjugation: { praesens: { ich: 'stelle ein', du: 'stellst ein', er_sie_es: 'stellt ein', wir: 'stellen ein', ihr: 'stellt ein', sie_Sie: 'stellen ein' }, isIrregular: false, isSeparable: true }, exampleSentence1: 'Die Firma stellt neue Leute ein.', exampleTranslation1: 'Công ty tuyển người mới.', exampleSentence2: 'Sie wurde eingestellt.', exampleTranslation2: 'Cô ấy được tuyển.' },
    { word: 'selbstständig', wordType: 'ADJEKTIV', meaningVi: 'tự kinh doanh', meaningEn: 'self-employed', exampleSentence1: 'Er ist selbstständig.', exampleTranslation1: 'Anh ấy tự kinh doanh.', exampleSentence2: 'Selbstständig arbeiten.', exampleTranslation2: 'Làm việc tự kinh doanh.' },
    { word: 'arbeitslos', wordType: 'ADJEKTIV', meaningVi: 'thất nghiệp', meaningEn: 'unemployed', exampleSentence1: 'Er ist arbeitslos.', exampleTranslation1: 'Anh ấy thất nghiệp.', exampleSentence2: 'Arbeitslose bekommen Geld.', exampleTranslation2: 'Người thất nghiệp nhận tiền.' },
    { word: 'Arbeitsamt', article: 'NEUTRUM', plural: 'die Arbeitsämter', wordType: 'NOMEN', meaningVi: 'sở lao động', meaningEn: 'employment office', exampleSentence1: 'Gehen Sie zum Arbeitsamt.', exampleTranslation1: 'Đến sở lao động.', exampleSentence2: 'Das Arbeitsamt hilft.', exampleTranslation2: 'Sở lao động hỗ trợ.' },
])

console.log(`\n📊 Batch 5 total: ${total} words (themes 09-10)`)
