/**
 * A2 Vocabulary — Themes 07–10
 */
import { writeFileSync } from 'fs'
import path from 'path'
const D = 'content/a2/vocabulary'
function w(f: string, t: any, ws: any[]) { writeFileSync(path.join(D, f), JSON.stringify({ theme: t, words: ws }, null, 4) + '\n'); console.log(`  ✅ ${f}: ${ws.length} words — ${t.name}`); return ws.length }
let total = 0

// 07 — Kleidung & Mode
total += w('07-kleidung-mode.json', { slug: 'a2-kleidung-mode', name: 'Kleidung & Mode', nameVi: 'Quần áo & Thời trang', nameEn: 'Clothing & Fashion', sortOrder: 7 }, [
    { word: 'Kleidung', article: 'FEMININ', plural: '-', wordType: 'NOMEN', meaningVi: 'quần áo', meaningEn: 'clothing', exampleSentence1: 'Welche Kleidung trägst du?', exampleTranslation1: 'Bạn mặc quần áo gì?', exampleSentence2: 'Warme Kleidung ist wichtig.', exampleTranslation2: 'Quần áo ấm quan trọng.' },
    { word: 'Mode', article: 'FEMININ', plural: 'die Moden', wordType: 'NOMEN', meaningVi: 'thời trang', meaningEn: 'fashion', exampleSentence1: 'Mode ist ihr Hobby.', exampleTranslation1: 'Thời trang là sở thích cô ấy.', exampleSentence2: 'Die Mode ändert sich schnell.', exampleTranslation2: 'Thời trang thay đổi nhanh.' },
    { word: 'Stoff', article: 'MASKULIN', plural: 'die Stoffe', wordType: 'NOMEN', meaningVi: 'vải, chất liệu', meaningEn: 'fabric, material', exampleSentence1: 'Der Stoff ist weich.', exampleTranslation1: 'Chất vải mềm.', exampleSentence2: 'Welcher Stoff ist das?', exampleTranslation2: 'Đây là chất vải gì?' },
    { word: 'Baumwolle', article: 'FEMININ', plural: '-', wordType: 'NOMEN', meaningVi: 'vải cotton', meaningEn: 'cotton', exampleSentence1: 'Das T-Shirt ist aus Baumwolle.', exampleTranslation1: 'Áo phông bằng cotton.', exampleSentence2: 'Baumwolle ist angenehm.', exampleTranslation2: 'Cotton thoải mái.' },
    { word: 'Leder', article: 'NEUTRUM', plural: '-', wordType: 'NOMEN', meaningVi: 'da thuộc', meaningEn: 'leather', exampleSentence1: 'Die Tasche ist aus Leder.', exampleTranslation1: 'Túi bằng da.', exampleSentence2: 'Leder ist teuer.', exampleTranslation2: 'Da đắt.' },
    { word: 'Wolle', article: 'FEMININ', plural: '-', wordType: 'NOMEN', meaningVi: 'len', meaningEn: 'wool', exampleSentence1: 'Der Pullover ist aus Wolle.', exampleTranslation1: 'Áo len bằng len.', exampleSentence2: 'Wolle ist warm.', exampleTranslation2: 'Len ấm.' },
    { word: 'Größe', article: 'FEMININ', plural: 'die Größen', wordType: 'NOMEN', meaningVi: 'kích cỡ, chiều cao', meaningEn: 'size', exampleSentence1: 'Welche Größe haben Sie?', exampleTranslation1: 'Bạn mặc size bao nhiêu?', exampleSentence2: 'Größe M, bitte.', exampleTranslation2: 'Size M.' },
    { word: 'anprobieren', wordType: 'VERB', meaningVi: 'thử (quần áo)', meaningEn: 'to try on', conjugation: { praesens: { ich: 'probiere an', du: 'probierst an', er_sie_es: 'probiert an', wir: 'probieren an', ihr: 'probiert an', sie_Sie: 'probieren an' }, isIrregular: false, isSeparable: true }, exampleSentence1: 'Kann ich das anprobieren?', exampleTranslation1: 'Tôi thử được không?', exampleSentence2: 'Probiere die Hose an!', exampleTranslation2: 'Thử cái quần đi!' },
    { word: 'passen', wordType: 'VERB', meaningVi: 'vừa, phù hợp', meaningEn: 'to fit', conjugation: { praesens: { ich: 'passe', du: 'passt', er_sie_es: 'passt', wir: 'passen', ihr: 'passt', sie_Sie: 'passen' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Das Kleid passt perfekt.', exampleTranslation1: 'Váy vừa hoàn hảo.', exampleSentence2: 'Die Schuhe passen nicht.', exampleTranslation2: 'Giày không vừa.' },
    { word: 'umtauschen', wordType: 'VERB', meaningVi: 'đổi (hàng)', meaningEn: 'to exchange', conjugation: { praesens: { ich: 'tausche um', du: 'tauschst um', er_sie_es: 'tauscht um', wir: 'tauschen um', ihr: 'tauscht um', sie_Sie: 'tauschen um' }, isIrregular: false, isSeparable: true }, exampleSentence1: 'Kann ich das umtauschen?', exampleTranslation1: 'Tôi đổi được không?', exampleSentence2: 'Ich möchte den Rock umtauschen.', exampleTranslation2: 'Tôi muốn đổi cái váy.' },
    { word: 'Angebot', article: 'NEUTRUM', plural: 'die Angebote', wordType: 'NOMEN', meaningVi: 'khuyến mãi, đề xuất', meaningEn: 'offer, deal', exampleSentence1: 'Das ist ein gutes Angebot.', exampleTranslation1: 'Đó là ưu đãi tốt.', exampleSentence2: 'Sonderangebote heute!', exampleTranslation2: 'Khuyến mãi đặc biệt hôm nay!' },
    { word: 'Rabatt', article: 'MASKULIN', plural: 'die Rabatte', wordType: 'NOMEN', meaningVi: 'giảm giá', meaningEn: 'discount', exampleSentence1: 'Es gibt 20% Rabatt.', exampleTranslation1: 'Giảm 20%.', exampleSentence2: 'Gibt es einen Rabatt?', exampleTranslation2: 'Có giảm giá không?' },
    { word: 'Schlussverkauf', article: 'MASKULIN', plural: 'die Schlussverkäufe', wordType: 'NOMEN', meaningVi: 'đại hạ giá', meaningEn: 'clearance sale', exampleSentence1: 'Schlussverkauf im Januar.', exampleTranslation1: 'Đại hạ giá tháng 1.', exampleSentence2: 'Alles im Schlussverkauf.', exampleTranslation2: 'Mọi thứ hạ giá.' },
    { word: 'Kasse', article: 'FEMININ', plural: 'die Kassen', wordType: 'NOMEN', meaningVi: 'quầy thu ngân', meaningEn: 'cash register, checkout', exampleSentence1: 'Bitte bezahlen Sie an der Kasse.', exampleTranslation1: 'Vui lòng thanh toán tại quầy.', exampleSentence2: 'Die Kasse ist dort.', exampleTranslation2: 'Quầy thu ngân ở kia.' },
    { word: 'Quittung', article: 'FEMININ', plural: 'die Quittungen', wordType: 'NOMEN', meaningVi: 'biên lai', meaningEn: 'receipt', exampleSentence1: 'Möchten Sie eine Quittung?', exampleTranslation1: 'Bạn muốn biên lai không?', exampleSentence2: 'Bewahren Sie die Quittung auf.', exampleTranslation2: 'Giữ lại biên lai.' },
    { word: 'eng', wordType: 'ADJEKTIV', meaningVi: 'chật', meaningEn: 'tight, narrow', exampleSentence1: 'Die Hose ist zu eng.', exampleTranslation1: 'Quần quá chật.', exampleSentence2: 'Die Straße ist eng.', exampleTranslation2: 'Đường hẹp.' },
    { word: 'weit', wordType: 'ADJEKTIV', meaningVi: 'rộng, xa', meaningEn: 'wide, far', exampleSentence1: 'Das Hemd ist zu weit.', exampleTranslation1: 'Áo sơ mi quá rộng.', exampleSentence2: 'Wie weit ist es?', exampleTranslation2: 'Bao xa?' },
    { word: 'gestreift', wordType: 'ADJEKTIV', meaningVi: 'kẻ sọc', meaningEn: 'striped', exampleSentence1: 'Ein gestreiftes Hemd.', exampleTranslation1: 'Áo kẻ sọc.', exampleSentence2: 'Magst du gestreifte Muster?', exampleTranslation2: 'Bạn thích mẫu kẻ sọc không?' },
    { word: 'kariert', wordType: 'ADJEKTIV', meaningVi: 'kẻ ca rô', meaningEn: 'checkered, plaid', exampleSentence1: 'Ein karierter Rock.', exampleTranslation1: 'Váy kẻ ca rô.', exampleSentence2: 'Karierte Hemden.', exampleTranslation2: 'Áo ca rô.' },
    { word: 'modisch', wordType: 'ADJEKTIV', meaningVi: 'thời trang', meaningEn: 'fashionable', exampleSentence1: 'Das Kleid ist modisch.', exampleTranslation1: 'Váy thời trang.', exampleSentence2: 'Sie kleidet sich modisch.', exampleTranslation2: 'Cô ấy ăn mặc thời trang.' },
    { word: 'elegant', wordType: 'ADJEKTIV', meaningVi: 'thanh lịch', meaningEn: 'elegant', exampleSentence1: 'Das ist ein elegantes Kleid.', exampleTranslation1: 'Đó là váy thanh lịch.', exampleSentence2: 'Er sieht elegant aus.', exampleTranslation2: 'Anh ấy trông thanh lịch.' },
    { word: 'Schmuck', article: 'MASKULIN', plural: '-', wordType: 'NOMEN', meaningVi: 'trang sức', meaningEn: 'jewelry', exampleSentence1: 'Sie trägt Schmuck.', exampleTranslation1: 'Cô ấy đeo trang sức.', exampleSentence2: 'Goldener Schmuck.', exampleTranslation2: 'Trang sức vàng.' },
    { word: 'Gürtel', article: 'MASKULIN', plural: 'die Gürtel', wordType: 'NOMEN', meaningVi: 'thắt lưng', meaningEn: 'belt', exampleSentence1: 'Der Gürtel passt gut.', exampleTranslation1: 'Thắt lưng vừa.', exampleSentence2: 'Brauchst du einen Gürtel?', exampleTranslation2: 'Bạn cần thắt lưng không?' },
    { word: 'Handschuh', article: 'MASKULIN', plural: 'die Handschuhe', wordType: 'NOMEN', meaningVi: 'găng tay', meaningEn: 'glove', exampleSentence1: 'Zieh Handschuhe an!', exampleTranslation1: 'Đeo găng tay đi!', exampleSentence2: 'Wo sind meine Handschuhe?', exampleTranslation2: 'Găng tay tôi ở đâu?' },
    { word: 'Schal', article: 'MASKULIN', plural: 'die Schals', wordType: 'NOMEN', meaningVi: 'khăn choàng', meaningEn: 'scarf', exampleSentence1: 'Nimm einen Schal mit!', exampleTranslation1: 'Mang khăn choàng đi!', exampleSentence2: 'Der Schal ist warm.', exampleTranslation2: 'Khăn choàng ấm.' },
])

// 08 — Dienstleistungen & Amt
total += w('08-dienstleistungen-amt.json', { slug: 'a2-dienstleistungen-amt', name: 'Dienstleistungen & Amt', nameVi: 'Dịch vụ & Cơ quan', nameEn: 'Services & Government', sortOrder: 8 }, [
    { word: 'Amt', article: 'NEUTRUM', plural: 'die Ämter', wordType: 'NOMEN', meaningVi: 'cơ quan nhà nước', meaningEn: 'office, authority', exampleSentence1: 'Ich muss zum Amt gehen.', exampleTranslation1: 'Tôi phải đến cơ quan.', exampleSentence2: 'Das Amt ist geschlossen.', exampleTranslation2: 'Cơ quan đóng cửa.' },
    { word: 'Formular', article: 'NEUTRUM', plural: 'die Formulare', wordType: 'NOMEN', meaningVi: 'mẫu đơn', meaningEn: 'form', exampleSentence1: 'Füllen Sie das Formular aus.', exampleTranslation1: 'Điền vào mẫu đơn.', exampleSentence2: 'Wo ist das Formular?', exampleTranslation2: 'Mẫu đơn ở đâu?' },
    { word: 'Antrag', article: 'MASKULIN', plural: 'die Anträge', wordType: 'NOMEN', meaningVi: 'đơn xin', meaningEn: 'application', exampleSentence1: 'Ich stelle einen Antrag.', exampleTranslation1: 'Tôi nộp đơn xin.', exampleSentence2: 'Der Antrag wurde genehmigt.', exampleTranslation2: 'Đơn được chấp nhận.' },
    { word: 'Genehmigung', article: 'FEMININ', plural: 'die Genehmigungen', wordType: 'NOMEN', meaningVi: 'giấy phép', meaningEn: 'permission, permit', exampleSentence1: 'Sie brauchen eine Genehmigung.', exampleTranslation1: 'Bạn cần giấy phép.', exampleSentence2: 'Die Genehmigung dauert lang.', exampleTranslation2: 'Cấp phép lâu.' },
    { word: 'Anmeldung', article: 'FEMININ', plural: 'die Anmeldungen', wordType: 'NOMEN', meaningVi: 'đăng ký', meaningEn: 'registration', exampleSentence1: 'Die Anmeldung ist Pflicht.', exampleTranslation1: 'Đăng ký bắt buộc.', exampleSentence2: 'Wo ist die Anmeldung?', exampleTranslation2: 'Đăng ký ở đâu?' },
    { word: 'sich anmelden', wordType: 'VERB', meaningVi: 'đăng ký', meaningEn: 'to register', conjugation: { praesens: { ich: 'melde mich an', du: 'meldest dich an', er_sie_es: 'meldet sich an', wir: 'melden uns an', ihr: 'meldet euch an', sie_Sie: 'melden sich an' }, isIrregular: false, isSeparable: true }, exampleSentence1: 'Sie müssen sich anmelden.', exampleTranslation1: 'Bạn phải đăng ký.', exampleSentence2: 'Ich habe mich angemeldet.', exampleTranslation2: 'Tôi đã đăng ký.' },
    { word: 'Bescheinigung', article: 'FEMININ', plural: 'die Bescheinigungen', wordType: 'NOMEN', meaningVi: 'giấy chứng nhận', meaningEn: 'certificate, confirmation', exampleSentence1: 'Ich brauche eine Bescheinigung.', exampleTranslation1: 'Tôi cần giấy chứng nhận.', exampleSentence2: 'Die Bescheinigung ist fertig.', exampleTranslation2: 'Giấy chứng nhận xong.' },
    { word: 'Unterschrift', article: 'FEMININ', plural: 'die Unterschriften', wordType: 'NOMEN', meaningVi: 'chữ ký', meaningEn: 'signature', exampleSentence1: 'Ihre Unterschrift bitte.', exampleTranslation1: 'Xin ký tên.', exampleSentence2: 'Die Unterschrift fehlt.', exampleTranslation2: 'Thiếu chữ ký.' },
    { word: 'unterschreiben', wordType: 'VERB', meaningVi: 'ký tên', meaningEn: 'to sign', conjugation: { praesens: { ich: 'unterschreibe', du: 'unterschreibst', er_sie_es: 'unterschreibt', wir: 'unterschreiben', ihr: 'unterschreibt', sie_Sie: 'unterschreiben' }, isIrregular: true, isSeparable: false }, exampleSentence1: 'Unterschreiben Sie hier.', exampleTranslation1: 'Ký ở đây.', exampleSentence2: 'Hast du unterschrieben?', exampleTranslation2: 'Bạn ký chưa?' },
    { word: 'Kopie', article: 'FEMININ', plural: 'die Kopien', wordType: 'NOMEN', meaningVi: 'bản sao', meaningEn: 'copy', exampleSentence1: 'Bringen Sie eine Kopie mit.', exampleTranslation1: 'Mang theo bản sao.', exampleSentence2: 'Ich brauche eine Kopie.', exampleTranslation2: 'Tôi cần bản sao.' },
    { word: 'Beratung', article: 'FEMININ', plural: 'die Beratungen', wordType: 'NOMEN', meaningVi: 'tư vấn', meaningEn: 'consultation, advice', exampleSentence1: 'Ich möchte eine Beratung.', exampleTranslation1: 'Tôi muốn tư vấn.', exampleSentence2: 'Die Beratung ist kostenlos.', exampleTranslation2: 'Tư vấn miễn phí.' },
    { word: 'beraten', wordType: 'VERB', meaningVi: 'tư vấn', meaningEn: 'to advise', conjugation: { praesens: { ich: 'berate', du: 'berätst', er_sie_es: 'berät', wir: 'beraten', ihr: 'beratet', sie_Sie: 'beraten' }, isIrregular: true, isSeparable: false }, exampleSentence1: 'Er berät mich gut.', exampleTranslation1: 'Anh ấy tư vấn tốt.', exampleSentence2: 'Lassen Sie sich beraten.', exampleTranslation2: 'Hãy đi tư vấn.' },
    { word: 'Beschwerde', article: 'FEMININ', plural: 'die Beschwerden', wordType: 'NOMEN', meaningVi: 'khiếu nại', meaningEn: 'complaint', exampleSentence1: 'Ich möchte eine Beschwerde machen.', exampleTranslation1: 'Tôi muốn khiếu nại.', exampleSentence2: 'Die Beschwerde wurde bearbeitet.', exampleTranslation2: 'Khiếu nại đã được xử lý.' },
    { word: 'sich beschweren', wordType: 'VERB', meaningVi: 'phàn nàn, khiếu nại', meaningEn: 'to complain', conjugation: { praesens: { ich: 'beschwere mich', du: 'beschwerst dich', er_sie_es: 'beschwert sich', wir: 'beschweren uns', ihr: 'beschwert euch', sie_Sie: 'beschweren sich' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Ich möchte mich beschweren.', exampleTranslation1: 'Tôi muốn phàn nàn.', exampleSentence2: 'Er beschwert sich über den Lärm.', exampleTranslation2: 'Anh ấy phàn nàn về tiếng ồn.' },
    { word: 'Steuern', plural: 'die Steuern', wordType: 'NOMEN', meaningVi: 'thuế', meaningEn: 'taxes', notes: 'Nur Plural üblich', exampleSentence1: 'Steuern muss man bezahlen.', exampleTranslation1: 'Phải nộp thuế.', exampleSentence2: 'Die Steuern sind hoch.', exampleTranslation2: 'Thuế cao.' },
    { word: 'Versicherung', article: 'FEMININ', plural: 'die Versicherungen', wordType: 'NOMEN', meaningVi: 'bảo hiểm', meaningEn: 'insurance', exampleSentence1: 'Die Versicherung zahlt das.', exampleTranslation1: 'Bảo hiểm trả tiền.', exampleSentence2: 'Hast du eine Versicherung?', exampleTranslation2: 'Bạn có bảo hiểm không?' },
    { word: 'Konto', article: 'NEUTRUM', plural: 'die Konten', wordType: 'NOMEN', meaningVi: 'tài khoản', meaningEn: 'account', exampleSentence1: 'Ich möchte ein Konto eröffnen.', exampleTranslation1: 'Tôi muốn mở tài khoản.', exampleSentence2: 'Das Geld ist auf dem Konto.', exampleTranslation2: 'Tiền trong tài khoản.' },
    { word: 'überweisen', wordType: 'VERB', meaningVi: 'chuyển khoản', meaningEn: 'to transfer', conjugation: { praesens: { ich: 'überweise', du: 'überweist', er_sie_es: 'überweist', wir: 'überweisen', ihr: 'überweist', sie_Sie: 'überweisen' }, isIrregular: true, isSeparable: false }, exampleSentence1: 'Ich überweise das Geld.', exampleTranslation1: 'Tôi chuyển khoản.', exampleSentence2: 'Bitte überweisen Sie die Miete.', exampleTranslation2: 'Vui lòng chuyển khoản tiền thuê.' },
    { word: 'abheben', wordType: 'VERB', meaningVi: 'rút tiền', meaningEn: 'to withdraw', conjugation: { praesens: { ich: 'hebe ab', du: 'hebst ab', er_sie_es: 'hebt ab', wir: 'heben ab', ihr: 'hebt ab', sie_Sie: 'heben ab' }, isIrregular: true, isSeparable: true }, exampleSentence1: 'Ich hebe Geld ab.', exampleTranslation1: 'Tôi rút tiền.', exampleSentence2: 'Wo kann ich Geld abheben?', exampleTranslation2: 'Rút tiền ở đâu?' },
    { word: 'einzahlen', wordType: 'VERB', meaningVi: 'nạp tiền', meaningEn: 'to deposit', conjugation: { praesens: { ich: 'zahle ein', du: 'zahlst ein', er_sie_es: 'zahlt ein', wir: 'zahlen ein', ihr: 'zahlt ein', sie_Sie: 'zahlen ein' }, isIrregular: false, isSeparable: true }, exampleSentence1: 'Ich zahle Geld ein.', exampleTranslation1: 'Tôi nạp tiền.', exampleSentence2: 'Bitte zahlen Sie 500 Euro ein.', exampleTranslation2: 'Vui lòng nạp 500 Euro.' },
    { word: 'Überweisung', article: 'FEMININ', plural: 'die Überweisungen', wordType: 'NOMEN', meaningVi: 'chuyển khoản', meaningEn: 'transfer', exampleSentence1: 'Die Überweisung dauert 2 Tage.', exampleTranslation1: 'Chuyển khoản mất 2 ngày.', exampleSentence2: 'Bezahlung per Überweisung.', exampleTranslation2: 'Thanh toán bằng chuyển khoản.' },
    { word: 'Sparkasse', article: 'FEMININ', plural: 'die Sparkassen', wordType: 'NOMEN', meaningVi: 'quỹ tiết kiệm', meaningEn: 'savings bank', exampleSentence1: 'Ich gehe zur Sparkasse.', exampleTranslation1: 'Tôi đến quỹ tiết kiệm.', exampleSentence2: 'Die Sparkasse ist um die Ecke.', exampleTranslation2: 'Quỹ tiết kiệm ở góc phố.' },
    { word: 'Geldautomat', article: 'MASKULIN', plural: 'die Geldautomaten', wordType: 'NOMEN', meaningVi: 'máy ATM', meaningEn: 'ATM', exampleSentence1: 'Wo ist der nächste Geldautomat?', exampleTranslation1: 'ATM gần nhất ở đâu?', exampleSentence2: 'Der Geldautomat ist kaputt.', exampleTranslation2: 'ATM hỏng.' },
])

console.log(`\n📊 Batch 4 total: ${total} words (themes 07-08)`)
