/**
 * A2 Vocabulary — Themes 15–17
 */
import { writeFileSync } from 'fs'
import path from 'path'
const D = 'content/a2/vocabulary'
function w(f: string, t: any, ws: any[]) { writeFileSync(path.join(D, f), JSON.stringify({ theme: t, words: ws }, null, 4) + '\n'); console.log(`  ✅ ${f}: ${ws.length} words — ${t.name}`); return ws.length }
let total = 0

// 15 — Gefühle & Meinungen
total += w('15-gefuehle-meinungen.json', { slug: 'a2-gefuehle-meinungen', name: 'Gefühle & Meinungen', nameVi: 'Cảm xúc & Quan điểm', nameEn: 'Feelings & Opinions', sortOrder: 15 }, [
    { word: 'Gefühl', article: 'NEUTRUM', plural: 'die Gefühle', wordType: 'NOMEN', meaningVi: 'cảm xúc, cảm giác', meaningEn: 'feeling', exampleSentence1: 'Ich habe ein gutes Gefühl.', exampleTranslation1: 'Tôi có cảm giác tốt.', exampleSentence2: 'Zeig deine Gefühle!', exampleTranslation2: 'Bày tỏ cảm xúc!' },
    { word: 'Freude', article: 'FEMININ', plural: 'die Freuden', wordType: 'NOMEN', meaningVi: 'niềm vui', meaningEn: 'joy', exampleSentence1: 'Das macht mir Freude.', exampleTranslation1: 'Điều đó làm tôi vui.', exampleSentence2: 'Große Freude!', exampleTranslation2: 'Vui lớn!' },
    { word: 'Angst', article: 'FEMININ', plural: 'die Ängste', wordType: 'NOMEN', meaningVi: 'sợ hãi', meaningEn: 'fear, anxiety', exampleSentence1: 'Ich habe Angst vor Spinnen.', exampleTranslation1: 'Tôi sợ nhện.', exampleSentence2: 'Keine Angst!', exampleTranslation2: 'Đừng sợ!' },
    { word: 'Sorge', article: 'FEMININ', plural: 'die Sorgen', wordType: 'NOMEN', meaningVi: 'lo lắng', meaningEn: 'worry, concern', exampleSentence1: 'Ich mache mir Sorgen.', exampleTranslation1: 'Tôi lo lắng.', exampleSentence2: 'Keine Sorge!', exampleTranslation2: 'Đừng lo!' },
    { word: 'Ärger', article: 'MASKULIN', plural: '-', wordType: 'NOMEN', meaningVi: 'sự tức giận', meaningEn: 'anger, annoyance', exampleSentence1: 'Er hat viel Ärger.', exampleTranslation1: 'Anh ấy rất tức giận.', exampleSentence2: 'Das ist ärgerlich.', exampleTranslation2: 'Điều đó bực mình.' },
    { word: 'Überraschung', article: 'FEMININ', plural: 'die Überraschungen', wordType: 'NOMEN', meaningVi: 'bất ngờ', meaningEn: 'surprise', exampleSentence1: 'Was für eine Überraschung!', exampleTranslation1: 'Thật bất ngờ!', exampleSentence2: 'Ich habe eine Überraschung.', exampleTranslation2: 'Tôi có bất ngờ.' },
    { word: 'Enttäuschung', article: 'FEMININ', plural: 'die Enttäuschungen', wordType: 'NOMEN', meaningVi: 'sự thất vọng', meaningEn: 'disappointment', exampleSentence1: 'Das war eine Enttäuschung.', exampleTranslation1: 'Đó là sự thất vọng.', exampleSentence2: 'Große Enttäuschung.', exampleTranslation2: 'Thất vọng lớn.' },
    { word: 'Hoffnung', article: 'FEMININ', plural: 'die Hoffnungen', wordType: 'NOMEN', meaningVi: 'hy vọng', meaningEn: 'hope', exampleSentence1: 'Ich habe Hoffnung.', exampleTranslation1: 'Tôi có hy vọng.', exampleSentence2: 'Die Hoffnung stirbt zuletzt.', exampleTranslation2: 'Hy vọng chết cuối cùng.' },
    { word: 'sich freuen', wordType: 'VERB', meaningVi: 'vui mừng', meaningEn: 'to be happy, look forward to', conjugation: { praesens: { ich: 'freue mich', du: 'freust dich', er_sie_es: 'freut sich', wir: 'freuen uns', ihr: 'freut euch', sie_Sie: 'freuen sich' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Ich freue mich auf die Party.', exampleTranslation1: 'Tôi mong chờ buổi tiệc.', exampleSentence2: 'Wir freuen uns!', exampleTranslation2: 'Chúng tôi vui!' },
    { word: 'sich ärgern', wordType: 'VERB', meaningVi: 'tức giận', meaningEn: 'to be annoyed', conjugation: { praesens: { ich: 'ärgere mich', du: 'ärgerst dich', er_sie_es: 'ärgert sich', wir: 'ärgern uns', ihr: 'ärgert euch', sie_Sie: 'ärgern sich' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Ich ärgere mich über dich.', exampleTranslation1: 'Tôi tức giận bạn.', exampleSentence2: 'Ärger dich nicht!', exampleTranslation2: 'Đừng tức giận!' },
    { word: 'sich wundern', wordType: 'VERB', meaningVi: 'ngạc nhiên', meaningEn: 'to be surprised', conjugation: { praesens: { ich: 'wundere mich', du: 'wunderst dich', er_sie_es: 'wundert sich', wir: 'wundern uns', ihr: 'wundert euch', sie_Sie: 'wundern sich' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Ich wundere mich.', exampleTranslation1: 'Tôi ngạc nhiên.', exampleSentence2: 'Das wundert mich nicht.', exampleTranslation2: 'Điều đó không ngạc nhiên.' },
    { word: 'hoffen', wordType: 'VERB', meaningVi: 'hy vọng', meaningEn: 'to hope', conjugation: { praesens: { ich: 'hoffe', du: 'hoffst', er_sie_es: 'hofft', wir: 'hoffen', ihr: 'hofft', sie_Sie: 'hoffen' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Ich hoffe auf gutes Wetter.', exampleTranslation1: 'Tôi hy vọng trời đẹp.', exampleSentence2: 'Hoffen wir das Beste.', exampleTranslation2: 'Hy vọng điều tốt nhất.' },
    { word: 'Meinung', article: 'FEMININ', plural: 'die Meinungen', wordType: 'NOMEN', meaningVi: 'ý kiến', meaningEn: 'opinion', exampleSentence1: 'Was ist deine Meinung?', exampleTranslation1: 'Ý kiến bạn là gì?', exampleSentence2: 'Meiner Meinung nach...', exampleTranslation2: 'Theo tôi...' },
    { word: 'meinen', wordType: 'VERB', meaningVi: 'nghĩ, cho là', meaningEn: 'to think, mean', conjugation: { praesens: { ich: 'meine', du: 'meinst', er_sie_es: 'meint', wir: 'meinen', ihr: 'meint', sie_Sie: 'meinen' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Was meinst du?', exampleTranslation1: 'Bạn nghĩ sao?', exampleSentence2: 'Ich meine, das ist richtig.', exampleTranslation2: 'Tôi nghĩ đó đúng.' },
    { word: 'zustimmen', wordType: 'VERB', meaningVi: 'đồng ý', meaningEn: 'to agree', conjugation: { praesens: { ich: 'stimme zu', du: 'stimmst zu', er_sie_es: 'stimmt zu', wir: 'stimmen zu', ihr: 'stimmt zu', sie_Sie: 'stimmen zu' }, isIrregular: false, isSeparable: true }, exampleSentence1: 'Ich stimme dir zu.', exampleTranslation1: 'Tôi đồng ý với bạn.', exampleSentence2: 'Alle stimmen zu.', exampleTranslation2: 'Tất cả đồng ý.' },
    { word: 'ablehnen', wordType: 'VERB', meaningVi: 'từ chối', meaningEn: 'to reject, decline', conjugation: { praesens: { ich: 'lehne ab', du: 'lehnst ab', er_sie_es: 'lehnt ab', wir: 'lehnen ab', ihr: 'lehnt ab', sie_Sie: 'lehnen ab' }, isIrregular: false, isSeparable: true }, exampleSentence1: 'Ich lehne das Angebot ab.', exampleTranslation1: 'Tôi từ chối đề nghị.', exampleSentence2: 'Er hat abgelehnt.', exampleTranslation2: 'Anh ấy đã từ chối.' },
    { word: 'Vorschlag', article: 'MASKULIN', plural: 'die Vorschläge', wordType: 'NOMEN', meaningVi: 'đề xuất', meaningEn: 'suggestion, proposal', exampleSentence1: 'Ich habe einen Vorschlag.', exampleTranslation1: 'Tôi có đề xuất.', exampleSentence2: 'Guter Vorschlag!', exampleTranslation2: 'Đề xuất hay!' },
    { word: 'vorschlagen', wordType: 'VERB', meaningVi: 'đề xuất', meaningEn: 'to suggest', conjugation: { praesens: { ich: 'schlage vor', du: 'schlägst vor', er_sie_es: 'schlägt vor', wir: 'schlagen vor', ihr: 'schlagt vor', sie_Sie: 'schlagen vor' }, isIrregular: true, isSeparable: true }, exampleSentence1: 'Ich schlage ein Treffen vor.', exampleTranslation1: 'Tôi đề xuất cuộc họp.', exampleSentence2: 'Was schlägst du vor?', exampleTranslation2: 'Bạn đề xuất gì?' },
    { word: 'traurig', wordType: 'ADJEKTIV', meaningVi: 'buồn', meaningEn: 'sad', exampleSentence1: 'Ich bin traurig.', exampleTranslation1: 'Tôi buồn.', exampleSentence2: 'Eine traurige Geschichte.', exampleTranslation2: 'Một câu chuyện buồn.' },
    { word: 'glücklich', wordType: 'ADJEKTIV', meaningVi: 'hạnh phúc', meaningEn: 'happy', exampleSentence1: 'Ich bin glücklich.', exampleTranslation1: 'Tôi hạnh phúc.', exampleSentence2: 'Bist du glücklich?', exampleTranslation2: 'Bạn hạnh phúc không?' },
    { word: 'zufrieden', wordType: 'ADJEKTIV', meaningVi: 'hài lòng', meaningEn: 'satisfied', exampleSentence1: 'Ich bin zufrieden.', exampleTranslation1: 'Tôi hài lòng.', exampleSentence2: 'Sind Sie zufrieden?', exampleTranslation2: 'Bạn hài lòng không?' },
    { word: 'enttäuscht', wordType: 'ADJEKTIV', meaningVi: 'thất vọng', meaningEn: 'disappointed', exampleSentence1: 'Ich bin enttäuscht.', exampleTranslation1: 'Tôi thất vọng.', exampleSentence2: 'Er war sehr enttäuscht.', exampleTranslation2: 'Anh ấy rất thất vọng.' },
    { word: 'wütend', wordType: 'ADJEKTIV', meaningVi: 'giận dữ', meaningEn: 'angry, furious', exampleSentence1: 'Er ist wütend.', exampleTranslation1: 'Anh ấy giận dữ.', exampleSentence2: 'Sei nicht so wütend!', exampleTranslation2: 'Đừng giận thế!' },
    { word: 'nervös', wordType: 'ADJEKTIV', meaningVi: 'lo lắng, hồi hộp', meaningEn: 'nervous', exampleSentence1: 'Ich bin nervös.', exampleTranslation1: 'Tôi hồi hộp.', exampleSentence2: 'Sei nicht nervös!', exampleTranslation2: 'Đừng hồi hộp!' },
    { word: 'überrascht', wordType: 'ADJEKTIV', meaningVi: 'ngạc nhiên', meaningEn: 'surprised', exampleSentence1: 'Ich bin überrascht.', exampleTranslation1: 'Tôi ngạc nhiên.', exampleSentence2: 'Bist du überrascht?', exampleTranslation2: 'Bạn ngạc nhiên không?' },
    { word: 'einsam', wordType: 'ADJEKTIV', meaningVi: 'cô đơn', meaningEn: 'lonely', exampleSentence1: 'Er fühlt sich einsam.', exampleTranslation1: 'Anh ấy cảm thấy cô đơn.', exampleSentence2: 'Bist du manchmal einsam?', exampleTranslation2: 'Bạn có khi cô đơn không?' },
    { word: 'aufgeregt', wordType: 'ADJEKTIV', meaningVi: 'phấn khích, hào hứng', meaningEn: 'excited', exampleSentence1: 'Ich bin so aufgeregt!', exampleTranslation1: 'Tôi rất phấn khích!', exampleSentence2: 'Die Kinder sind aufgeregt.', exampleTranslation2: 'Trẻ em rất hào hứng.' },
    { word: 'dankbar', wordType: 'ADJEKTIV', meaningVi: 'biết ơn', meaningEn: 'grateful', exampleSentence1: 'Ich bin dir dankbar.', exampleTranslation1: 'Tôi biết ơn bạn.', exampleSentence2: 'Wir sind sehr dankbar.', exampleTranslation2: 'Chúng tôi rất biết ơn.' },
    { word: 'neidisch', wordType: 'ADJEKTIV', meaningVi: 'ghen tị', meaningEn: 'jealous, envious', exampleSentence1: 'Sei nicht neidisch!', exampleTranslation1: 'Đừng ghen tị!', exampleSentence2: 'Er ist neidisch auf dich.', exampleTranslation2: 'Anh ấy ghen tị với bạn.' },
])

// 16 — Technik & Alltag
total += w('16-technik-alltag.json', { slug: 'a2-technik-alltag', name: 'Technik & Alltag', nameVi: 'Kỹ thuật & Đời sống', nameEn: 'Technology & Daily Life', sortOrder: 16 }, [
    { word: 'Gerät', article: 'NEUTRUM', plural: 'die Geräte', wordType: 'NOMEN', meaningVi: 'thiết bị', meaningEn: 'device', exampleSentence1: 'Das Gerät ist neu.', exampleTranslation1: 'Thiết bị mới.', exampleSentence2: 'Welches Gerät benutzt du?', exampleTranslation2: 'Bạn dùng thiết bị nào?' },
    { word: 'Maschine', article: 'FEMININ', plural: 'die Maschinen', wordType: 'NOMEN', meaningVi: 'máy móc', meaningEn: 'machine', exampleSentence1: 'Die Maschine funktioniert gut.', exampleTranslation1: 'Máy hoạt động tốt.', exampleSentence2: 'Die Maschine ist kaputt.', exampleTranslation2: 'Máy hỏng.' },
    { word: 'Akku', article: 'MASKULIN', plural: 'die Akkus', wordType: 'NOMEN', meaningVi: 'pin sạc', meaningEn: 'battery', exampleSentence1: 'Der Akku ist leer.', exampleTranslation1: 'Pin hết.', exampleSentence2: 'Lade den Akku auf!', exampleTranslation2: 'Sạc pin!' },
    { word: 'Ladegerät', article: 'NEUTRUM', plural: 'die Ladegeräte', wordType: 'NOMEN', meaningVi: 'bộ sạc', meaningEn: 'charger', exampleSentence1: 'Wo ist mein Ladegerät?', exampleTranslation1: 'Bộ sạc tôi đâu?', exampleSentence2: 'Ich brauche ein Ladegerät.', exampleTranslation2: 'Tôi cần bộ sạc.' },
    { word: 'Stecker', article: 'MASKULIN', plural: 'die Stecker', wordType: 'NOMEN', meaningVi: 'phích cắm', meaningEn: 'plug', exampleSentence1: 'Steck den Stecker ein.', exampleTranslation1: 'Cắm phích cắm.', exampleSentence2: 'Der Stecker passt nicht.', exampleTranslation2: 'Phích cắm không vừa.' },
    { word: 'Taste', article: 'FEMININ', plural: 'die Tasten', wordType: 'NOMEN', meaningVi: 'phím, nút bấm', meaningEn: 'key, button', exampleSentence1: 'Drücken Sie die Taste.', exampleTranslation1: 'Bấm nút.', exampleSentence2: 'Welche Taste?', exampleTranslation2: 'Phím nào?' },
    { word: 'installieren', wordType: 'VERB', meaningVi: 'cài đặt', meaningEn: 'to install', conjugation: { praesens: { ich: 'installiere', du: 'installierst', er_sie_es: 'installiert', wir: 'installieren', ihr: 'installiert', sie_Sie: 'installieren' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Ich installiere die App.', exampleTranslation1: 'Tôi cài đặt app.', exampleSentence2: 'Die Software ist installiert.', exampleTranslation2: 'Phần mềm đã cài.' },
    { word: 'aktualisieren', wordType: 'VERB', meaningVi: 'cập nhật', meaningEn: 'to update', conjugation: { praesens: { ich: 'aktualisiere', du: 'aktualisierst', er_sie_es: 'aktualisiert', wir: 'aktualisieren', ihr: 'aktualisiert', sie_Sie: 'aktualisieren' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Aktualisiere die App!', exampleTranslation1: 'Cập nhật app!', exampleSentence2: 'Das System wird aktualisiert.', exampleTranslation2: 'Hệ thống đang cập nhật.' },
    { word: 'speichern', wordType: 'VERB', meaningVi: 'lưu', meaningEn: 'to save', conjugation: { praesens: { ich: 'speichere', du: 'speicherst', er_sie_es: 'speichert', wir: 'speichern', ihr: 'speichert', sie_Sie: 'speichern' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Speichere das Dokument!', exampleTranslation1: 'Lưu tài liệu!', exampleSentence2: 'Hast du gespeichert?', exampleTranslation2: 'Bạn lưu chưa?' },
    { word: 'löschen', wordType: 'VERB', meaningVi: 'xóa', meaningEn: 'to delete', conjugation: { praesens: { ich: 'lösche', du: 'löschst', er_sie_es: 'löscht', wir: 'löschen', ihr: 'löscht', sie_Sie: 'löschen' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Lösche die alte Datei.', exampleTranslation1: 'Xóa tệp cũ.', exampleSentence2: 'Die Nachricht wurde gelöscht.', exampleTranslation2: 'Tin nhắn đã xóa.' },
    { word: 'funktionieren', wordType: 'VERB', meaningVi: 'hoạt động', meaningEn: 'to work, function', conjugation: { praesens: { ich: 'funktioniere', du: 'funktionierst', er_sie_es: 'funktioniert', wir: 'funktionieren', ihr: 'funktioniert', sie_Sie: 'funktionieren' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Das funktioniert nicht.', exampleTranslation1: 'Cái này không hoạt động.', exampleSentence2: 'Alles funktioniert gut.', exampleTranslation2: 'Mọi thứ hoạt động tốt.' },
    { word: 'einschalten', wordType: 'VERB', meaningVi: 'bật', meaningEn: 'to turn on', conjugation: { praesens: { ich: 'schalte ein', du: 'schaltest ein', er_sie_es: 'schaltet ein', wir: 'schalten ein', ihr: 'schaltet ein', sie_Sie: 'schalten ein' }, isIrregular: false, isSeparable: true }, exampleSentence1: 'Schalte das Licht ein!', exampleTranslation1: 'Bật đèn!', exampleSentence2: 'Ich schalte den Computer ein.', exampleTranslation2: 'Tôi bật máy tính.' },
    { word: 'ausschalten', wordType: 'VERB', meaningVi: 'tắt', meaningEn: 'to turn off', conjugation: { praesens: { ich: 'schalte aus', du: 'schaltest aus', er_sie_es: 'schaltet aus', wir: 'schalten aus', ihr: 'schaltet aus', sie_Sie: 'schalten aus' }, isIrregular: false, isSeparable: true }, exampleSentence1: 'Schalte das Handy aus!', exampleTranslation1: 'Tắt điện thoại!', exampleSentence2: 'Vergiss nicht auszuschalten.', exampleTranslation2: 'Đừng quên tắt.' },
    { word: 'Werkzeug', article: 'NEUTRUM', plural: 'die Werkzeuge', wordType: 'NOMEN', meaningVi: 'dụng cụ', meaningEn: 'tool', exampleSentence1: 'Ich brauche Werkzeug.', exampleTranslation1: 'Tôi cần dụng cụ.', exampleSentence2: 'Wo ist das Werkzeug?', exampleTranslation2: 'Dụng cụ ở đâu?' },
    { word: 'Schere', article: 'FEMININ', plural: 'die Scheren', wordType: 'NOMEN', meaningVi: 'kéo', meaningEn: 'scissors', exampleSentence1: 'Hast du eine Schere?', exampleTranslation1: 'Bạn có kéo không?', exampleSentence2: 'Die Schere ist scharf.', exampleTranslation2: 'Kéo sắc.' },
    { word: 'Kleber', article: 'MASKULIN', plural: 'die Kleber', wordType: 'NOMEN', meaningVi: 'keo dán', meaningEn: 'glue', exampleSentence1: 'Ich brauche Kleber.', exampleTranslation1: 'Tôi cần keo dán.', exampleSentence2: 'Der Kleber hält gut.', exampleTranslation2: 'Keo dán tốt.' },
    { word: 'automatisch', wordType: 'ADJEKTIV', meaningVi: 'tự động', meaningEn: 'automatic', exampleSentence1: 'Die Tür öffnet sich automatisch.', exampleTranslation1: 'Cửa mở tự động.', exampleSentence2: 'Automatische Updates.', exampleTranslation2: 'Cập nhật tự động.' },
    { word: 'praktisch', wordType: 'ADJEKTIV', meaningVi: 'thực tế, tiện lợi', meaningEn: 'practical, handy', exampleSentence1: 'Das ist sehr praktisch.', exampleTranslation1: 'Rất tiện lợi.', exampleSentence2: 'Eine praktische Lösung.', exampleTranslation2: 'Giải pháp thực tế.' },
])

// 17 — Gesellschaft & Regeln
total += w('17-gesellschaft-regeln.json', { slug: 'a2-gesellschaft-regeln', name: 'Gesellschaft & Regeln', nameVi: 'Xã hội & Quy tắc', nameEn: 'Society & Rules', sortOrder: 17 }, [
    { word: 'Regel', article: 'FEMININ', plural: 'die Regeln', wordType: 'NOMEN', meaningVi: 'quy tắc', meaningEn: 'rule', exampleSentence1: 'Halten Sie sich an die Regeln.', exampleTranslation1: 'Tuân thủ quy tắc.', exampleSentence2: 'Das ist die Regel.', exampleTranslation2: 'Đó là quy tắc.' },
    { word: 'Gesetz', article: 'NEUTRUM', plural: 'die Gesetze', wordType: 'NOMEN', meaningVi: 'luật pháp', meaningEn: 'law', exampleSentence1: 'Das ist gegen das Gesetz.', exampleTranslation1: 'Đó là trái luật.', exampleSentence2: 'Das Gesetz ist streng.', exampleTranslation2: 'Luật nghiêm.' },
    { word: 'Pflicht', article: 'FEMININ', plural: 'die Pflichten', wordType: 'NOMEN', meaningVi: 'nghĩa vụ', meaningEn: 'duty, obligation', exampleSentence1: 'Das ist meine Pflicht.', exampleTranslation1: 'Đó là nghĩa vụ của tôi.', exampleSentence2: 'Rechte und Pflichten.', exampleTranslation2: 'Quyền và nghĩa vụ.' },
    { word: 'Recht', article: 'NEUTRUM', plural: 'die Rechte', wordType: 'NOMEN', meaningVi: 'quyền, luật', meaningEn: 'right, law', exampleSentence1: 'Jeder hat das Recht.', exampleTranslation1: 'Ai cũng có quyền.', exampleSentence2: 'Das ist mein Recht.', exampleTranslation2: 'Đó là quyền của tôi.' },
    { word: 'Verbot', article: 'NEUTRUM', plural: 'die Verbote', wordType: 'NOMEN', meaningVi: 'lệnh cấm', meaningEn: 'prohibition, ban', exampleSentence1: 'Rauchverbot im Gebäude.', exampleTranslation1: 'Cấm hút thuốc trong tòa nhà.', exampleSentence2: 'Das ist ein Verbot.', exampleTranslation2: 'Đó là lệnh cấm.' },
    { word: 'erlauben', wordType: 'VERB', meaningVi: 'cho phép', meaningEn: 'to allow', conjugation: { praesens: { ich: 'erlaube', du: 'erlaubst', er_sie_es: 'erlaubt', wir: 'erlauben', ihr: 'erlaubt', sie_Sie: 'erlauben' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Das ist nicht erlaubt.', exampleTranslation1: 'Điều đó không được phép.', exampleSentence2: 'Wer hat das erlaubt?', exampleTranslation2: 'Ai cho phép?' },
    { word: 'verbieten', wordType: 'VERB', meaningVi: 'cấm', meaningEn: 'to forbid', conjugation: { praesens: { ich: 'verbiete', du: 'verbietest', er_sie_es: 'verbietet', wir: 'verbieten', ihr: 'verbietet', sie_Sie: 'verbieten' }, isIrregular: true, isSeparable: false }, exampleSentence1: 'Rauchen ist hier verboten.', exampleTranslation1: 'Cấm hút thuốc ở đây.', exampleSentence2: 'Das verbiete ich!', exampleTranslation2: 'Tôi cấm điều đó!' },
    { word: 'Bürger', article: 'MASKULIN', plural: 'die Bürger', wordType: 'NOMEN', meaningVi: 'công dân', meaningEn: 'citizen', exampleSentence1: 'Die Bürger wählen.', exampleTranslation1: 'Công dân bầu cử.', exampleSentence2: 'Als Bürger hat man Rechte.', exampleTranslation2: 'Là công dân có quyền.' },
    { word: 'Demokratie', article: 'FEMININ', plural: 'die Demokratien', wordType: 'NOMEN', meaningVi: 'dân chủ', meaningEn: 'democracy', exampleSentence1: 'Deutschland ist eine Demokratie.', exampleTranslation1: 'Đức là nước dân chủ.', exampleSentence2: 'Demokratie ist wichtig.', exampleTranslation2: 'Dân chủ quan trọng.' },
    { word: 'wählen', wordType: 'VERB', meaningVi: 'chọn, bầu cử', meaningEn: 'to choose, to vote', conjugation: { praesens: { ich: 'wähle', du: 'wählst', er_sie_es: 'wählt', wir: 'wählen', ihr: 'wählt', sie_Sie: 'wählen' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Wir wählen am Sonntag.', exampleTranslation1: 'Chúng tôi bỏ phiếu chủ nhật.', exampleSentence2: 'Welche Partei wählst du?', exampleTranslation2: 'Bạn bầu đảng nào?' },
    { word: 'Gleichberechtigung', article: 'FEMININ', plural: '-', wordType: 'NOMEN', meaningVi: 'bình đẳng', meaningEn: 'equal rights', exampleSentence1: 'Gleichberechtigung ist wichtig.', exampleTranslation1: 'Bình đẳng quan trọng.', exampleSentence2: 'Für Gleichberechtigung kämpfen.', exampleTranslation2: 'Đấu tranh cho bình đẳng.' },
    { word: 'respektieren', wordType: 'VERB', meaningVi: 'tôn trọng', meaningEn: 'to respect', conjugation: { praesens: { ich: 'respektiere', du: 'respektierst', er_sie_es: 'respektiert', wir: 'respektieren', ihr: 'respektiert', sie_Sie: 'respektieren' }, isIrregular: false, isSeparable: false }, exampleSentence1: 'Wir respektieren alle.', exampleTranslation1: 'Chúng tôi tôn trọng mọi người.', exampleSentence2: 'Respektiere die Regeln.', exampleTranslation2: 'Tôn trọng quy tắc.' },
    { word: 'Integration', article: 'FEMININ', plural: '-', wordType: 'NOMEN', meaningVi: 'hội nhập', meaningEn: 'integration', exampleSentence1: 'Integration braucht Zeit.', exampleTranslation1: 'Hội nhập cần thời gian.', exampleSentence2: 'Integrationskurs besuchen.', exampleTranslation2: 'Tham gia khóa hội nhập.' },
    { word: 'Kultur', article: 'FEMININ', plural: 'die Kulturen', wordType: 'NOMEN', meaningVi: 'văn hóa', meaningEn: 'culture', exampleSentence1: 'Die deutsche Kultur ist reich.', exampleTranslation1: 'Văn hóa Đức phong phú.', exampleSentence2: 'Verschiedene Kulturen.', exampleTranslation2: 'Văn hóa đa dạng.' },
    { word: 'Tradition', article: 'FEMININ', plural: 'die Traditionen', wordType: 'NOMEN', meaningVi: 'truyền thống', meaningEn: 'tradition', exampleSentence1: 'Das ist eine alte Tradition.', exampleTranslation1: 'Đó là truyền thống cũ.', exampleSentence2: 'Traditionen sind wichtig.', exampleTranslation2: 'Truyền thống quan trọng.' },
    { word: 'Religion', article: 'FEMININ', plural: 'die Religionen', wordType: 'NOMEN', meaningVi: 'tôn giáo', meaningEn: 'religion', exampleSentence1: 'Religionsfreiheit ist ein Recht.', exampleTranslation1: 'Tự do tôn giáo là quyền.', exampleSentence2: 'Welche Religion hast du?', exampleTranslation2: 'Bạn theo tôn giáo nào?' },
    { word: 'öffentlich', wordType: 'ADJEKTIV', meaningVi: 'công cộng', meaningEn: 'public', exampleSentence1: 'Öffentliche Verkehrsmittel.', exampleTranslation1: 'Phương tiện công cộng.', exampleSentence2: 'Ein öffentlicher Platz.', exampleTranslation2: 'Nơi công cộng.' },
    { word: 'privat', wordType: 'ADJEKTIV', meaningVi: 'riêng tư, tư nhân', meaningEn: 'private', exampleSentence1: 'Das ist privat.', exampleTranslation1: 'Đó là riêng tư.', exampleSentence2: 'Eine private Schule.', exampleTranslation2: 'Trường tư.' },
    { word: 'freiwillig', wordType: 'ADJEKTIV', meaningVi: 'tình nguyện', meaningEn: 'voluntary', exampleSentence1: 'Die Teilnahme ist freiwillig.', exampleTranslation1: 'Tham gia tự nguyện.', exampleSentence2: 'Freiwillige Arbeit.', exampleTranslation2: 'Làm tình nguyện.' },
])

console.log(`\n📊 Batch 7 total: ${total} words (themes 15-17)`)
