import { PrismaClient } from '../apps/web/generated/prisma'
const prisma = new PrismaClient()

const batch = [
  {
    exerciseId: 'C1-T3-009',
    texts: [{ id: 'TextA', type: 'sachtext', title: 'Kunst als gesellschaftlicher Spiegel und Katalysator',
      content: 'Die Rolle der Kunst in der Gesellschaft wird seit der Antike kontrovers diskutiert. ___(1)___ In der Moderne hat sich die Funktion der Kunst grundlegend gewandelt. ___(2)___ Die zeitgenössische Kunstszene ist zunehmend von ökonomischen Interessen geprägt. ___(3)___ Gleichzeitig wächst das Potenzial der Kunst als Medium politischen Protests. ___(4)___ Die Frage nach der Autonomie des Kunstwerks bleibt virulent. ___(5)___ Kulturelle Teilhabe ist ein zentrales Thema der aktuellen Kunstpolitik. ___(6)___ Die Digitalisierung eröffnet neue Möglichkeiten der künstlerischen Produktion und Rezeption. ___(7)___ Die Zukunft der Kunst wird davon abhängen, ob sie ihre kritische Funktion bewahren kann. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Bereits Platon sah in der mimetischen Kunst eine Gefahr für die sittliche Ordnung, während Aristoteles ihr eine kathartische und damit gesellschaftlich konstruktive Wirkung zusprach.',b:'Kunst gibt es seit der Steinzeit.',c:'Viele Menschen besuchen Museen.',d:'Kunst ist subjektiv.'}, answer:'a', evidence:'seit der Antike kontrovers diskutiert', vocab:[{word:'Katharsis',type:'Nomen',meaning:'catharsis'}] },
      { n:2, opts:{a:'Die Avantgarde-Bewegungen des frühen 20. Jahrhunderts zerbrachen programmatisch die Grenzen zwischen Kunst und Leben und stellten die institutionellen Rahmenbedingungen ästhetischer Produktion radikal infrage.',b:'Moderne Kunst ist oft abstrakt.',c:'Viele Menschen verstehen moderne Kunst nicht.',d:'Impressionismus war eine wichtige Epoche.'}, answer:'a', evidence:'die Funktion der Kunst grundlegend gewandelt', vocab:[{word:'Avantgarde',type:'Nomen',meaning:'avant-garde'}] },
      { n:3, opts:{a:'Die Kommodifizierung von Kunst durch den globalisierten Kunstmarkt, in dem Werke primär als Spekulationsobjekte und Statussymbole fungieren, untergräbt die emanzipatorische Kraft ästhetischer Erfahrung.',b:'Kunstwerke werden immer teurer.',c:'Galerien machen viel Geld.',d:'Manche Künstler sind sehr reich.'}, answer:'a', evidence:'von ökonomischen Interessen geprägt', vocab:[{word:'Kommodifizierung',type:'Nomen',meaning:'commodification'}] },
      { n:4, opts:{a:'Streetart ist populär geworden.',b:'Von Ai Weiweis systemkritischen Installationen bis zu den kollektiven Aktionen von „Pussy Riot" zeigt sich, dass Kunst subversive Wirkmacht entfalten kann, die autoritäre Regime als Bedrohung wahrnehmen.',c:'Kunst und Politik sollten getrennt bleiben.',d:'Viele Künstler sind politisch engagiert.'}, answer:'b', evidence:'Kunst als Medium politischen Protests', vocab:[{word:'subversiv',type:'Adjektiv',meaning:'subversive'}] },
      { n:5, opts:{a:'Adornos Diktum von der Zweckfreiheit des Kunstwerks steht in produktiver Spannung zu engagierten Kunstkonzepten, die eine direkte gesellschaftliche Wirksamkeit anstreben.',b:'Kunst muss frei sein.',c:'Jeder kann Kunst machen.',d:'Die Kunstfreiheit ist ein Grundrecht.'}, answer:'a', evidence:'Autonomie des Kunstwerks', vocab:[{word:'Zweckfreiheit',type:'Nomen',meaning:'purposelessness'}] },
      { n:6, opts:{a:'Museen sollten kostenlos sein.',b:'Bildung ist wichtig.',c:'Die systematische Exklusion bildungsferner Schichten von kulturellen Angeboten reproduziert bestehende gesellschaftliche Ungleichheiten und widerspricht dem demokratischen Ideal gleicher Entfaltungsmöglichkeiten.',d:'Kultur ist für alle da.'}, answer:'c', evidence:'Kulturelle Teilhabe', vocab:[{word:'Exklusion',type:'Nomen',meaning:'exclusion'}] },
      { n:7, opts:{a:'NFTs haben den Kunstmarkt revolutioniert.',b:'Immersive Technologien, algorithmische Kreativität und dezentralisierte Distributionsplattformen demokratisieren die Kunstproduktion, werfen aber zugleich fundamentale Fragen nach Autorschaft, Originalität und dem Werkbegriff auf.',c:'Computer können keine Kunst erschaffen.',d:'Die meisten Künstler nutzen digitale Tools.'}, answer:'b', evidence:'Die Digitalisierung eröffnet neue Möglichkeiten', vocab:[{word:'Autorschaft',type:'Nomen',meaning:'authorship'}] },
      { n:8, opts:{a:'Die Zukunft wird es zeigen.',b:'Kunst wird immer überleben.',c:'In einer Welt zunehmender Vereinfachung und algorithmischer Steuerung kommt der Kunst die unverzichtbare Aufgabe zu, die Komplexität menschlicher Erfahrung sichtbar zu machen und Räume des Dissenses offenzuhalten.',d:'Künstler sollten besser bezahlt werden.'}, answer:'c', evidence:'ob sie ihre kritische Funktion bewahren kann', vocab:[{word:'Dissens',type:'Nomen',meaning:'dissent'}] },
    ]
  },
  {
    exerciseId: 'C1-T3-010',
    texts: [{ id: 'TextA', type: 'sachtext', title: 'Bildungsgerechtigkeit und soziale Mobilität',
      content: 'Der Zusammenhang zwischen sozialer Herkunft und Bildungserfolg ist in Deutschland besonders stark ausgeprägt. ___(1)___ Internationale Vergleichsstudien wie PISA haben diesen Befund wiederholt bestätigt. ___(2)___ Die Debatte um Bildungsgerechtigkeit wird von unterschiedlichen Gerechtigkeitskonzepten geprägt. ___(3)___ Das dreigliedrige Schulsystem steht dabei besonders in der Kritik. ___(4)___ Frühkindliche Bildung gilt als Schlüssel zur Verringerung von Bildungsungleichheiten. ___(5)___ Die Lehrerausbildung spielt eine zentrale Rolle für die Qualität des Unterrichts. ___(6)___ Digitale Bildungsangebote können sowohl Chancen als auch Risiken bergen. ___(7)___ Ein gerechtes Bildungssystem erfordert umfassende strukturelle Reformen. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'In kaum einem anderen OECD-Land determiniert der Bildungsgrad der Eltern die Schullaufbahn der Kinder so nachhaltig wie in Deutschland, wo die Korrelation zwischen sozioökonomischem Status und Kompetenzerwerb persistiert.',b:'Bildung ist ein Menschenrecht.',c:'Viele Kinder gehen nicht gern zur Schule.',d:'Deutschland hat ein gutes Bildungssystem.'}, answer:'a', evidence:'sozialer Herkunft und Bildungserfolg besonders stark ausgeprägt', vocab:[{word:'persistieren',type:'Verb',meaning:'to persist'}] },
      { n:2, opts:{a:'Die PISA-Studie wird alle drei Jahre durchgeführt.',b:'Besonders alarmierend ist der Befund, dass die Leistungsschere zwischen privilegierten und benachteiligten Schülern trotz zahlreicher Reformbemühungen nicht signifikant geschlossen werden konnte.',c:'Deutsche Schüler schneiden durchschnittlich ab.',d:'Finnland hat das beste Bildungssystem.'}, answer:'b', evidence:'PISA haben diesen Befund wiederholt bestätigt', vocab:[{word:'Leistungsschere',type:'Nomen',meaning:'performance gap'}] },
      { n:3, opts:{a:'Gerechtigkeit ist ein philosophischer Begriff.',b:'Alle Kinder sollten gleich behandelt werden.',c:'Während egalitaristische Ansätze gleiche Bildungsergebnisse anstreben, plädieren libertäre Positionen für Wahlfreiheit und Wettbewerb, während Capability-Theoretiker wie Amartya Sen die Befähigung zur autonomen Lebensgestaltung in den Mittelpunkt stellen.',d:'Es gibt verschiedene Meinungen.'}, answer:'c', evidence:'von unterschiedlichen Gerechtigkeitskonzepten geprägt', vocab:[{word:'egalitaristisch',type:'Adjektiv',meaning:'egalitarian'}] },
      { n:4, opts:{a:'Viele Eltern bevorzugen das Gymnasium.',b:'Gesamtschulen sind eine Alternative.',c:'Kritiker argumentieren, dass die frühe Selektion im Alter von zehn Jahren bestehende soziale Disparitäten zementiert, da Empfehlungen für weiterführende Schulen nachweislich durch herkunftsbedingte Erwartungshaltungen verzerrt werden.',d:'Das Gymnasium hat die längste Tradition.'}, answer:'c', evidence:'dreigliedrige Schulsystem steht in der Kritik', vocab:[{word:'Selektion',type:'Nomen',meaning:'selection'}] },
      { n:5, opts:{a:'Kinder lernen gerne.',b:'Langzeitstudien belegen, dass qualitativ hochwertige Kita-Betreuung insbesondere bei Kindern aus bildungsfernen Haushalten messbare und langfristige positive Effekte auf kognitive und sozio-emotionale Kompetenzen hat.',c:'Es gibt zu wenige Kitaplätze.',d:'Eltern sollten mehr vorlesen.'}, answer:'b', evidence:'Frühkindliche Bildung als Schlüssel', vocab:[{word:'bildungsfern',type:'Adjektiv',meaning:'educationally disadvantaged'}] },
      { n:6, opts:{a:'Lehrer werden schlecht bezahlt.',b:'Der Lehrerberuf ist anspruchsvoll.',c:'Empirische Bildungsforschung zeigt, dass die diagnostische Kompetenz, die Fähigkeit zur adaptiven Unterrichtsgestaltung und die interkulturelle Sensibilität von Lehrkräften die stärksten schulischen Prädiktoren für den Lernerfolg sind.',d:'Es fehlen viele Lehrkräfte.'}, answer:'c', evidence:'Die Lehrerausbildung spielt eine zentrale Rolle', vocab:[{word:'Prädiktor',type:'Nomen',meaning:'predictor'}] },
      { n:7, opts:{a:'Nicht alle Schüler haben einen Computer.',b:'Einerseits ermöglichen sie individualisiertes, selbstgesteuertes Lernen unabhängig von Ort und Zeit; andererseits droht ein „Digital Divide", der bestehende Ungleichheiten entlang sozioökonomischer Linien vertieft.',c:'Online-Unterricht ist nicht so gut.',d:'Die Schüler nutzen das Internet zum Spielen.'}, answer:'b', evidence:'sowohl Chancen als auch Risiken', vocab:[{word:'Digital Divide',type:'Nomen',meaning:'digital divide'}] },
      { n:8, opts:{a:'Bildung kostet Geld.',b:'Reformen brauchen Zeit.',c:'Jenseits isolierter Einzelmaßnahmen bedarf es eines systemischen Ansatzes, der die Durchlässigkeit zwischen Bildungswegen erhöht, multiprofessionelle Teams an Schulen verankert und die Ressourcenverteilung konsequent am Prinzip der bedarfsgerechten Förderung ausrichtet.',d:'Das Bildungssystem muss besser werden.'}, answer:'c', evidence:'umfassende strukturelle Reformen', vocab:[{word:'Durchlässigkeit',type:'Nomen',meaning:'permeability'}] },
    ]
  },
  {
    exerciseId: 'C1-T3-011',
    texts: [{ id: 'TextA', type: 'sachtext', title: 'Klimaanpassung und ökologische Transformation',
      content: 'Neben der Vermeidung weiterer Treibhausgasemissionen rückt die Anpassung an bereits unvermeidliche Klimafolgen verstärkt in den Fokus politischer Debatten. ___(1)___ Extremwetterereignisse nehmen weltweit an Häufigkeit und Intensität zu. ___(2)___ Die ökologische Transformation der Wirtschaft erfordert einen grundlegenden Strukturwandel. ___(3)___ Landwirtschaftliche Systeme müssen an veränderte klimatische Bedingungen angepasst werden. ___(4)___ Die Frage der Klimagerechtigkeit gewinnt zunehmend an Bedeutung. ___(5)___ Technologische Innovationen allein werden den Klimawandel nicht aufhalten können. ___(6)___ Die Rolle zivilgesellschaftlicher Akteure in der Klimapolitik wächst stetig. ___(7)___ Eine erfolgreiche Klimapolitik erfordert die Integration ökologischer, sozialer und wirtschaftlicher Ziele. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Das Klima verändert sich schnell.',b:'Während Mitigationsstrategien auf die Reduktion von Emissionen abzielen, umfassen Adaptationsmaßnahmen die vorausschauende Anpassung von Infrastruktur, Ökosystemen und Governance-Strukturen an die bereits eingetretenen und prognostizierten Veränderungen.',c:'Die Temperaturen steigen.',d:'Der Meeresspiegel steigt an.'}, answer:'b', evidence:'Anpassung an bereits unvermeidliche Klimafolgen', vocab:[{word:'Mitigation',type:'Nomen',meaning:'mitigation'}] },
      { n:2, opts:{a:'Überschwemmungen richten große Schäden an.',b:'Die Sommer werden heißer.',c:'Die ökonomischen Schäden durch Dürren, Überschwemmungen, Waldbrände und Stürme übersteigen bereits die Kosten präventiver Klimaschutzmaßnahmen um ein Vielfaches und belasten überproportional vulnerable Bevölkerungsgruppen.',d:'Es regnet öfter als früher.'}, answer:'c', evidence:'Extremwetterereignisse nehmen zu', vocab:[{word:'vulnerabel',type:'Adjektiv',meaning:'vulnerable'}] },
      { n:3, opts:{a:'Die Industrie muss sich wandeln.',b:'Der Übergang von einer linearen, auf fossilen Energieträgern basierenden Wirtschaft zu einem zirkulären, klimaneutralen Wirtschaftsmodell betrifft sämtliche Sektoren und erfordert massive Investitionen in erneuerbare Energien und nachhaltige Produktionsprozesse.',c:'Unternehmen müssen nachhaltig werden.',d:'Erneuerbare Energien werden günstiger.'}, answer:'b', evidence:'grundlegenden Strukturwandel', vocab:[{word:'zirkulär',type:'Adjektiv',meaning:'circular'}] },
      { n:4, opts:{a:'Landwirte beklagen Ernteausfälle.',b:'Bio-Landwirtschaft ist umweltfreundlicher.',c:'Diversifizierte Anbausysteme, trockenheitsresistente Sorten, agroforstwirtschaftliche Konzepte und eine grundlegende Reform der Subventionspolitik sind dabei wesentliche Bausteine einer klimaresilienten Agrarwende.',d:'Die Lebensmittelpreise steigen.'}, answer:'c', evidence:'Landwirtschaftliche Systeme angepasst werden', vocab:[{word:'Agrarwende',type:'Nomen',meaning:'agricultural transition'}] },
      { n:5, opts:{a:'Der globale Süden ist besonders betroffen.',b:'Die historisch größten Emittenten tragen die geringsten Klimafolgen, während diejenigen Länder und Bevölkerungsgruppen, die am wenigsten zum Klimawandel beigetragen haben, überproportional unter dessen Auswirkungen leiden.',c:'Alle Länder müssen zusammenarbeiten.',d:'Entwicklungsländer brauchen Hilfe.'}, answer:'b', evidence:'Klimagerechtigkeit', vocab:[{word:'Emittent',type:'Nomen',meaning:'emitter'}] },
      { n:6, opts:{a:'Ohne einen tiefgreifenden Wandel der Konsummuster, Mobilitätsgewohnheiten und Ernährungsweisen in den Industrieländern werden technologische Effizienzgewinne durch Rebound-Effekte konterkariert.',b:'Die Technik wird Lösungen finden.',c:'Elektroautos sind gut für die Umwelt.',d:'Kernenergie könnte helfen.'}, answer:'a', evidence:'Technologische Innovationen allein werden den Klimawandel nicht aufhalten', vocab:[{word:'Rebound-Effekt',type:'Nomen',meaning:'rebound effect'}] },
      { n:7, opts:{a:'Umweltverbände sind wichtig.',b:'Von „Fridays for Future" über lokale Energiegenossenschaften bis zu indigenen Umweltbewegungen schaffen zivilgesellschaftliche Akteure politischen Druck, treiben Innovationen voran und fungieren als Korrektiv gegenüber wirtschaftlichen Partikularinteressen.',c:'Demonstrationen bewirken wenig.',d:'Die Politik muss handeln.'}, answer:'b', evidence:'zivilgesellschaftlicher Akteure wächst stetig', vocab:[{word:'Partikularinteresse',type:'Nomen',meaning:'particular interest'}] },
      { n:8, opts:{a:'Klimaschutz ist teuer.',b:'Die nächste Generation wird Lösungen finden.',c:'Die Erde wird sich erholen.',d:'Nur ein gesamtgesellschaftlicher Transformationsprozess, der ökologische Nachhaltigkeit als Querschnittsaufgabe in allen Politikfeldern verankert und zugleich soziale Absicherung gewährleistet, kann eine gerechte und zukunftsfähige Entwicklung ermöglichen.',d2:''}, answer:'d', evidence:'Integration ökologischer, sozialer und wirtschaftlicher Ziele', vocab:[{word:'Querschnittsaufgabe',type:'Nomen',meaning:'cross-cutting task'}] },
    ]
  },
  {
    exerciseId: 'C1-T3-012',
    texts: [{ id: 'TextA', type: 'sachtext', title: 'Migration, Integration und gesellschaftlicher Zusammenhalt',
      content: 'Migrationsbewegungen prägen die demografische und kulturelle Entwicklung moderner Gesellschaften maßgeblich. ___(1)___ Die Debatte um Integration wird häufig von vereinfachenden Narrativen dominiert. ___(2)___ Arbeitsmarktintegration gilt als zentraler Indikator für gelungene Eingliederung. ___(3)___ Die Frage der kulturellen Identität in Einwanderungsgesellschaften ist komplex. ___(4)___ Bildungsinstitutionen spielen eine Schlüsselrolle im Integrationsprozess. ___(5)___ Die rechtliche Stellung von Migranten variiert erheblich. ___(6)___ Kommunen tragen die Hauptlast der praktischen Integrationsarbeit. ___(7)___ Eine erfolgreiche Integrationspolitik muss die gesamte Gesellschaft adressieren. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Viele Menschen verlassen ihre Heimat.',b:'Die Flucht ist gefährlich.',c:'Push- und Pull-Faktoren wie bewaffnete Konflikte, Klimafolgen, wirtschaftliche Disparitäten und familiäre Netzwerke erzeugen komplexe Migrationsmuster, die sich linearen Steuerungsversuchen weitgehend entziehen.',d:'Die Grenzen sollten geschlossen werden.'}, answer:'c', evidence:'Migrationsbewegungen prägen die demografische und kulturelle Entwicklung', vocab:[{word:'Disparität',type:'Nomen',meaning:'disparity'}] },
      { n:2, opts:{a:'Integration ist schwierig.',b:'Sowohl die Defizitperspektive, die Migranten primär als Problemträger wahrnimmt, als auch die idealisierende Diversitätsrhetorik verfehlen die Ambivalenz realer Integrationsprozesse.',c:'Die Medien berichten oft negativ.',d:'Nicht alle Migranten wollen sich integrieren.'}, answer:'b', evidence:'von vereinfachenden Narrativen dominiert', vocab:[{word:'Defizitperspektive',type:'Nomen',meaning:'deficit perspective'}] },
      { n:3, opts:{a:'Dabei zeigt die Forschung, dass neben formalen Qualifikationen auch informelle Netzwerke, Diskriminierungserfahrungen und die Anerkennung ausländischer Abschlüsse die Erwerbsteilhabe maßgeblich beeinflussen.',b:'Arbeit ist wichtig für die Integration.',c:'Viele Migranten sind hoch qualifiziert.',d:'Die Arbeitslosenquote ist gesunken.'}, answer:'a', evidence:'Arbeitsmarktintegration als zentraler Indikator', vocab:[{word:'Erwerbsteilhabe',type:'Nomen',meaning:'labor market participation'}] },
      { n:4, opts:{a:'Jeder hat eine eigene Kultur.',b:'Multikulturalismus wird kritisiert.',c:'Das Konzept hybrider Identitäten, die multiple kulturelle Zugehörigkeiten nicht als Widerspruch, sondern als Bereicherung begreifen, gewinnt gegenüber assimilationistischen Modellen zunehmend an wissenschaftlicher und gesellschaftlicher Akzeptanz.',d:'Integration bedeutet Anpassung.'}, answer:'c', evidence:'kulturellen Identität in Einwanderungsgesellschaften', vocab:[{word:'hybride Identität',type:'Nomen',meaning:'hybrid identity'}] },
      { n:5, opts:{a:'Schulen in Brennpunktvierteln sind unterfinanziert.',b:'Sprachförderung ist das Wichtigste.',c:'Als Orte der Sozialisation und des interkulturellen Kontakts können Schulen und Kindertagesstätten die Teilhabechancen zugewanderter Familien erhöhen, sofern sie mit adäquaten Ressourcen und diversitätssensiblem Personal ausgestattet sind.',d:'Migrantenkinder haben schlechtere Noten.'}, answer:'c', evidence:'Bildungsinstitutionen spielen eine Schlüsselrolle', vocab:[{word:'diversitätssensibel',type:'Adjektiv',meaning:'diversity-sensitive'}] },
      { n:6, opts:{a:'Das Aufenthaltsrecht ist kompliziert.',b:'Vom prekären Duldungsstatus über befristete Aufenthaltstitel bis hin zur vollen Staatsbürgerschaft erstreckt sich ein Spektrum, das die gesellschaftliche Teilhabe und die psychische Stabilität von Migranten nachhaltig beeinflusst.',c:'Jeder sollte einen Pass haben.',d:'Die Gesetze sind zu streng.'}, answer:'b', evidence:'Die rechtliche Stellung variiert erheblich', vocab:[{word:'Duldungsstatus',type:'Nomen',meaning:'toleration status'}] },
      { n:7, opts:{a:'Die Städte sind überfordert.',b:'Mehr Geld vom Bund wäre nötig.',c:'Die Bereitstellung von Wohnraum, Sprachkursen, Gesundheitsversorgung und niedrigschwelligen Beratungsangeboten erfordert eine verlässliche Finanzierung, koordinierte Governance und die Einbeziehung ehrenamtlicher Strukturen.',d:'Ehrenamtliche leisten wichtige Arbeit.'}, answer:'c', evidence:'Kommunen tragen die Hauptlast', vocab:[{word:'niedrigschwellig',type:'Adjektiv',meaning:'low-threshold'}] },
      { n:8, opts:{a:'Integration ist eine Aufgabe für alle.',b:'Die Gesellschaft muss toleranter werden.',c:'Das geht nicht über Nacht.',d:'Denn Integration ist kein einseitiger Assimilationsprozess, sondern ein wechselseitiger Transformationsprozess, der sowohl Zuwanderern als auch der Aufnahmegesellschaft Veränderungsbereitschaft und interkulturelle Kompetenz abverlangt.'}, answer:'d', evidence:'die gesamte Gesellschaft adressieren', vocab:[{word:'wechselseitig',type:'Adjektiv',meaning:'mutual/reciprocal'}] },
    ]
  },
]

async function main() {
  console.log('🚀 Seeding — Batch 6 (C1-T3-009 to 012)')
  for (const entry of batch) {
    const ex = await prisma.readingExercise.findFirst({ where: { exerciseId: entry.exerciseId }, include: { questions: true } })
    if (!ex) { console.log(`⏭️ ${entry.exerciseId} not found`); continue }
    if (ex.questions.length > 0) { console.log(`⏭️ ${entry.exerciseId} already has questions`); continue }
    await prisma.readingExercise.update({ where: { id: ex.id }, data: { textsJson: entry.texts } })
    for (const q of entry.questions) {
      await prisma.readingQuestion.create({ data: {
        exerciseId: ex.id, questionNumber: q.n, questionType: 'lueckentext', linkedText: 'TextA',
        statement: `Welcher Satz passt in Lücke ${q.n}?`, options: q.opts, correctAnswer: q.answer, points: 1, sortOrder: q.n,
        explanation: { reasoning: `Der Satz passt inhaltlich und logisch in den Kontext.`, key_evidence: q.evidence, key_vocabulary: q.vocab }
      }})
    }
    console.log(`✅ ${entry.exerciseId} — ${entry.texts[0].title}`)
  }
  console.log('🎉 Batch 6 complete!')
}
main().catch(console.error).finally(() => prisma.$disconnect())
