import { PrismaClient } from '../apps/web/generated/prisma'
const prisma = new PrismaClient()
const batch = [
  { exerciseId: 'C2-T2-009', texts: [{ id: 'TextA', type: 'sachtext', title: 'Autonomie, Fürsorge und die Grenzen ärztlichen Handelns', content: 'Die Medizinethik steht an der Schnittstelle zwischen individueller Patientenautonomie und ärztlicher Fürsorgepflicht. ___(1)___ Die Debatte um Sterbehilfe verdeutlicht dieses Spannungsfeld. ___(2)___ Organtransplantation wirft Verteilungsgerechtigkeitsfragen auf. ___(3)___ Pränataldiagnostik stellt werdende Eltern vor schwere Entscheidungen. ___(4)___ Genetische Eingriffe in die Keimbahn berühren die Identität künftiger Generationen. ___(5)___ Die Ressourcenallokation im Gesundheitswesen ist ein zentrales ethisches Problem. ___(6)___ Die Kommerzialisierung der Medizin gefährdet den hippokratischen Ethos. ___(7)___ Eine zeitgemäße Medizinethik muss die Vielfalt kultureller Wertvorstellungen berücksichtigen. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Das seit Beauchamp und Childress kanonische Vier-Prinzipien-Modell — Autonomie, Benefizienz, Nonmalefizienz und Gerechtigkeit — bildet den normativ-analytischen Rahmen, an dem sich klinische Entscheidungen orientieren, ohne die Komplexität konkreter Fälle vollständig einfangen zu können.',b:'Ärzte helfen Menschen.',c:'Die Medizin hat sich verändert.',d:'Ethik ist wichtig in der Medizin.'}, answer:'a', evidence:'Patientenautonomie und Fürsorgepflicht', vocab:[{word:'Benefizienz',type:'Nomen',meaning:'beneficence'}] },
      { n:2, opts:{a:'Sterbehilfe ist in einigen Ländern legal.',b:'Wenn ein urteilsfähiger Patient die Beendigung seines Lebens wünscht und die medizinische Profession zwischen der Achtung seiner Selbstbestimmung und dem ärztlichen Gebot des Nicht-Schadens zerrissen wird, kollidieren zwei konstitutive Prinzipien der Medizinethik unauflösbar.',c:'Jeder Mensch hat ein Recht auf Würde.',d:'Die Palliativmedizin bietet Alternativen.'}, answer:'b', evidence:'Sterbehilfe verdeutlicht dieses Spannungsfeld', vocab:[{word:'Selbstbestimmung',type:'Nomen',meaning:'self-determination'}] },
      { n:3, opts:{a:'Organe sind knapp.',b:'Die Wartelisten sind lang.',c:'Viele Menschen sterben beim Warten.',d:'Die Entscheidung, welcher Patient ein lebensrettendes Organ erhält und welcher auf der Warteliste verbleibt, zwingt zur Explizitmachung von Bewertungskriterien menschlichen Lebens, die in einer pluralistischen Gesellschaft niemals vollständig konsensfähig sind.'}, answer:'d', evidence:'Verteilungsgerechtigkeitsfragen', vocab:[{word:'Explizitmachung',type:'Nomen',meaning:'making explicit'}] },
      { n:4, opts:{a:'Die vorgeburtliche Diagnostik genetischer Abweichungen erzeugt einen Entscheidungsdruck, der die Grenze zwischen therapeutischer Prävention und eugenischer Selektion verschwimmen lässt und die gesellschaftliche Akzeptanz von Behinderung implizit untergräbt.',b:'Die Technologie ermöglicht vieles.',c:'Eltern wollen gesunde Kinder.',d:'Die Tests sind zuverlässig.'}, answer:'a', evidence:'Pränataldiagnostik stellt vor schwere Entscheidungen', vocab:[{word:'eugenisch',type:'Adjektiv',meaning:'eugenic'}] },
      { n:5, opts:{a:'CRISPR ist eine revolutionäre Technologie.',b:'Gentechnik ist umstritten.',c:'Die irreversible Modifikation des menschlichen Erbguts, die nicht den behandelten Individuen, sondern deren Nachkommen zugute käme und deren Einwilligung prinzipiell nicht eingeholt werden kann, stellt das Paradigma der informierten Zustimmung vor eine konzeptionelle Unmöglichkeit.',d:'Die Forschung schreitet voran.'}, answer:'c', evidence:'Identität künftiger Generationen', vocab:[{word:'Keimbahntherapie',type:'Nomen',meaning:'germline therapy'}] },
      { n:6, opts:{a:'Das Gesundheitssystem ist teuer.',b:'Die Kosten steigen.',c:'Die unvermeidliche Rationierung medizinischer Leistungen — ob implizit durch Budgetierungen oder explizit durch Kosten-Nutzen-Analysen wie QALYs — erzwingt tragische Entscheidungen, die demokratisch legitimiert und transparent kommuniziert werden müssen.',d:'Nicht jeder bekommt die beste Behandlung.'}, answer:'c', evidence:'Ressourcenallokation', vocab:[{word:'QALY',type:'Nomen',meaning:'quality-adjusted life year'}] },
      { n:7, opts:{a:'Wenn Gesundheit zur Ware und der Patient zum Kunden wird, transformiert sich das Arzt-Patienten-Verhältnis von einer treuhänderischen Beziehung zu einer kommerziellen Transaktion, in der die asymmetrische Verwundbarkeit des Kranken ökonomisch ausgebeutet zu werden droht.',b:'Krankenhäuser müssen Gewinn machen.',c:'Die Pharmaindustrie ist mächtig.',d:'Ärzte verdienen viel Geld.'}, answer:'a', evidence:'Kommerzialisierung gefährdet hippokratischen Ethos', vocab:[{word:'treuhänderisch',type:'Adjektiv',meaning:'fiduciary'}] },
      { n:8, opts:{a:'Die Welt ist vielfältig.',b:'Jede Kultur hat andere Werte.',c:'Toleranz ist wichtig.',d:'Die westlich-liberale Privilegierung individueller Autonomie ist keine universelle Selbstverständlichkeit; in vielen Kulturen sind familiale, kommunitäre oder religiöse Entscheidungsstrukturen mindestens gleichrangig, was eine kontextsensible Anwendung bioethischer Prinzipien erfordert.'}, answer:'d', evidence:'Vielfalt kultureller Wertvorstellungen', vocab:[{word:'kommunitär',type:'Adjektiv',meaning:'communitarian'}] },
    ]
  },
  { exerciseId: 'C2-T2-010', texts: [{ id: 'TextA', type: 'sachtext', title: 'Digitale Methoden und geisteswissenschaftliche Erkenntnis', content: 'Die Digitalen Geisteswissenschaften (Digital Humanities) markieren eine epistemologische Wende in den Kultur- und Textwissenschaften. ___(1)___ Distant Reading als methodischer Ansatz hat die Literaturwissenschaft herausgefordert. ___(2)___ Die Digitalisierung kulturellen Erbes ermöglicht neue Zugänge. ___(3)___ Digitale Editionswissenschaft transformiert die Textphilologie. ___(4)___ Die Frage nach dem hermeneutischen Status computergenerierter Ergebnisse ist methodologisch zentral. ___(5)___ Datenvisualisierung eröffnet neue Erkenntnismöglichkeiten. ___(6)___ Die digitale Transformation der Geisteswissenschaften birgt auch Risiken. ___(7)___ Die Zukunft der Digital Humanities liegt in der produktiven Spannung zwischen algorithmischer Analyse und hermeneutischer Interpretation. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Computer werden in der Forschung eingesetzt.',b:'Die Anwendung computationeller Methoden — von Text Mining über Netzwerkanalyse bis zu maschinellem Lernen — auf geisteswissenschaftliche Gegenstände verspricht nicht nur quantitative Skalierung, sondern potenziell qualitativ neue Einsichten in kulturelle Muster.',c:'Die Geisteswissenschaften verändern sich.',d:'Software ist nützlich für die Forschung.'}, answer:'b', evidence:'epistemologische Wende', vocab:[{word:'Text Mining',type:'Nomen',meaning:'text mining'}] },
      { n:2, opts:{a:'Man kann viele Bücher gleichzeitig lesen.',b:'Franco Morettis Konzept, statt einzelner kanonischer Werke Tausende von Texten algorithmisch zu analysieren, durchbricht die hermeneutische Tradition der Einzeltextlektüre und ermöglicht die Identifikation makrostruktureller Entwicklungen im Literatursystem.',c:'Moretti ist ein italienischer Literaturwissenschaftler.',d:'Close Reading ist die traditionelle Methode.'}, answer:'b', evidence:'Distant Reading', vocab:[{word:'makrostrukturell',type:'Adjektiv',meaning:'macrostructural'}] },
      { n:3, opts:{a:'Museen digitalisieren ihre Bestände.',b:'Archive sind online zugänglich.',c:'Die hochauflösende Digitalisierung von Manuskripten, Kunstwerken, archäologischen Artefakten und historischen Quellen demokratisiert den Forschungszugang, ermöglicht nicht-invasive Analysen und schafft die Grundlage für maschinenlesbare Korpora von bisher unerreichtem Umfang.',d:'Alles wird digital.'}, answer:'c', evidence:'Digitalisierung kulturellen Erbes', vocab:[{word:'Korpus',type:'Nomen',meaning:'corpus'}] },
      { n:4, opts:{a:'Texte werden digital editiert.',b:'Digitale Editionen bieten viele Vorteile.',c:'Die Möglichkeit, Textvarianten, Kommentare, Übersetzungen und Kontextmaterialien in dynamisch verlinkten, beliebig erweiterbaren digitalen Editionen zu präsentieren, sprengt die Linearität des gedruckten Buchs und eröffnet multidimensionale Lektürepfade.',d:'XML und TEI sind wichtige Standards.'}, answer:'c', evidence:'transformiert die Textphilologie', vocab:[{word:'Lektürepfad',type:'Nomen',meaning:'reading path'}] },
      { n:5, opts:{a:'Algorithmen haben keine Meinung.',b:'Die Frage, ob eine statistisch identifizierte Korrelation — etwa ein Themencluster in 50.000 Romanen — interpretative Aussagekraft besitzt oder lediglich ein methodisches Artefakt darstellt, erfordert eine Reflexion über den epistemischen Status datengetriebener Befunde.',c:'Korrelation ist nicht Kausalität.',d:'Computer machen keine Fehler.'}, answer:'b', evidence:'hermeneutischen Status computergenerierter Ergebnisse', vocab:[{word:'epistemischer Status',type:'Nomen',meaning:'epistemic status'}] },
      { n:6, opts:{a:'Diagramme sind informativ.',b:'Graphen zeigen Zusammenhänge.',c:'Die kartographische, netzwerkanalytische oder chronologische Visualisierung großer Datenmengen macht unsichtbare Strukturen sichtbar und erzeugt visuelle Evidenz, die sowohl heuristisch produktiv als auch epistemisch trügerisch sein kann.',d:'Bilder sagen mehr als tausend Worte.'}, answer:'c', evidence:'Datenvisualisierung eröffnet neue Erkenntnismöglichkeiten', vocab:[{word:'heuristisch',type:'Adjektiv',meaning:'heuristic'}] },
      { n:7, opts:{a:'Die Gefahr besteht, dass die Faszination für technische Machbarkeit und die Verfügbarkeit großer Datensätze zu einer Verengung der Forschungsfragen auf das Quantifizierbare führt und die genuin geisteswissenschaftliche Kompetenz der differenzierten Einzelfallanalyse marginalisiert.',b:'Nicht alles lässt sich digitalisieren.',c:'Manche Forscher lehnen Computer ab.',d:'Die Technik hat Grenzen.'}, answer:'a', evidence:'birgt auch Risiken', vocab:[{word:'marginalisieren',type:'Verb',meaning:'to marginalize'}] },
      { n:8, opts:{a:'Beide Ansätze sind wichtig.',b:'Die Zukunft wird es zeigen.',c:'Technologie und Tradition müssen zusammenwirken.',d:'Erst wenn algorithmische Musterkennung und interpretative Sinnstiftung nicht als konkurrierende, sondern als komplementäre Erkenntnismodi begriffen werden, kann die digitale Transformation den Geisteswissenschaften neue Forschungshorizonte erschließen, ohne deren Kernkompetenz preiszugeben.'}, answer:'d', evidence:'produktiven Spannung zwischen algorithmischer Analyse und hermeneutischer Interpretation', vocab:[{word:'Erkenntnismodus',type:'Nomen',meaning:'mode of knowledge'}] },
    ]
  },
  { exerciseId: 'C2-T2-011', texts: [{ id: 'TextA', type: 'sachtext', title: 'Religiöse Pluralität und interreligiöser Dialog', content: 'Die vergleichende Religionswissenschaft untersucht religiöse Traditionen in ihrer kulturellen, historischen und phänomenologischen Vielfalt. ___(1)___ Der interreligiöse Dialog steht vor grundlegenden epistemologischen Herausforderungen. ___(2)___ Säkularisierungstheorien sind in ihrer universellen Gültigkeit umstritten. ___(3)___ Fundamentalistische Bewegungen instrumentalisieren Religion für politische Zwecke. ___(4)___ Religionsfreiheit als Menschenrecht schützt individuelle und kollektive Praxis. ___(5)___ Die Unterscheidung zwischen Religion und Spiritualität gewinnt gesellschaftlich an Bedeutung. ___(6)___ Religion und Gewalt stehen in einem komplexen Verhältnis. ___(7)___ Eine zukunftsfähige Religionswissenschaft muss ihre eigenen kategorialen Voraussetzungen kritisch reflektieren. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Es gibt viele Religionen.',b:'Religion ist ein universelles Phänomen.',c:'Ihr methodischer Anspruch auf Neutralität und Empathie — das von Ninian Smart geforderte „methodische Agnostizismus" — unterscheidet sie von der Theologie, die stets innerhalb eines spezifischen Glaubenshorizonts argumentiert.',d:'Die Religionswissenschaft ist ein akademisches Fach.'}, answer:'c', evidence:'kulturellen, historischen und phänomenologischen Vielfalt', vocab:[{word:'methodischer Agnostizismus',type:'Nomen',meaning:'methodological agnosticism'}] },
      { n:2, opts:{a:'Die Frage, ob ein verstehender Zugang zu einer fremden religiösen Tradition möglich ist, ohne deren Wahrheitsansprüche zu teilen, und ob die dabei verwendeten Kategorien nicht ihrerseits kulturell kontingent sind, durchzieht die gesamte Disziplingeschichte.',b:'Dialog ist wichtig.',c:'Religionen sollten zusammenarbeiten.',d:'Es gibt viele Gemeinsamkeiten.'}, answer:'a', evidence:'epistemologischen Herausforderungen', vocab:[{word:'kulturell kontingent',type:'Adjektiv',meaning:'culturally contingent'}] },
      { n:3, opts:{a:'Die Annahme eines linearen Zusammenhangs zwischen Modernisierung und Religionsverlust, wie sie von Max Weber bis Peter Berger vertreten wurde, hat sich angesichts der globalen Revitalisierung religiöser Identitäten als eurozentrischer Sonderweg herausgestellt.',b:'Weniger Menschen gehen in die Kirche.',c:'Religion ist rückläufig.',d:'Die Aufklärung hat die Religion geschwächt.'}, answer:'a', evidence:'Säkularisierungstheorien umstritten', vocab:[{word:'Revitalisierung',type:'Nomen',meaning:'revitalization'}] },
      { n:4, opts:{a:'Fundamentalismus ist gefährlich.',b:'Terrorismus hat viele Ursachen.',c:'Die selektive Verabsolutierung einzelner Textpassagen, die Konstruktion einer idealisierten Vergangenheit und die manichäische Freund-Feind-Unterscheidung bilden dabei ideologische Strategien, die religiöse Tradition für dezidiert moderne Herrschaftsinteressen funktionalisieren.',d:'Religion sollte friedlich sein.'}, answer:'c', evidence:'instrumentalisieren Religion für politische Zwecke', vocab:[{word:'manichäisch',type:'Adjektiv',meaning:'Manichaean'}] },
      { n:5, opts:{a:'Jeder darf glauben, was er will.',b:'Die Spannungsfelder zwischen individueller Glaubensfreiheit, kollektiven Religionsrechten, staatlicher Neutralität und der Schutzpflicht gegenüber Abtrünnigen und Nichtgläubigen erzeugen Konflikte, die in jeder Gesellschaft kontextspezifisch ausgehandelt werden müssen.',c:'Religionsfreiheit ist ein Grundrecht.',d:'Die Verfassung schützt die Religion.'}, answer:'b', evidence:'Religionsfreiheit als Menschenrecht', vocab:[{word:'Abtrünniger',type:'Nomen',meaning:'apostate'}] },
      { n:6, opts:{a:'Viele Menschen sind spirituell, aber nicht religiös.',b:'Yoga und Meditation sind populär.',c:'Die zunehmende Entkoppelung subjektiver Transzendenzerfahrungen von institutionellen Zugehörigkeiten — das Phänomen der „believing without belonging" — stellt nicht nur die organisierte Religion, sondern auch die religionswissenschaftliche Begriffsbildung vor konzeptionelle Herausforderungen.',d:'Kirchen verlieren Mitglieder.'}, answer:'c', evidence:'Unterscheidung zwischen Religion und Spiritualität', vocab:[{word:'Transzendenzerfahrung',type:'Nomen',meaning:'experience of transcendence'}] },
      { n:7, opts:{a:'Religionskriege gab es immer.',b:'Gewalt ist nie gerechtfertigt.',c:'Weder die apologetische Behauptung, religiöse Gewalt sei stets Missbrauch, noch die reduktionistische These, Religion sei intrinsisch gewalttätig, werden der ambivalenten Rolle gerecht, die sakrale Symbolik, eschatologische Erwartungen und moralische Absoluta in der Legitimation und Delegitimation von Gewalt spielen.',d:'Der Islam ist keine gewalttätige Religion.'}, answer:'c', evidence:'Religion und Gewalt in einem komplexen Verhältnis', vocab:[{word:'eschatologisch',type:'Adjektiv',meaning:'eschatological'}] },
      { n:8, opts:{a:'Die Wissenschaft muss neutral bleiben.',b:'Objektivität ist unmöglich.',c:'Forschung muss ehrlich sein.',d:'Die Einsicht, dass der westlich geprägte Religionsbegriff selbst — mit seiner Privilegierung von Glaubensinhalten, Textualität und institutioneller Organisation — die Vielfalt religiöser Phänomene systematisch verzerrt, erfordert eine De-Provinzialisierung der theoretischen Grundlagen.'}, answer:'d', evidence:'kategoriale Voraussetzungen kritisch reflektieren', vocab:[{word:'De-Provinzialisierung',type:'Nomen',meaning:'de-provincialization'}] },
    ]
  },
  { exerciseId: 'C2-T2-012', texts: [{ id: 'TextA', type: 'sachtext', title: 'Bewusstsein, Kognition und die Grenzen der Naturalisierung', content: 'Die Kognitionswissenschaft versucht, die Mechanismen des Geistes durch die Integration von Psychologie, Neurowissenschaft, Linguistik und KI-Forschung zu erklären. ___(1)___ Das Bewusstseinsproblem bildet die größte Herausforderung. ___(2)___ Embodied Cognition hat den klassischen Kognitivismus herausgefordert. ___(3)___ Die Erforschung des Gedächtnisses verbindet neurowissenschaftliche und psychologische Perspektiven. ___(4)___ Emotionen werden nicht mehr als Störung, sondern als konstitutiv für rationales Denken betrachtet. ___(5)___ Die Frage der Willensfreiheit wird durch neurowissenschaftliche Befunde neu verhandelt. ___(6)___ Künstliche Intelligenz dient der Kognitionswissenschaft als Modell und Prüfstein. ___(7)___ Eine angemessene Theorie des Geistes muss die irreduzible Subjektivität der Erfahrung berücksichtigen. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Das Gehirn ist komplex.',b:'Die Kognitionswissenschaft ist interdisziplinär.',c:'Dieses seit den 1950er-Jahren verfolgte Projekt der Naturalisierung des Geistes — die Erklärung mentaler Phänomene in den Begriffen der Naturwissenschaft — hat beeindruckende Erfolge erzielt, stößt aber an prinzipielle Grenzen, die das Verhältnis von Erklären und Verstehen betreffen.',d:'Viele Wissenschaftler arbeiten zusammen.'}, answer:'c', evidence:'Mechanismen des Geistes', vocab:[{word:'Naturalisierung',type:'Nomen',meaning:'naturalization'}] },
      { n:2, opts:{a:'David Chalmers\' Unterscheidung zwischen dem „leichten Problem" funktionaler Erklärungen und dem „harten Problem" der subjektiven Erlebnisqualität (Qualia) hat verdeutlicht, dass die neuronale Korrelation von Bewusstseinszuständen nicht mit deren Erklärung gleichgesetzt werden darf.',b:'Bewusstsein ist schwer zu definieren.',c:'Wir wissen wenig über das Gehirn.',d:'Das Bewusstsein ist ein Rätsel.'}, answer:'a', evidence:'Bewusstseinsproblem', vocab:[{word:'Qualia',type:'Nomen',meaning:'qualia'}] },
      { n:3, opts:{a:'Denken geschieht nicht nur im Kopf.',b:'Die These, dass Kognition nicht auf interne Symbolverarbeitung reduzierbar ist, sondern wesentlich durch die leibliche Verfasstheit des Organismus, seine sensomotorische Interaktion mit der Umwelt und die kulturelle Einbettung seiner Praxis konstituiert wird, untergräbt die computationelle Metapher.',c:'Roboter können gehen lernen.',d:'Der Körper ist wichtig für das Denken.'}, answer:'b', evidence:'Embodied Cognition', vocab:[{word:'computationelle Metapher',type:'Nomen',meaning:'computational metaphor'}] },
      { n:4, opts:{a:'Das Gedächtnis ist nicht perfekt.',b:'Erinnerungen können trügen.',c:'Die Entdeckung, dass Erinnerungen keine stabilen Repräsentationen, sondern bei jedem Abruf aktiv rekonstruierte Prozesse sind, deren neuronale Substrate sich dynamisch reorganisieren, hat die naive Speichermetapher des Gedächtnisses obsolet gemacht.',d:'Es gibt verschiedene Gedächtnisarten.'}, answer:'c', evidence:'Erforschung des Gedächtnisses', vocab:[{word:'Speichermetapher',type:'Nomen',meaning:'storage metaphor'}] },
      { n:5, opts:{a:'Emotionen sind wichtig.',b:'António Damásios Forschung zu Patienten mit Frontalhirnläsionen hat gezeigt, dass der Verlust emotionaler Bewertungsfähigkeit die rationale Entscheidungsfindung nicht verbessert, sondern massiv beeinträchtigt — ein Befund, der die cartesianische Trennung von Vernunft und Gefühl empirisch widerlegt.',c:'Gefühle beeinflussen Entscheidungen.',d:'Wut ist ein schlechter Ratgeber.'}, answer:'b', evidence:'Emotionen konstitutiv für rationales Denken', vocab:[{word:'cartesianisch',type:'Adjektiv',meaning:'Cartesian'}] },
      { n:6, opts:{a:'Unser Wille ist nicht frei.',b:'Benjamin Libets Experimente scheinen zu zeigen, dass das Bereitschaftspotenzial der bewussten Willensintention vorausgeht; die philosophische Tragweite dieses Befunds bleibt jedoch umstritten, da die Gleichsetzung einer neuronalen Signatur mit einer „Entscheidung" begriffliche Konfusionen enthält.',c:'Das Gehirn entscheidet vor uns.',d:'Die Neurowissenschaft kann alles erklären.'}, answer:'b', evidence:'Willensfreiheit wird neu verhandelt', vocab:[{word:'Bereitschaftspotenzial',type:'Nomen',meaning:'readiness potential'}] },
      { n:7, opts:{a:'KI wird immer intelligenter.',b:'Computer können Schach spielen.',c:'Die Tatsache, dass Large Language Models menschenähnliche Texte produzieren, ohne über Intentionalität, Bewusstsein oder Weltwissen zu verfügen, wirft die Frage auf, ob menschliche Kognition tatsächlich computationell modellierbar ist oder ob die Simulation intelligenten Verhaltens grundsätzlich von seiner Realisation zu unterscheiden bleibt.',d:'Roboter werden keine Gefühle haben.'}, answer:'c', evidence:'KI als Modell und Prüfstein', vocab:[{word:'Intentionalität',type:'Nomen',meaning:'intentionality'}] },
      { n:8, opts:{a:'Es gibt noch viel zu erforschen.',b:'Das Bewusstsein bleibt ein Rätsel.',c:'Die Naturwissenschaft wird die Antwort finden.',d:'Thomas Nagels Frage „What is it like to be a bat?" verweist auf die unhintergehbare Perspektivität bewusster Erfahrung, die sich möglicherweise einer vollständigen objektivierenden Beschreibung prinzipiell entzieht und die Grenzen des naturwissenschaftlichen Erklärungsanspruchs markiert.'}, answer:'d', evidence:'irreduzible Subjektivität der Erfahrung', vocab:[{word:'Perspektivität',type:'Nomen',meaning:'perspectivity'}] },
    ]
  },
]

async function main() {
  console.log('🚀 Seeding — Batch 9 FINAL (C2-T2-009 to 012)')
  for (const entry of batch) {
    const ex = await prisma.readingExercise.findFirst({ where: { exerciseId: entry.exerciseId }, include: { questions: true } })
    if (!ex) { console.log(`⏭️ ${entry.exerciseId} not found`); continue }
    if (ex.questions.length > 0) { console.log(`⏭️ ${entry.exerciseId} already has questions`); continue }
    await prisma.readingExercise.update({ where: { id: ex.id }, data: { textsJson: entry.texts } })
    for (const q of entry.questions) {
      await prisma.readingQuestion.create({ data: {
        exerciseId: ex.id, questionNumber: q.n, questionType: 'lueckentext', linkedText: 'TextA',
        statement: `Welcher Textabschnitt passt in Lücke ${q.n}?`, options: q.opts, correctAnswer: q.answer, points: 1, sortOrder: q.n,
        explanation: { reasoning: 'Der Textabschnitt fügt sich inhaltlich und argumentativ kohärent in den Kontext ein.', key_evidence: q.evidence, key_vocabulary: q.vocab }
      }})
    }
    console.log(`✅ ${entry.exerciseId} — ${entry.texts[0].title}`)
  }
  console.log('🎉 Batch 9 FINAL complete! All 36 exercises seeded!')
}
main().catch(console.error).finally(() => prisma.$disconnect())
