import { PrismaClient } from '../apps/web/generated/prisma'
const prisma = new PrismaClient()

const batch = [
  {
    exerciseId: 'C1-T3-001',
    texts: [{ id: 'TextA', type: 'sachtext', title: 'Moralphilosophie und künstliche Entscheidungssysteme',
      content: 'Die Frage, ob Maschinen moralisch handeln können, beschäftigt Philosophen seit Jahrzehnten. ___(1)___ Dabei geht es nicht nur um die technische Machbarkeit, sondern um grundsätzliche Fragen des Menschseins. ___(2)___ Besonders kontrovers wird die Debatte, wenn es um autonome Waffensysteme geht. ___(3)___ Befürworter argumentieren, dass algorithmenbasierte Entscheidungen weniger fehleranfällig seien als menschliche Urteile unter Stress. ___(4)___ Kritiker hingegen verweisen auf die Unersetzbarkeit moralischer Intuition. ___(5)___ In der medizinischen Ethik stellen sich ähnliche Fragen, etwa bei der Verteilung knapper Ressourcen. ___(6)___ Die philosophische Tradition bietet verschiedene Ansätze zur Lösung solcher Dilemmata. ___(7)___ Letztlich bleibt die Frage offen, ob ethisches Handeln ohne Bewusstsein überhaupt möglich ist. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Bereits Aristoteles hat auf die Bedeutung der Phronesis, der praktischen Klugheit, hingewiesen.',b:'Die technische Entwicklung schreitet unaufhaltsam voran.',c:'Computer werden immer leistungsfähiger.',d:'Die Philosophie hat darauf keine Antwort.'}, answer:'a', evidence:'Die Frage, ob Maschinen moralisch handeln können', vocab:[{word:'Phronesis',type:'Nomen',meaning:'practical wisdom'}] },
      { n:2, opts:{a:'Die Wirtschaft profitiert von diesen Entwicklungen.',b:'Insbesondere die Unterscheidung zwischen regelbasierter und tugendethischer Moral spielt eine zentrale Rolle.',c:'Die Technologie ist noch nicht ausgereift.',d:'Niemand interessiert sich für diese Debatte.'}, answer:'b', evidence:'grundsätzliche Fragen des Menschseins', vocab:[{word:'Tugendethik',type:'Nomen',meaning:'virtue ethics'}] },
      { n:3, opts:{a:'Hier stoßen utilitaristische und deontologische Perspektiven besonders hart aufeinander.',b:'Autonome Waffen sind bereits im Einsatz.',c:'Die Vereinten Nationen haben dies bereits verboten.',d:'Militärexperten lehnen autonome Systeme grundsätzlich ab.'}, answer:'a', evidence:'autonome Waffensysteme', vocab:[{word:'deontologisch',type:'Adjektiv',meaning:'deontological'}] },
      { n:4, opts:{a:'Die Kosten solcher Systeme sind erheblich.',b:'Dies trifft jedoch nur auf klar definierte Szenarien zu, in denen moralische Ambiguität gering ist.',c:'Alle Menschen machen Fehler.',d:'Die Forschung steht noch am Anfang.'}, answer:'b', evidence:'algorithmenbasierte Entscheidungen weniger fehleranfällig', vocab:[{word:'Ambiguität',type:'Nomen',meaning:'ambiguity'}] },
      { n:5, opts:{a:'Die Industrie investiert weiterhin in diese Technologien.',b:'Roboter werden niemals Gefühle haben.',c:'Gerade die Fähigkeit zur Empathie und zum Perspektivwechsel unterscheide den Menschen fundamental von der Maschine.',d:'Die Debatte wird in den Medien kaum beachtet.'}, answer:'c', evidence:'Unersetzbarkeit moralischer Intuition', vocab:[{word:'Empathie',type:'Nomen',meaning:'empathy'}] },
      { n:6, opts:{a:'Die Kosten im Gesundheitswesen steigen stetig.',b:'Hier zeigt sich besonders deutlich, dass rein quantitative Modelle der Komplexität ethischer Entscheidungen nicht gerecht werden.',c:'Ärzte lehnen technische Hilfsmittel ab.',d:'Patienten wünschen sich mehr Technologie.'}, answer:'b', evidence:'Verteilung knapper Ressourcen', vocab:[{word:'quantitativ',type:'Adjektiv',meaning:'quantitative'}] },
      { n:7, opts:{a:'Der Utilitarismus etwa fordert die Maximierung des Gesamtnutzens, während Kants kategorischer Imperativ auf universalisierbare Handlungsmaximen abzielt.',b:'Die Philosophie ist eine alte Wissenschaft.',c:'Es gibt keine einfachen Lösungen.',d:'Die meisten Menschen kennen diese Ansätze nicht.'}, answer:'a', evidence:'verschiedene Ansätze zur Lösung solcher Dilemmata', vocab:[{word:'kategorischer Imperativ',type:'Nomen',meaning:'categorical imperative'}] },
      { n:8, opts:{a:'Die Zukunft wird es zeigen.',b:'Diese Debatte wird noch lange andauern.',c:'Dies verweist auf das fundamentale Qualia-Problem der Philosophie des Geistes und die ungeklärte Beziehung zwischen Intentionalität und moralischer Handlungsfähigkeit.',d:'Die Technik wird diese Fragen lösen.'}, answer:'c', evidence:'ethisches Handeln ohne Bewusstsein', vocab:[{word:'Qualia',type:'Nomen',meaning:'subjective experience'}] },
    ]
  },
  {
    exerciseId: 'C1-T3-002',
    texts: [{ id: 'TextA', type: 'sachtext', title: 'Strukturwandel in der globalen Finanzarchitektur',
      content: 'Die internationale Finanzarchitektur befindet sich in einem tiefgreifenden Umbruch. ___(1)___ Traditionelle Institutionen wie der IWF und die Weltbank sehen sich zunehmend mit Legitimationsfragen konfrontiert. ___(2)___ Der Aufstieg digitaler Währungen stellt die Zentralbanken vor völlig neue Herausforderungen. ___(3)___ Gleichzeitig wächst die Erkenntnis, dass rein marktbasierte Regulierungsmechanismen versagen können. ___(4)___ Die Finanzkrise von 2008 hat diese Schwächen schonungslos offengelegt. ___(5)___ Seither wird intensiv über alternative Governance-Modelle diskutiert. ___(6)___ Besonders die Schwellenländer fordern eine stärkere Beteiligung an internationalen Entscheidungsprozessen. ___(7)___ Die Zukunft des internationalen Finanzsystems hängt maßgeblich davon ab, ob ein gerechter Interessenausgleich gelingen kann. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Insbesondere die zunehmende Verflechtung der Kapitalmärkte und die Geschwindigkeit grenzüberschreitender Transaktionen erfordern neue Steuerungsinstrumente.',b:'Die Börsen sind volatil.',c:'Investoren sind verunsichert.',d:'Die Zinsen bleiben niedrig.'}, answer:'a', evidence:'tiefgreifenden Umbruch', vocab:[{word:'Verflechtung',type:'Nomen',meaning:'interconnection'}] },
      { n:2, opts:{a:'Ihre Kreditprogramme helfen vielen Ländern.',b:'Dies liegt vor allem daran, dass ihre Entscheidungsstrukturen die geopolitischen Machtverhältnisse der Nachkriegszeit widerspiegeln.',c:'Der IWF wurde 1944 gegründet.',d:'Beide Institutionen haben ihren Sitz in Washington.'}, answer:'b', evidence:'Legitimationsfragen', vocab:[{word:'Machtverhältnisse',type:'Nomen',meaning:'power relations'}] },
      { n:3, opts:{a:'Bitcoin wurde 2009 eingeführt.',b:'Viele Menschen nutzen bereits Kryptowährungen.',c:'Die potenzielle Disintermediation des Bankensektors durch dezentrale Blockchain-Technologien könnte das Finanzsystem grundlegend transformieren.',d:'Digitale Währungen sind riskant.'}, answer:'c', evidence:'Der Aufstieg digitaler Währungen', vocab:[{word:'Disintermediation',type:'Nomen',meaning:'disintermediation'}] },
      { n:4, opts:{a:'Die Deregulierung der 1990er-Jahre hat systemische Risiken begünstigt, die durch nationale Aufsichtsbehörden allein nicht kontrollierbar sind.',b:'Märkte regulieren sich selbst.',c:'Banken sind gut reguliert.',d:'Die Regierungen haben kein Interesse an Regulierung.'}, answer:'a', evidence:'marktbasierte Regulierungsmechanismen versagen können', vocab:[{word:'Deregulierung',type:'Nomen',meaning:'deregulation'}] },
      { n:5, opts:{a:'Viele Banken mussten gerettet werden.',b:'Der Zusammenbruch von Lehman Brothers löste eine globale Rezession aus, deren sozialpolitische Folgen in vielen Ländern bis heute spürbar sind.',c:'Die Krise war schnell überwunden.',d:'Nur wenige Länder waren betroffen.'}, answer:'b', evidence:'Die Finanzkrise von 2008', vocab:[{word:'Rezession',type:'Nomen',meaning:'recession'}] },
      { n:6, opts:{a:'Einige Experten plädieren für eine stärkere Rolle supranationaler Instanzen, während andere auf subsidiäre Lösungsansätze setzen.',b:'Die Diskussionen führen zu nichts.',c:'Politiker sind sich einig.',d:'Es gibt keine Alternativen.'}, answer:'a', evidence:'alternative Governance-Modelle', vocab:[{word:'supranational',type:'Adjektiv',meaning:'supranational'}] },
      { n:7, opts:{a:'China und Indien sind große Volkswirtschaften.',b:'Ihre wachsende wirtschaftliche Bedeutung kontrastiert mit ihrer nach wie vor unterproportionalen Repräsentation in den Bretton-Woods-Institutionen.',c:'Sie möchten eigene Institutionen gründen.',d:'Die Schwellenländer sind hoch verschuldet.'}, answer:'b', evidence:'stärkere Beteiligung an internationalen Entscheidungsprozessen', vocab:[{word:'Repräsentation',type:'Nomen',meaning:'representation'}] },
      { n:8, opts:{a:'Die Zeit wird es zeigen.',b:'Die nächste Krise kommt bestimmt.',c:'Hierfür bedarf es nicht nur institutioneller Reformen, sondern auch eines Paradigmenwechsels hin zu einer Finanzordnung, die ökologische und soziale Nachhaltigkeit als gleichrangige Ziele verankert.',d:'Die Märkte werden es regeln.'}, answer:'c', evidence:'ob ein gerechter Interessenausgleich gelingen kann', vocab:[{word:'Paradigmenwechsel',type:'Nomen',meaning:'paradigm shift'}] },
    ]
  },
  {
    exerciseId: 'C1-T3-003',
    texts: [{ id: 'TextA', type: 'sachtext', title: 'Mehrsprachigkeit als literarisches Gestaltungsmittel',
      content: 'In der zeitgenössischen Literatur gewinnt Mehrsprachigkeit als bewusstes Stilmittel zunehmend an Bedeutung. ___(1)___ Autoren wie Yoko Tawada oder Herta Müller nutzen sprachliche Hybridität, um kulturelle Zwischenräume auszuloten. ___(2)___ Die Literaturwissenschaft steht dabei vor methodischen Herausforderungen. ___(3)___ Traditionelle Analysekategorien greifen bei mehrsprachigen Texten häufig zu kurz. ___(4)___ Die Übersetzbarkeit solcher Werke wird kontrovers diskutiert. ___(5)___ Befürworter der literarischen Mehrsprachigkeit sehen darin eine Bereicherung des sprachlichen Ausdrucksrepertoires. ___(6)___ Besonders in postkolonialen Kontexten dient der Sprachwechsel als Mittel der kulturellen Selbstbehauptung. ___(7)___ Die Zukunft der Weltliteratur liegt möglicherweise jenseits einsprachiger Konzepte. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Dies zeigt sich besonders in der sogenannten transkulturellen Literatur, die Sprachen nicht als getrennte Systeme, sondern als durchlässige Ausdrucksformen begreift.',b:'Viele Bücher werden in mehrere Sprachen übersetzt.',c:'Die deutsche Literatur hat eine lange Tradition.',d:'Bestsellerlisten spiegeln diesen Trend nicht wider.'}, answer:'a', evidence:'Mehrsprachigkeit als bewusstes Stilmittel', vocab:[{word:'transkulturell',type:'Adjektiv',meaning:'transcultural'}] },
      { n:2, opts:{a:'Beide Autorinnen haben den Nobelpreis erhalten.',b:'Durch den gezielten Einsatz von Interferenzen, Code-Switching und semantischen Verschiebungen erzeugen sie eine poetische Fremdheit, die monolinguale Texte nicht erreichen können.',c:'Ihre Bücher sind schwer zu lesen.',d:'Sie schreiben hauptsächlich auf Deutsch.'}, answer:'b', evidence:'sprachliche Hybridität', vocab:[{word:'Code-Switching',type:'Nomen',meaning:'code-switching'}] },
      { n:3, opts:{a:'Insbesondere die Frage, welche Sprache als Referenzsystem dient und wie die Wechselwirkungen zwischen den eingesetzten Sprachen zu analysieren sind, erfordert neue theoretische Rahmenwerke.',b:'Es gibt viele Literaturtheorien.',c:'Die Wissenschaft ist sich uneinig.',d:'Germanisten ignorieren dieses Phänomen.'}, answer:'a', evidence:'methodischen Herausforderungen', vocab:[{word:'Rahmenwerk',type:'Nomen',meaning:'framework'}] },
      { n:4, opts:{a:'Die Texte sind oft experimentell.',b:'Sowohl die auf Einzelsprachen ausgerichtete Stilistik als auch die komparatistische Methodik müssen erweitert werden, um der sprachlichen Polyphonie gerecht zu werden.',c:'Die Leser verstehen diese Texte nicht.',d:'Verlage lehnen solche Manuskripte ab.'}, answer:'b', evidence:'Traditionelle Analysekategorien greifen häufig zu kurz', vocab:[{word:'Polyphonie',type:'Nomen',meaning:'polyphony'}] },
      { n:5, opts:{a:'Einige Übersetzer argumentieren, dass gerade das Unübersetzbare den ästhetischen Kern mehrsprachiger Literatur ausmache und durch jede Übertragung unweigerlich verloren gehe.',b:'Übersetzer verdienen zu wenig.',c:'Maschinelle Übersetzung wird immer besser.',d:'Alle Literatur lässt sich übersetzen.'}, answer:'a', evidence:'Die Übersetzbarkeit solcher Werke wird kontrovers diskutiert', vocab:[{word:'ästhetisch',type:'Adjektiv',meaning:'aesthetic'}] },
      { n:6, opts:{a:'Die Verschmelzung verschiedener Sprachregister ermöglicht es, Erfahrungen der Migration, des Exils und der kulturellen Doppelzugehörigkeit authentisch zu artikulieren.',b:'Sprachen sind grundsätzlich gleichwertig.',c:'Monolinguale Literatur ist weniger wertvoll.',d:'Die Globalisierung fördert die Einsprachigkeit.'}, answer:'a', evidence:'Bereicherung des sprachlichen Ausdrucksrepertoires', vocab:[{word:'Sprachregister',type:'Nomen',meaning:'language register'}] },
      { n:7, opts:{a:'Viele Autoren schreiben in der Sprache der ehemaligen Kolonialmacht.',b:'Indem Schriftsteller die dominante Sprache mit indigenen oder diasporischen Sprachmustern durchsetzen, unterlaufen sie hegemoniale Diskurse und schaffen Räume sprachlicher Widerständigkeit.',c:'Der Kolonialismus ist lange vorbei.',d:'Englisch ist die wichtigste Weltsprache.'}, answer:'b', evidence:'Sprachwechsel als Mittel der kulturellen Selbstbehauptung', vocab:[{word:'hegemonial',type:'Adjektiv',meaning:'hegemonic'}] },
      { n:8, opts:{a:'Die Zukunft wird es zeigen.',b:'Einsprachigkeit wird bestehen bleiben.',c:'Goethes Vision einer Weltliteratur könnte sich in einer Form verwirklichen, die er selbst nicht vorhergesehen hätte: als vielstimmiges, sprachlich hybrides Geflecht, das nationale Grenzen ebenso überschreitet wie sprachliche.',d:'Die nationale Literatur bleibt dominant.'}, answer:'c', evidence:'jenseits einsprachiger Konzepte', vocab:[{word:'Geflecht',type:'Nomen',meaning:'web/network'}] },
    ]
  },
  {
    exerciseId: 'C1-T3-004',
    texts: [{ id: 'TextA', type: 'sachtext', title: 'Urbane Resilienz und ökologische Stadtentwicklung',
      content: 'Moderne Städte stehen vor der Aufgabe, sich an die Folgen des Klimawandels anzupassen. ___(1)___ Das Konzept der urbanen Resilienz gewinnt dabei zunehmend an Bedeutung. ___(2)___ Architekten und Stadtplaner entwickeln neue Ansätze für eine klimagerechte Bauweise. ___(3)___ Dabei spielen Grünflächen eine zentrale Rolle für das Stadtklima. ___(4)___ Die soziale Dimension der Stadtentwicklung darf jedoch nicht vernachlässigt werden. ___(5)___ Partizipative Planungsprozesse können dazu beitragen, die Akzeptanz von Umbauprojekten zu erhöhen. ___(6)___ Die Frage der Finanzierung bleibt eine der größten Herausforderungen. ___(7)___ Die Stadt der Zukunft muss ökologisch, sozial und ökonomisch nachhaltig sein. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Hitzeperioden, Starkregenereignisse und der Anstieg des Meeresspiegels erfordern grundlegende Veränderungen in der städtischen Infrastruktur und Raumplanung.',b:'Städte wachsen immer schneller.',c:'Die Urbanisierung nimmt zu.',d:'Viele Menschen ziehen aufs Land.'}, answer:'a', evidence:'Folgen des Klimawandels', vocab:[{word:'Starkregenereignis',type:'Nomen',meaning:'heavy rainfall event'}] },
      { n:2, opts:{a:'Es wurde in den 1990er-Jahren entwickelt.',b:'Es beschreibt die Fähigkeit urbaner Systeme, auf Störungen flexibel zu reagieren, sich anzupassen und dabei ihre wesentlichen Funktionen aufrechtzuerhalten.',c:'Resilienz ist ein Modewort.',d:'Nur wenige Städte setzen dieses Konzept um.'}, answer:'b', evidence:'urbane Resilienz', vocab:[{word:'Resilienz',type:'Nomen',meaning:'resilience'}] },
      { n:3, opts:{a:'Dazu zählen etwa begrünte Fassaden, Schwammstadt-Konzepte zur dezentralen Regenwasserbewirtschaftung und die Verwendung wärmeregulierender Baumaterialien.',b:'Neue Gebäude sind teurer.',c:'Architekten bevorzugen Glas und Stahl.',d:'Die meisten Städte bauen konventionell.'}, answer:'a', evidence:'klimagerechte Bauweise', vocab:[{word:'Schwammstadt',type:'Nomen',meaning:'sponge city'}] },
      { n:4, opts:{a:'Parks sind wichtig für die Erholung.',b:'Bäume filtern die Luft.',c:'Sie fungieren als natürliche Kühlkörper, fördern die Biodiversität, dienen der Regenwasserretention und verbessern nachweislich die psychische Gesundheit der Stadtbewohner.',d:'Kinder spielen gerne im Grünen.'}, answer:'c', evidence:'Grünflächen eine zentrale Rolle für das Stadtklima', vocab:[{word:'Regenwasserretention',type:'Nomen',meaning:'rainwater retention'}] },
      { n:5, opts:{a:'Die Mieten steigen.',b:'Ökologische Umbaumaßnahmen dürfen nicht dazu führen, dass einkommensschwache Bevölkerungsgruppen durch steigende Wohnkosten aus ihren Vierteln verdrängt werden.',c:'Soziale Fragen sind weniger wichtig.',d:'Die Stadt gehört allen.'}, answer:'b', evidence:'Die soziale Dimension der Stadtentwicklung', vocab:[{word:'Verdrängung',type:'Nomen',meaning:'displacement'}] },
      { n:6, opts:{a:'Bürgerversammlungen finden regelmäßig statt.',b:'Demokratie ist wichtig.',c:'Wenn Anwohner frühzeitig in die Gestaltung ihres Lebensumfelds einbezogen werden, identifizieren sie sich stärker mit den Veränderungen und tragen aktiv zu deren Gelingen bei.',d:'Die meisten Bürger sind desinteressiert.'}, answer:'c', evidence:'Partizipative Planungsprozesse', vocab:[{word:'partizipativ',type:'Adjektiv',meaning:'participatory'}] },
      { n:7, opts:{a:'Innovative Finanzierungsmodelle wie Green Bonds, Public-Private-Partnerships und revolvierende Klimafonds bieten hier vielversprechende Möglichkeiten.',b:'Die Kommunen haben kein Geld.',c:'Die EU könnte helfen.',d:'Steuererhöhungen sind unvermeidlich.'}, answer:'a', evidence:'Die Frage der Finanzierung', vocab:[{word:'Green Bond',type:'Nomen',meaning:'green bond'}] },
      { n:8, opts:{a:'Die Zukunft wird es zeigen.',b:'Die Städte werden schrumpfen.',c:'Dies erfordert einen integrativen Planungsansatz, der Klimaschutz, soziale Gerechtigkeit und wirtschaftliche Wettbewerbsfähigkeit nicht als konkurrierende, sondern als sich gegenseitig verstärkende Ziele begreift.',d:'Technologie wird alle Probleme lösen.'}, answer:'c', evidence:'ökologisch, sozial und ökonomisch nachhaltig', vocab:[{word:'integrativ',type:'Adjektiv',meaning:'integrative'}] },
    ]
  },
]

async function main() {
  console.log('🚀 Seeding — Batch 4 (C1-T3-001 to 004)')
  for (const entry of batch) {
    const ex = await prisma.readingExercise.findFirst({ where: { exerciseId: entry.exerciseId }, include: { questions: true } })
    if (!ex) { console.log(`⏭️ ${entry.exerciseId} not found`); continue }
    if (ex.questions.length > 0) { console.log(`⏭️ ${entry.exerciseId} already has questions`); continue }
    await prisma.readingExercise.update({ where: { id: ex.id }, data: { textsJson: entry.texts } })
    for (const q of entry.questions) {
      await prisma.readingQuestion.create({ data: {
        exerciseId: ex.id, questionNumber: q.n, questionType: 'lueckentext', linkedText: 'TextA',
        statement: `Welcher Satz passt in Lücke ${q.n}?`, options: q.opts, correctAnswer: q.answer, points: 1, sortOrder: q.n,
        explanation: { reasoning: `Der Satz "${(q.opts as any)[q.answer].slice(0,60)}..." passt inhaltlich und logisch in den Kontext.`, key_evidence: q.evidence, key_vocabulary: q.vocab }
      }})
    }
    console.log(`✅ ${entry.exerciseId} — ${entry.texts[0].title}`)
  }
  console.log('🎉 Batch 4 complete!')
}
main().catch(console.error).finally(() => prisma.$disconnect())
