import { PrismaClient } from '../apps/web/generated/prisma'
const prisma = new PrismaClient()

const batch = [
  {
    exerciseId: 'C2-T2-001',
    texts: [{ id: 'TextA', type: 'sachtext', title: 'Naturrecht und Rechtspositivismus: Eine ungelöste Kontroverse',
      content: 'Die Rechtsphilosophie ringt seit der Antike mit der Frage, ob das Recht eine überpositive moralische Grundlage besitzt oder ausschließlich als Produkt menschlicher Setzung zu verstehen ist. ___(1)___ Die naturrechtliche Tradition, die von den Stoikern über Thomas von Aquin bis zu den Menschenrechtserklärungen des 18. Jahrhunderts reicht, postuliert die Existenz universeller, vernunftbegründeter Rechtsprinzipien. ___(2)___ Der Rechtspositivismus, wie ihn Hans Kelsen und H.L.A. Hart paradigmatisch formuliert haben, trennt hingegen strikt zwischen Recht und Moral. ___(3)___ Die Erfahrung totalitärer Regime im 20. Jahrhundert hat die Debatte neu entfacht. ___(4)___ Gustav Radbruchs berühmte Formel, wonach unerträglich ungerechtes Recht keinen Geltungsanspruch erheben kann, markiert einen Wendepunkt. ___(5)___ In der zeitgenössischen Rechtstheorie haben integrative Ansätze an Bedeutung gewonnen. ___(6)___ Die Frage nach dem Verhältnis von Recht und Gerechtigkeit bleibt auch für die Praxis relevant. ___(7)___ Die digitale Transformation wirft die rechtsphilosophischen Grundfragen in neuer Form auf. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Diese als Naturrecht-Positivismus-Kontroverse bekannte Auseinandersetzung berührt fundamentale Fragen der Legitimation, der Geltung und der Verbindlichkeit rechtlicher Normen und bildet das Gravitationszentrum der abendländischen Rechtsphilosophie.',b:'Das Recht ist ein komplexes Thema.',c:'Juristen studieren viele Jahre.',d:'Es gibt verschiedene Rechtsschulen.'}, answer:'a', evidence:'ob das Recht eine überpositive moralische Grundlage besitzt', vocab:[{word:'Geltung',type:'Nomen',meaning:'validity'}] },
      { n:2, opts:{a:'Das Naturrecht hat religiöse Wurzeln.',b:'Menschenrechte sind universal.',c:'Diese Prinzipien fungieren als kritischer Maßstab, an dem sich positives Recht messen lassen muss, und verleihen dem Widerstandsrecht gegen ungerechte Gesetze eine philosophische Legitimationsgrundlage.',d:'Aristoteles war der erste Naturrechtler.'}, answer:'c', evidence:'universeller, vernunftbegründeter Rechtsprinzipien', vocab:[{word:'Legitimationsgrundlage',type:'Nomen',meaning:'basis of legitimation'}] },
      { n:3, opts:{a:'Kelsen wurde in Prag geboren.',b:'Hart lehrte in Oxford.',c:'Nach dieser Auffassung ist die Gültigkeit einer Rechtsnorm allein von ihrer korrekten Erzeugung innerhalb des Rechtssystems abhängig, nicht jedoch von ihrer inhaltlichen Übereinstimmung mit moralischen Wertvorstellungen.',d:'Der Rechtspositivismus ist die vorherrschende Theorie.'}, answer:'c', evidence:'trennt strikt zwischen Recht und Moral', vocab:[{word:'Gültigkeit',type:'Nomen',meaning:'validity'}] },
      { n:4, opts:{a:'Der Nationalsozialismus war eine Diktatur.',b:'Viele Juristen waren Mittäter.',c:'Die Frage, wie ein Rechtssystem, das formal korrekt funktionierte, zur Legalisierung systematischen Unrechts instrumentalisiert werden konnte, offenbarte die ethischen Grenzen eines rein positivistischen Rechtsbegriffs.',d:'Der Holocaust war ein Verbrechen.'}, answer:'c', evidence:'Die Erfahrung totalitärer Regime hat die Debatte neu entfacht', vocab:[{word:'instrumentalisieren',type:'Verb',meaning:'to instrumentalize'}] },
      { n:5, opts:{a:'Radbruch war ein deutscher Rechtsphilosoph.',b:'Er lebte von 1878 bis 1949.',c:'Seine vor dem Nationalsozialismus noch positivistisch geprägte Rechtsauffassung wandelte sich unter dem Eindruck des NS-Unrechts zu einer Position, die dem extremen Rechtspositivismus eine Mitschuld an der Perversion des Rechtsstaats zuweist.',d:'Seine Formel wird oft zitiert.'}, answer:'c', evidence:'Radbruchs berühmte Formel', vocab:[{word:'Rechtspositivismus',type:'Nomen',meaning:'legal positivism'}] },
      { n:6, opts:{a:'Ronald Dworkins interpretativer Rechtsansatz und Robert Alexys nichtpositivistischer Rechtsbegriff versuchen, die berechtigten Anliegen beider Traditionen aufzunehmen, ohne deren jeweilige Schwächen zu übernehmen.',b:'Es gibt viele Theorien.',c:'Die Diskussion geht weiter.',d:'Juristen sind sich uneins.'}, answer:'a', evidence:'integrative Ansätze an Bedeutung gewonnen', vocab:[{word:'interpretativ',type:'Adjektiv',meaning:'interpretive'}] },
      { n:7, opts:{a:'Richter entscheiden täglich über Recht und Unrecht.',b:'Die Verfassung schützt Grundrechte.',c:'In verfassungsgerichtlichen Verfahren, in denen Grundrechtsnormen gegen demokratisch legitimierte Gesetzgebung abgewogen werden, manifestiert sich der Konflikt zwischen naturrechtlicher Übersetzbarkeit und positivistischer Geltungstheorie in unmittelbar rechtsgestaltender Weise.',d:'Die Justiz ist unabhängig.'}, answer:'c', evidence:'für die Praxis relevant', vocab:[{word:'Geltungstheorie',type:'Nomen',meaning:'theory of validity'}] },
      { n:8, opts:{a:'Das Internet braucht Regeln.',b:'Datenschutz ist wichtig.',c:'Die Technik verändert alles.',d:'Wenn algorithmische Entscheidungssysteme über Kreditwürdigkeit, Strafzumessung oder Asylberechtigung befinden, stellt sich die Frage, ob die philosophischen Fundamente eines auf menschliche Urteilskraft gegründeten Rechtssystems tragfähig bleiben.'}, answer:'d', evidence:'digitale Transformation wirft rechtsphilosophische Grundfragen auf', vocab:[{word:'Urteilskraft',type:'Nomen',meaning:'faculty of judgment'}] },
    ]
  },
  {
    exerciseId: 'C2-T2-002',
    texts: [{ id: 'TextA', type: 'sachtext', title: 'Goethes Faust: Universalität und Aktualität',
      content: 'Goethes „Faust" gilt als das zentrale Werk der deutschen Literatur und zugleich als eines der Schlüsselwerke der Weltliteratur. ___(1)___ Die Tragödie erzählt die Geschichte eines Gelehrten, der in seinem Streben nach absoluter Erkenntnis einen Pakt mit dem Teufel eingeht. ___(2)___ Die Gretchen-Tragödie im ersten Teil verbindet die metaphysische Dimension mit einer Sozialkritik. ___(3)___ Im zweiten Teil weitet Goethe die Handlung ins Politische und Ökonomische aus. ___(4)___ Die Rezeptionsgeschichte des Faust spiegelt den jeweiligen Zeitgeist wider. ___(5)___ Für die Literaturwissenschaft bleibt der Faust ein unerschöpflicher Forschungsgegenstand. ___(6)___ Die theatrale Umsetzung des Werks stellt Regisseure vor enorme Herausforderungen. ___(7)___ Die Aktualität des Faust liegt in seiner Auseinandersetzung mit der menschlichen Hybris. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Goethe wurde 1749 geboren.',b:'Er arbeitete über sechs Jahrzehnte lang an diesem Werk.',c:'Die über sechs Jahrzehnte währende Entstehungsgeschichte dieses opus magnum dokumentiert nicht nur die künstlerische Evolution seines Schöpfers, sondern auch die geistesgeschichtlichen Umwälzungen einer Epochenschwelle.',d:'Der Faust ist Pflichtlektüre.'}, answer:'c', evidence:'das zentrale Werk der deutschen Literatur', vocab:[{word:'Epochenschwelle',type:'Nomen',meaning:'threshold between epochs'}] },
      { n:2, opts:{a:'Die Wette mit Mephisto ist berühmt.',b:'In der faustischen Wette, die den erkenntnistheoretischen Optimismus der Aufklärung ebenso reflektiert wie die romantische Sehnsucht nach dem Unendlichen, verdichtet sich das anthropologische Grundmotiv eines nie zu stillenden Strebens.',c:'Faust ist ein Wissenschaftler.',d:'Der Teufel heißt Mephisto.'}, answer:'b', evidence:'Streben nach absoluter Erkenntnis', vocab:[{word:'erkenntnistheoretisch',type:'Adjektiv',meaning:'epistemological'}] },
      { n:3, opts:{a:'Gretchen ist eine tragische Figur.',b:'Die Liebesgeschichte ist bewegend.',c:'Das Schicksal Margaretes, deren Untergang aus der Kollision ständischer Moralvorstellungen mit der Rücksichtslosigkeit faustischen Begehrens resultiert, offenbart die destruktive Kehrseite des prometheischen Selbstverwirklichungsanspruchs.',d:'Der erste Teil wurde 1808 veröffentlicht.'}, answer:'c', evidence:'Gretchen-Tragödie verbindet metaphysische Dimension mit Sozialkritik', vocab:[{word:'prometheisch',type:'Adjektiv',meaning:'Promethean'}] },
      { n:4, opts:{a:'Der zweite Teil ist schwerer zu verstehen.',b:'Die Landgewinnungsszene im fünften Akt, in der Faust durch technische Naturbeherrschung utopischen Fortschritt erzwingen will und dabei über Leichen geht, antizipiert in prophetischer Weise die ökologischen und ethischen Dilemmata der Moderne.',c:'Goethe vollendete den zweiten Teil kurz vor seinem Tod.',d:'Im zweiten Teil reist Faust durch die Zeit.'}, answer:'b', evidence:'weitet die Handlung ins Politische und Ökonomische', vocab:[{word:'antizipieren',type:'Verb',meaning:'to anticipate'}] },
      { n:5, opts:{a:'Jede Generation liest den Faust anders.',b:'Im Kaiserreich diente Faust als Symbol deutschen Tatendrangs, im Nationalsozialismus wurde er völkisch vereinnahmt, in der DDR marxistisch umgedeutet, und in der Postmoderne zum Paradigma des gescheiterten Totalitätsanspruchs erklärt.',c:'Der Faust wurde oft verfilmt.',d:'Es gibt viele Übersetzungen.'}, answer:'b', evidence:'Rezeptionsgeschichte spiegelt den Zeitgeist wider', vocab:[{word:'Totalitätsanspruch',type:'Nomen',meaning:'claim to totality'}] },
      { n:6, opts:{a:'Es gibt viele Interpretationen.',b:'Germanisten forschen intensiv.',c:'Die intertextuellen Bezüge zur antiken Mythologie, zur mittelalterlichen Teufelsliteratur, zur Alchemie und zur zeitgenössischen Naturphilosophie bilden ein Referenzgeflecht, dessen vollständige Entschlüsselung noch immer aussteht.',d:'Der Faust ist gut erforscht.'}, answer:'c', evidence:'unerschöpflicher Forschungsgegenstand', vocab:[{word:'intertextuell',type:'Adjektiv',meaning:'intertextual'}] },
      { n:7, opts:{a:'Faust wird oft aufgeführt.',b:'Mit über 12.000 Versen, zahlreichen Schauplatzwechseln, allegorischen Massenszenen und einer Zeitspanne von der Antike bis zur Moderne sprengt das Werk konventionelle Bühnenformate und verlangt nach experimentellen szenischen Konzepten.',c:'Manche Inszenierungen dauern über acht Stunden.',d:'Peter Stein inszenierte den gesamten Faust.'}, answer:'b', evidence:'theatrale Umsetzung stellt Regisseure vor Herausforderungen', vocab:[{word:'allegorisch',type:'Adjektiv',meaning:'allegorical'}] },
      { n:8, opts:{a:'Der Faust ist zeitlos.',b:'Goethe war ein Genie.',c:'Klassiker bleiben relevant.',d:'In einer Epoche, in der technologische Machbarkeit die ethische Reflexion systematisch überholt und das faustische „Verweile doch" durch die rastlose Beschleunigungslogik des digitalen Kapitalismus pervertiert wird, erweist sich Goethes Diagnose als bestürzend aktuell.'}, answer:'d', evidence:'menschlichen Hybris', vocab:[{word:'Hybris',type:'Nomen',meaning:'hubris'}] },
    ]
  },
  {
    exerciseId: 'C2-T2-003',
    texts: [{ id: 'TextA', type: 'sachtext', title: 'Grundlagenforschung und ihre gesellschaftliche Legitimation',
      content: 'Die Legitimation von Grundlagenforschung, die keinen unmittelbaren praktischen Nutzen verspricht, wird in Zeiten knapper öffentlicher Ressourcen zunehmend hinterfragt. ___(1)___ Die Geschichte der Wissenschaft liefert zahlreiche Beispiele für den unvorhersehbaren Nutzen grundlegender Entdeckungen. ___(2)___ Gleichzeitig wächst der Druck auf Forschende, die gesellschaftliche Relevanz ihrer Arbeit nachzuweisen. ___(3)___ Die Freiheit der Forschung ist ein verfassungsrechtlich geschütztes Gut. ___(4)___ Interdisziplinarität wird zunehmend als Voraussetzung für Innovationen betrachtet. ___(5)___ Die Reproduzierbarkeitskrise betrifft mehrere wissenschaftliche Disziplinen. ___(6)___ Die Finanzierung von Grundlagenforschung ist international höchst unterschiedlich organisiert. ___(7)___ Die epistemische Demut, also das Bewusstsein für die Grenzen des eigenen Wissens, sollte eine Kardinaltugend der Wissenschaft bleiben. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Forschung ist teuer.',b:'Die Spannung zwischen dem Eigenrecht zweckfreier Erkenntnis und der demokratisch legitimierten Forderung nach gesellschaftlicher Rechenschaftspflicht durchzieht die Wissenschaftspolitik aller modernen Industriestaaten.',c:'Nicht alle Forschung ist nützlich.',d:'Politiker verstehen die Wissenschaft nicht.'}, answer:'b', evidence:'Legitimation von Grundlagenforschung wird hinterfragt', vocab:[{word:'Rechenschaftspflicht',type:'Nomen',meaning:'accountability'}] },
      { n:2, opts:{a:'Max Plancks Quantentheorie, die als rein theoretische Spekulation begann, ermöglichte Jahrzehnte später die Entwicklung des Lasers, des Transistors und der gesamten digitalen Infrastruktur der modernen Welt.',b:'Die Wissenschaft hat viel erreicht.',c:'Grundlagenforschung führt oft zu Entdeckungen.',d:'Einstein war ein Theoretiker.'}, answer:'a', evidence:'unvorhersehbaren Nutzen grundlegender Entdeckungen', vocab:[{word:'Quantentheorie',type:'Nomen',meaning:'quantum theory'}] },
      { n:3, opts:{a:'Forschungsanträge müssen genehmigt werden.',b:'Die Bürokratie nimmt zu.',c:'Die zunehmende Projektifizierung und Drittmittelabhängigkeit der Forschungsfinanzierung begünstigt kurzfristig verwertbare Ergebnisse und benachteiligt risikoreiche, zeitintensive Grundlagenforschung, die den wirklich transformativen Durchbrüchen historisch vorausgeht.',d:'Wissenschaftler brauchen mehr Geld.'}, answer:'c', evidence:'gesellschaftliche Relevanz nachzuweisen', vocab:[{word:'Projektifizierung',type:'Nomen',meaning:'projectification'}] },
      { n:4, opts:{a:'Jeder darf forschen.',b:'Die Verfassung schützt viele Rechte.',c:'Diese grundgesetzliche Garantie reflektiert die historische Erfahrung, dass staatlich gelenkte Wissenschaft — wie im Nationalsozialismus oder Lyssenkoismus — nicht nur die Erkenntnisfähigkeit korrumpiert, sondern auch die ethischen Grundlagen der Forschungsgemeinschaft zerstört.',d:'Wissenschaftsfreiheit ist ein Grundrecht.'}, answer:'c', evidence:'verfassungsrechtlich geschütztes Gut', vocab:[{word:'Lyssenkoismus',type:'Nomen',meaning:'Lysenkoism'}] },
      { n:5, opts:{a:'Verschiedene Fächer arbeiten zusammen.',b:'Die fruchtbarsten wissenschaftlichen Innovationen der jüngsten Zeit — von der Bioinformatik über die Neuroökonomie bis zur Computational Social Science — entstehen an den Schnittstellen traditionell getrennter Disziplinen, wo heterogene Methoden und Wissensbestände produktiv kollidieren.',c:'Teamarbeit ist wichtig.',d:'Spezialisierung hat auch Vorteile.'}, answer:'b', evidence:'Interdisziplinarität als Voraussetzung für Innovationen', vocab:[{word:'Bioinformatik',type:'Nomen',meaning:'bioinformatics'}] },
      { n:6, opts:{a:'Viele Studien können nicht repliziert werden.',b:'Die Qualität der Forschung schwankt.',c:'Die systematische Unfähigkeit, publizierte Forschungsergebnisse in kontrollierten Wiederholungsstudien zu bestätigen — dokumentiert in der Psychologie, Medizin und Ökonomie —, hat das Vertrauen in wissenschaftliche Selbstkorrekturmechanismen erschüttert und eine Methodenreflexion ausgelöst.',d:'Peer Review funktioniert nicht immer.'}, answer:'c', evidence:'Reproduzierbarkeitskrise', vocab:[{word:'Selbstkorrekturmechanismus',type:'Nomen',meaning:'self-correction mechanism'}] },
      { n:7, opts:{a:'Die USA geben am meisten aus.',b:'Während missionsorientierte Forschungssysteme wie das der DARPA oder die Fraunhofer-Gesellschaft auf strategische Anwendungsfelder fokussieren, setzen curiosity-driven Modelle wie die Max-Planck-Gesellschaft auf die intrinsische Dynamik erkenntnisgeleiteter Forschung.',c:'Europa investiert zu wenig.',d:'Private Unternehmen forschen auch.'}, answer:'b', evidence:'international höchst unterschiedlich organisiert', vocab:[{word:'curiosity-driven',type:'Adjektiv',meaning:'curiosity-driven'}] },
      { n:8, opts:{a:'Bescheidenheit ist eine Tugend.',b:'Wissenschaftler sollten ehrlich sein.',c:'Niemand weiß alles.',d:'In einer Zeit, in der Szientismus und Wissenschaftsskepsis gleichermaßen zunehmen, kommt der authentischen Kommunikation von Unsicherheit, Vorläufigkeit und methodischen Grenzen eine Schlüsselrolle für die Aufrechterhaltung öffentlichen Vertrauens in die Wissenschaft zu.'}, answer:'d', evidence:'epistemische Demut', vocab:[{word:'Szientismus',type:'Nomen',meaning:'scientism'}] },
    ]
  },
  {
    exerciseId: 'C2-T2-004',
    texts: [{ id: 'TextA', type: 'sachtext', title: 'Sprache, Denken und die Grenzen der Welt',
      content: 'Die Frage nach dem Verhältnis von Sprache und Denken gehört zu den ältesten und zugleich kontroversesten Problemen der Philosophie. ___(1)___ Die Sapir-Whorf-Hypothese in ihrer starken Form postuliert eine sprachliche Determination des Denkens. ___(2)___ Noam Chomskys Universalgrammatik vertritt die Gegenposition. ___(3)___ Neuere Forschungen in der kognitiven Linguistik haben die Debatte um empirische Befunde bereichert. ___(4)___ Ludwig Wittgensteins philosophische Untersuchungen haben das Verständnis von Sprache grundlegend verändert. ___(5)___ Die Philosophie der normalen Sprache hat weitreichende Konsequenzen für andere Disziplinen. ___(6)___ Sprachphilosophische Fragen gewinnen durch die Entwicklung von KI-Sprachmodellen neue Dringlichkeit. ___(7)___ Die Vielsprachigkeit der Menschheit ist aus sprachphilosophischer Sicht kein Defizit, sondern ein epistemischer Reichtum. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Sprache ist einzigartig menschlich.',b:'Kinder lernen Sprache intuitiv.',c:'Wittgensteins berühmtes Diktum „Die Grenzen meiner Sprache bedeuten die Grenzen meiner Welt" verdichtet diese Problematik in eine Formel, deren scheinbare Einfachheit eine abgründige Komplexität verbirgt.',d:'Es gibt viele Sprachen auf der Welt.'}, answer:'c', evidence:'Verhältnis von Sprache und Denken', vocab:[{word:'Diktum',type:'Nomen',meaning:'dictum'}] },
      { n:2, opts:{a:'Benjamin Lee Whorf studierte indianische Sprachen.',b:'Demnach würden Sprecher verschiedener Sprachen die Welt kategorial unterschiedlich wahrnehmen und konzeptualisieren — eine These, die in ihrer radikalen Konsequenz die Möglichkeit vollständiger interlingualer Übersetzung infrage stellt.',c:'Sprache beeinflusst das Denken.',d:'Jede Sprache ist einzigartig.'}, answer:'b', evidence:'sprachliche Determination des Denkens', vocab:[{word:'konzeptualisieren',type:'Verb',meaning:'to conceptualize'}] },
      { n:3, opts:{a:'Chomsky ist ein berühmter Linguist.',b:'Er lehrt am MIT.',c:'Seine Theorie einer angeborenen, biologisch determinierten Sprachfähigkeit, die allen natürlichen Sprachen gemeinsame Strukturprinzipien zugrunde legt, impliziert, dass die kognitive Grundarchitektur des Menschen sprachunabhängig und universell ist.',d:'Die Universalgrammatik ist umstritten.'}, answer:'c', evidence:'Chomskys Universalgrammatik', vocab:[{word:'Sprachfähigkeit',type:'Nomen',meaning:'language faculty'}] },
      { n:4, opts:{a:'Sprache und Denken hängen zusammen.',b:'Lera Boroditskys Experimente zum sprachlichen Einfluss auf Zeitwahrnehmung, Farbdiskrimination und Raumkognition liefern differenzierte Evidenz für moderate sprachliche Relativitätseffekte, ohne die starke Determinismusthese zu bestätigen.',c:'Wissenschaftler führen viele Experimente durch.',d:'Kognitive Linguistik ist ein neues Feld.'}, answer:'b', evidence:'empirische Befunde bereichert', vocab:[{word:'Relativitätseffekt',type:'Nomen',meaning:'relativity effect'}] },
      { n:5, opts:{a:'Wittgenstein lehrte in Cambridge.',b:'Der Tractatus ist sein bekanntestes Werk.',c:'Sein Konzept der Sprachspiele, demzufolge die Bedeutung eines Wortes in seinem Gebrauch innerhalb konkreter Lebensformen liegt und nicht in einer referenziellen Abbildung der Realität, hat die essentialistische Semantik dekonstruiert.',d:'Wittgenstein war Österreicher.'}, answer:'c', evidence:'Wittgensteins philosophische Untersuchungen', vocab:[{word:'Sprachspiel',type:'Nomen',meaning:'language game'}] },
      { n:6, opts:{a:'J.L. Austins Sprechakttheorie hat gezeigt, dass Äußerungen nicht nur beschreiben, sondern Handlungen vollziehen — eine Einsicht, die das Verständnis von Rechtsakten, therapeutischer Kommunikation und politischer Rhetorik grundlegend transformiert hat.',b:'Sprache ist mächtig.',c:'Worte können verletzen.',d:'Kommunikation ist komplex.'}, answer:'a', evidence:'weitreichende Konsequenzen für andere Disziplinen', vocab:[{word:'Sprechakttheorie',type:'Nomen',meaning:'speech act theory'}] },
      { n:7, opts:{a:'KI kann immer besser sprechen.',b:'ChatGPT ist beeindruckend.',c:'Die Frage, ob Large Language Models, die statistisch überzeugende Texte generieren ohne semantisches Verständnis zu besitzen, den Bedeutungsbegriff selbst infrage stellen oder lediglich die behavioristischen Grenzen unserer Bedeutungstheorien offenlegen, spaltet die zeitgenössische Sprachphilosophie.',d:'KI wird immer besser.'}, answer:'c', evidence:'KI-Sprachmodellen neue Dringlichkeit', vocab:[{word:'behavioristisch',type:'Adjektiv',meaning:'behaviorist'}] },
      { n:8, opts:{a:'Mehrsprachigkeit ist ein Vorteil.',b:'Jede Sprache, die ausstirbt, ist ein Verlust.',c:'Die Welt ist vielfältig.',d:'Jede natürliche Sprache stellt ein einzigartiges kognitives Werkzeug dar, das bestimmte Aspekte der Wirklichkeit besonders differenziert erfasst und dessen Verlust eine unwiederbringliche Verarmung des menschlichen Denk- und Erfahrungsraums bedeutet.'}, answer:'d', evidence:'epistemischer Reichtum', vocab:[{word:'Erfahrungsraum',type:'Nomen',meaning:'space of experience'}] },
    ]
  },
]

async function main() {
  console.log('🚀 Seeding — Batch 7 (C2-T2-001 to 004)')
  for (const entry of batch) {
    const ex = await prisma.readingExercise.findFirst({ where: { exerciseId: entry.exerciseId }, include: { questions: true } })
    if (!ex) { console.log(`⏭️ ${entry.exerciseId} not found`); continue }
    if (ex.questions.length > 0) { console.log(`⏭️ ${entry.exerciseId} already has questions`); continue }
    await prisma.readingExercise.update({ where: { id: ex.id }, data: { textsJson: entry.texts } })
    for (const q of entry.questions) {
      await prisma.readingQuestion.create({ data: {
        exerciseId: ex.id, questionNumber: q.n, questionType: 'lueckentext', linkedText: 'TextA',
        statement: `Welcher Textabschnitt passt in Lücke ${q.n}?`, options: q.opts, correctAnswer: q.answer, points: 1, sortOrder: q.n,
        explanation: { reasoning: `Der Textabschnitt fügt sich inhaltlich und argumentativ kohärent in den Kontext ein.`, key_evidence: q.evidence, key_vocabulary: q.vocab }
      }})
    }
    console.log(`✅ ${entry.exerciseId} — ${entry.texts[0].title}`)
  }
  console.log('🎉 Batch 7 complete!')
}
main().catch(console.error).finally(() => prisma.$disconnect())
