import { PrismaClient } from '../apps/web/generated/prisma'
const prisma = new PrismaClient()
const batch = [
  { exerciseId: 'C2-T2-005', texts: [{ id: 'TextA', type: 'sachtext', title: 'Multilateralismus und die Krise der Weltordnung', content: 'Die nach 1945 etablierte multilaterale Weltordnung befindet sich in einer tiefgreifenden Legitimationskrise. ___(1)___ Der Aufstieg Chinas verändert die geopolitischen Kräfteverhältnisse fundamental. ___(2)___ Regionale Konflikte eskalieren zunehmend ohne wirksame internationale Intervention. ___(3)___ Die Vereinten Nationen stehen vor einem Reformstau. ___(4)___ Neue Formen transnationaler Bedrohungen erfordern neuartige Kooperationsformate. ___(5)___ Die Erosion demokratischer Normen gefährdet die Grundlagen der regelbasierten Ordnung. ___(6)___ Wirtschaftliche Interdependenz wird zunehmend als geopolitisches Instrument eingesetzt. ___(7)___ Die Zukunft der internationalen Ordnung hängt davon ab, ob ein neuer normativer Konsens gelingen kann. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Die zunehmende Diskrepanz zwischen der in den Institutionen abgebildeten Machtverteilung der Nachkriegszeit und den realpolitischen Kräfteverhältnissen des 21. Jahrhunderts untergräbt die Akzeptanz und Handlungsfähigkeit internationaler Organisationen.',b:'Die Welt ist kompliziert.',c:'Es gibt viele internationale Organisationen.',d:'Die USA sind die stärkste Macht.'}, answer:'a', evidence:'Legitimationskrise', vocab:[{word:'Diskrepanz',type:'Nomen',meaning:'discrepancy'}] },
      { n:2, opts:{a:'China hat eine große Bevölkerung.',b:'Sein systemischer Wettbewerb mit den USA, der ideologische, technologische, wirtschaftliche und militärische Dimensionen umfasst, erzwingt eine Neuausrichtung der strategischen Kalkulationen aller Akteure im internationalen System.',c:'Die Seidenstraße ist ein großes Projekt.',d:'China investiert viel in Afrika.'}, answer:'b', evidence:'Der Aufstieg Chinas', vocab:[{word:'systemischer Wettbewerb',type:'Nomen',meaning:'systemic competition'}] },
      { n:3, opts:{a:'Es gibt viele Kriege.',b:'Die Zivilbevölkerung leidet.',c:'Die Blockade des UN-Sicherheitsrats durch wechselseitige Vetos der ständigen Mitglieder paralysiert das kollektive Sicherheitssystem in Fällen, in denen vitale Interessen der Großmächte berührt sind.',d:'Friedensverhandlungen sind schwierig.'}, answer:'c', evidence:'ohne wirksame internationale Intervention', vocab:[{word:'paralysieren',type:'Verb',meaning:'to paralyze'}] },
      { n:4, opts:{a:'Die Zusammensetzung des Sicherheitsrats, die Vetoregelung und die institutionelle Fragmentierung des UN-Systems reflektieren geopolitische Konstellationen, die der Realität des 21. Jahrhunderts nicht mehr entsprechen.',b:'Die UN haben ihren Sitz in New York.',c:'Die UN wurden 1945 gegründet.',d:'Es gibt 193 Mitgliedstaaten.'}, answer:'a', evidence:'Reformstau', vocab:[{word:'Vetoregelung',type:'Nomen',meaning:'veto regulation'}] },
      { n:5, opts:{a:'Pandemien, Cyberangriffe auf kritische Infrastruktur, algorithmisch beschleunigte Desinformation und die Weaponisierung von Migrationsströmen transzendieren nationalstaatliche Grenzen und erfordern Reaktionsmechanismen, die das bestehende Instrumentarium übersteigen.',b:'Der Terrorismus ist eine globale Bedrohung.',c:'Der Klimawandel betrifft alle.',d:'Globale Probleme brauchen globale Lösungen.'}, answer:'a', evidence:'Neue Formen transnationaler Bedrohungen', vocab:[{word:'Weaponisierung',type:'Nomen',meaning:'weaponization'}] },
      { n:6, opts:{a:'Die Demokratie ist in der Krise.',b:'Autokratien werden stärker.',c:'Der weltweit zu beobachtende demokratische Rückgang — von der Aushöhlung rechtsstaatlicher Institutionen über die Einschränkung zivilgesellschaftlicher Freiräume bis zur Manipulation von Wahlen — destabilisiert das normative Fundament, auf dem die multilaterale Ordnung ruht.',d:'Die Pressefreiheit wird eingeschränkt.'}, answer:'c', evidence:'Erosion demokratischer Normen', vocab:[{word:'rechtsstaatlich',type:'Adjektiv',meaning:'rule-of-law based'}] },
      { n:7, opts:{a:'Die Instrumentalisierung von Handelsbeziehungen, Technologietransfer und Investitionsströmen als Druckmittel in geopolitischen Auseinandersetzungen — die sogenannte Geoökonomie — untergräbt die Prämisse wechselseitiger Wohlstandsgewinne durch wirtschaftliche Integration.',b:'Die Globalisierung hat viele Vorteile.',c:'Der Freihandel wird kritisiert.',d:'Sanktionen sind ein politisches Instrument.'}, answer:'a', evidence:'Wirtschaftliche Interdependenz als geopolitisches Instrument', vocab:[{word:'Geoökonomie',type:'Nomen',meaning:'geo-economics'}] },
      { n:8, opts:{a:'Die Zukunft ist ungewiss.',b:'Diplomatie ist wichtig.',c:'Die Welt braucht Frieden.',d:'Angesichts der tiefgreifenden Divergenzen zwischen liberalen, autoritären und postkolonialen Ordnungsvorstellungen erfordert dies eine Verständigung auf prozedurale Minimalnormen, die koexistenzfähig sind, ohne auf die Durchsetzung substanzieller Gerechtigkeitsprinzipien vollständig zu verzichten.'}, answer:'d', evidence:'ob ein neuer normativer Konsens gelingen kann', vocab:[{word:'Minimalnormen',type:'Nomen',meaning:'minimal norms'}] },
    ]
  },
  { exerciseId: 'C2-T2-006', texts: [{ id: 'TextA', type: 'sachtext', title: 'Paradigmenwechsel und wissenschaftliche Revolutionen', content: 'Die Wissenschaftsgeschichte zeigt, dass der Erkenntnisfortschritt keineswegs linear verläuft, sondern durch revolutionäre Umbrüche geprägt ist. ___(1)___ Die kopernikanische Wende markiert den paradigmatischen Bruch mit dem geozentrischen Weltbild. ___(2)___ Darwins Evolutionstheorie erschütterte religiöse und philosophische Gewissheiten. ___(3)___ Die Quantenmechanik stellte fundamentale Annahmen der klassischen Physik infrage. ___(4)___ Die Entschlüsselung der DNA-Struktur revolutionierte die Biologie. ___(5)___ Die Plattentektonik transformierte die Geowissenschaften. ___(6)___ Jeder Paradigmenwechsel provoziert massiven Widerstand innerhalb der etablierten Wissenschaft. ___(7)___ Die heutige Wissenschaft steht möglicherweise vor neuen paradigmatischen Umbrüchen. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Thomas Kuhns „Struktur wissenschaftlicher Revolutionen" hat gezeigt, dass die Normalwissenschaft innerhalb eines Paradigmas operiert, bis die Akkumulation von Anomalien eine Krise auslöst, die in einem Paradigmenwechsel mündet.',b:'Wissenschaft ist wichtig.',c:'Es gibt viele Wissenschaftler.',d:'Die Wissenschaft hat sich verändert.'}, answer:'a', evidence:'revolutionäre Umbrüche', vocab:[{word:'Normalwissenschaft',type:'Nomen',meaning:'normal science'}] },
      { n:2, opts:{a:'Kopernikus lebte im 16. Jahrhundert.',b:'Die Erde dreht sich um die Sonne.',c:'Die Verlagerung des Beobachtungszentrums von der Erde zur Sonne war nicht bloß eine astronomische Korrektur, sondern eine existenzielle Dezentrierung des Menschen, die das gesamte kosmologische, theologische und anthropologische Selbstverständnis Europas erschütterte.',d:'Galileo bestätigte Kopernikus.'}, answer:'c', evidence:'kopernikanische Wende', vocab:[{word:'Dezentrierung',type:'Nomen',meaning:'decentering'}] },
      { n:3, opts:{a:'Die natürliche Selektion wirkt auf alle Arten.',b:'Indem sie den Menschen in die Kontinuität des Lebendigen einreihte und die Vorstellung eines teleologischen Schöpfungsplans durch einen blinden, statistischen Mechanismus ersetzte, demontierte sie die anthropozentrische Sonderstellung des Menschen in der Natur.',c:'Darwin reiste auf der Beagle.',d:'Die Evolution dauert Millionen von Jahren.'}, answer:'b', evidence:'Darwins Evolutionstheorie erschütterte', vocab:[{word:'teleologisch',type:'Adjektiv',meaning:'teleological'}] },
      { n:4, opts:{a:'Atome sind sehr klein.',b:'Die Physik ist eine exakte Wissenschaft.',c:'Die Entdeckung, dass subatomare Teilchen gleichzeitig Wellen- und Teilchencharakter besitzen und dass der Beobachtungsakt den Zustand des beobachteten Systems beeinflusst, sprengte die deterministische Ontologie der newtonschen Mechanik.',d:'Einstein mochte die Quantenmechanik nicht.'}, answer:'c', evidence:'fundamentale Annahmen der klassischen Physik', vocab:[{word:'deterministische Ontologie',type:'Nomen',meaning:'deterministic ontology'}] },
      { n:5, opts:{a:'Watson und Crick entdeckten die Doppelhelix 1953.',b:'DNA enthält den genetischen Code.',c:'Die Aufklärung des molekularen Informationsspeichers, der die Vererbung steuert, eröffnete nicht nur die Biotechnologie und Genommedizin, sondern stellte die Biologie erstmals auf ein informationstheoretisches Fundament, das mathematische Präzision ermöglichte.',d:'Genetik ist ein wichtiges Fach.'}, answer:'c', evidence:'DNA-Struktur revolutionierte die Biologie', vocab:[{word:'informationstheoretisch',type:'Adjektiv',meaning:'information-theoretic'}] },
      { n:6, opts:{a:'Kontinente verschieben sich langsam.',b:'Alfred Wegener hatte recht.',c:'Die erst in den 1960er-Jahren akzeptierte Erkenntnis, dass die Erdkruste aus beweglichen tektonischen Platten besteht, deren Interaktion Erdbeben, Vulkanismus und Gebirgsbildung erklärt, integrierte disparate geologische Phänomene erstmals in ein kohärentes theoretisches Rahmenwerk.',d:'Vulkane entstehen an Plattengrenzen.'}, answer:'c', evidence:'Plattentektonik transformierte die Geowissenschaften', vocab:[{word:'tektonisch',type:'Adjektiv',meaning:'tectonic'}] },
      { n:7, opts:{a:'Neue Theorien brauchen Zeit.',b:'Wissenschaftler sind oft konservativ.',c:'Max Plancks Bonmot, dass eine neue wissenschaftliche Wahrheit sich nicht durchsetze, indem sie ihre Gegner überzeugt, sondern indem diese allmählich aussterben, beleuchtet die soziologische Dimension wissenschaftlichen Wandels jenseits rein rationaler Argumentation.',d:'Alte Professoren akzeptieren keine neuen Ideen.'}, answer:'c', evidence:'massiven Widerstand', vocab:[{word:'Bonmot',type:'Nomen',meaning:'bon mot/witticism'}] },
      { n:8, opts:{a:'Die KI wird alles verändern.',b:'Die Wissenschaft wird sich weiterentwickeln.',c:'Es gibt immer Neues zu entdecken.',d:'Die Konvergenz von Quantencomputing, synthetischer Biologie, Neurowissenschaft und KI-gestützter Hypothesengenerierung könnte Erkenntnissprünge ermöglichen, die nicht nur einzelne Disziplinen, sondern das Verständnis von Wissenschaft selbst transformieren.'}, answer:'d', evidence:'vor neuen paradigmatischen Umbrüchen', vocab:[{word:'Konvergenz',type:'Nomen',meaning:'convergence'}] },
    ]
  },
  { exerciseId: 'C2-T2-007', texts: [{ id: 'TextA', type: 'sachtext', title: 'Kulturelle Hegemonie und Gegennarrative', content: 'Antonio Gramscis Konzept der kulturellen Hegemonie hat die Kulturtheorie des 20. Jahrhunderts maßgeblich beeinflusst. ___(1)___ In der Tradition der Cultural Studies wurde dieses Konzept weiterentwickelt. ___(2)___ Postkoloniale Theorie hat die eurozentrische Perspektive der Kulturwissenschaft kritisiert. ___(3)___ Die Debatten um kulturelle Aneignung zeigen die Aktualität hegemonialer Machtverhältnisse. ___(4)___ Die Populärkultur ist ein zentrales Terrain hegemonialer Aushandlungsprozesse. ___(5)___ Digitale Medien verändern die Bedingungen kultureller Hegemonie. ___(6)___ Die Frage nach einem universellen Kulturbegriff ist theoretisch höchst umstritten. ___(7)___ Eine kritische Kulturtheorie muss ihre eigene Positionierung reflektieren. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Gramsci war Italiener.',b:'Seine in den Gefängnisheften entwickelte Analyse, wie herrschende Klassen durch die Produktion von Konsens statt durch Zwang ihre Machtstellung reproduzieren, verschob den Fokus marxistischer Theorie vom ökonomischen Unterbau zum kulturellen Überbau.',c:'Hegemonie bedeutet Vorherrschaft.',d:'Er war ein politischer Gefangener.'}, answer:'b', evidence:'kulturellen Hegemonie', vocab:[{word:'Überbau',type:'Nomen',meaning:'superstructure'}] },
      { n:2, opts:{a:'Stuart Hall, Raymond Williams und andere Vertreter der Birmingham School zeigten, dass Kultur kein passiver Reflex ökonomischer Strukturen ist, sondern ein aktiv umkämpftes Feld, auf dem subalterne Gruppen eigene Bedeutungen und Widerstandspraktiken hervorbringen.',b:'Cultural Studies sind populär.',c:'Sie entstanden in England.',d:'Medien werden analysiert.'}, answer:'a', evidence:'Cultural Studies', vocab:[{word:'subaltern',type:'Adjektiv',meaning:'subaltern'}] },
      { n:3, opts:{a:'Edward Said lehrte in New York.',b:'Gayatri Spivaks Frage „Can the Subaltern Speak?" und Edward Saids Analyse des „Orientalismus" haben offengelegt, wie westliche Wissensproduktion den kolonisierten Anderen systematisch als defizitär konstruierte und damit epistemische Gewalt ausübte.',c:'Der Kolonialismus war ungerecht.',d:'Es gibt viele postkoloniale Autoren.'}, answer:'b', evidence:'eurozentrische Perspektive kritisiert', vocab:[{word:'epistemische Gewalt',type:'Nomen',meaning:'epistemic violence'}] },
      { n:4, opts:{a:'Kulturelle Aneignung ist umstritten.',b:'Mode ist ein globales Phänomen.',c:'Die Übernahme kultureller Praktiken, Symbole und Ästhetiken aus marginalisierten in hegemoniale Kontexte — etwa indigener Muster in der Haute Couture — reproduziert Machtasymmetrien, indem sie kulturelles Kapital extrahiert, ohne die sozialen Bedingungen seiner Entstehung anzuerkennen.',d:'Jeder sollte tragen, was er will.'}, answer:'c', evidence:'kulturelle Aneignung', vocab:[{word:'kulturelles Kapital',type:'Nomen',meaning:'cultural capital'}] },
      { n:5, opts:{a:'Von der Genderdarstellung in Videospielen über die Rassifikation in Streamingserien bis zur algorithmischen Selektion viraler Inhalte werden in der Populärkultur hegemoniale Normalitätsvorstellungen reproduziert, aber auch subversiv unterlaufen und transformiert.',b:'Filme beeinflussen die Gesellschaft.',c:'Musik ist wichtig.',d:'Populärkultur ist Unterhaltung.'}, answer:'a', evidence:'zentrales Terrain hegemonialer Aushandlungsprozesse', vocab:[{word:'Rassifikation',type:'Nomen',meaning:'racialization'}] },
      { n:6, opts:{a:'Social Media demokratisiert die Kultur.',b:'Die Dezentralisierung kultureller Produktion durch digitale Plattformen ermöglicht zwar marginalisierte Gegenöffentlichkeiten, wird jedoch durch die Aufmerksamkeitsökonomie und die Konzentration digitaler Infrastruktur bei wenigen Konzernen strukturell limitiert.',c:'Das Internet hat alles verändert.',d:'Jeder kann heute Inhalte veröffentlichen.'}, answer:'b', evidence:'Digitale Medien verändern die Bedingungen', vocab:[{word:'Gegenöffentlichkeit',type:'Nomen',meaning:'counter-public sphere'}] },
      { n:7, opts:{a:'Kultur ist relativ.',b:'Es gibt viele Kulturbegriffe.',c:'Der Versuch, kulturelle Universalien zu identifizieren, steht in der Spannung zwischen einer abstrakten Menschheitsethik und dem Vorwurf des kulturellen Imperialismus, der partikulare westliche Werte als universell naturalisiert.',d:'Jede Kultur ist wertvoll.'}, answer:'c', evidence:'universellen Kulturbegriff höchst umstritten', vocab:[{word:'Imperialismus',type:'Nomen',meaning:'imperialism'}] },
      { n:8, opts:{a:'Theorie muss praktisch sein.',b:'Selbstreflexion ist wichtig.',c:'Kritik muss fair sein.',d:'Dies impliziert eine konsequente Historisierung der eigenen Kategorien, die Offenlegung der institutionellen und epistemischen Privilegien, aus denen sie spricht, und die Bereitschaft, sich durch die Perspektiven jener korrigieren zu lassen, über die sie theoretisiert.'}, answer:'d', evidence:'eigene Positionierung reflektieren', vocab:[{word:'Historisierung',type:'Nomen',meaning:'historicization'}] },
    ]
  },
  { exerciseId: 'C2-T2-008', texts: [{ id: 'TextA', type: 'sachtext', title: 'Ökonomische Rationalität und moralische Verantwortung', content: 'Die Wirtschaftsethik untersucht die moralischen Grundlagen und Grenzen ökonomischen Handelns. ___(1)___ Milton Friedmans Shareholder-Value-Doktrin dominierte die Unternehmensethik über Jahrzehnte. ___(2)___ Die Stakeholder-Theorie fordert eine erweiterte Verantwortung. ___(3)___ Die Lieferkettenproblematik verdeutlicht die globale Dimension wirtschaftsethischer Fragen. ___(4)___ ESG-Kriterien gewinnen auf den Finanzmärkten an Bedeutung. ___(5)___ Die Verhaltensökonomie hat das Modell des Homo oeconomicus grundlegend infrage gestellt. ___(6)___ Die Frage nach einer gerechten Verteilung von Wohlstand bleibt zentral. ___(7)___ Eine zukunftsfähige Wirtschaftsethik muss ökologische Grenzen als absolute Restriktionen anerkennen. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Die zentrale Spannung zwischen der Effizienzlogik der Marktwirtschaft und den Anforderungen sozialer Gerechtigkeit, ökologischer Nachhaltigkeit und menschlicher Würde bildet den Kern wirtschaftsethischer Reflexion.',b:'Wirtschaft und Ethik widersprechen sich.',c:'Unternehmen müssen Gewinn machen.',d:'Die Wirtschaftsethik ist ein junges Fach.'}, answer:'a', evidence:'moralischen Grundlagen und Grenzen', vocab:[{word:'Effizienzlogik',type:'Nomen',meaning:'efficiency logic'}] },
      { n:2, opts:{a:'Friedman war ein Nobelpreisträger.',b:'Seine 1970 formulierte These, die einzige soziale Verantwortung des Unternehmens bestehe in der Gewinnmaximierung für seine Aktionäre, reduzierte die moralische Komplexität unternehmerischen Handelns auf eine einzige Kennzahl und externalisierte alle übrigen Kosten.',c:'Gewinnmaximierung ist das Ziel.',d:'Aktionäre wollen Rendite.'}, answer:'b', evidence:'Shareholder-Value-Doktrin', vocab:[{word:'externalisieren',type:'Verb',meaning:'to externalize'}] },
      { n:3, opts:{a:'Unternehmen haben viele Interessengruppen.',b:'R. Edward Freemans Konzept, demzufolge Unternehmen die legitimen Interessen aller von ihrer Tätigkeit Betroffenen berücksichtigen müssen — einschließlich Arbeitnehmer, Zulieferer, Gemeinden und die natürliche Umwelt —, konstituiert eine pluralistische Unternehmensverantwortung.',c:'Die Mitarbeiter sind wichtig.',d:'Kunden haben immer recht.'}, answer:'b', evidence:'Stakeholder-Theorie fordert erweiterte Verantwortung', vocab:[{word:'pluralistisch',type:'Adjektiv',meaning:'pluralistic'}] },
      { n:4, opts:{a:'Lieferketten sind komplex.',b:'Die Globalisierung hat Vorteile.',c:'Wenn westliche Konsumenten von den ausbeuterischen Arbeitsbedingungen, die ihre Kaufkraft in Billiglohnländern erzwingt, durch lange und intransparente Wertschöpfungsketten abgeschirmt werden, stellt sich die Frage nach der moralischen Zurechenbarkeit in asymmetrischen Machtverhältnissen.',d:'Kinderarbeit muss bekämpft werden.'}, answer:'c', evidence:'Lieferkettenproblematik', vocab:[{word:'Zurechenbarkeit',type:'Nomen',meaning:'attributability'}] },
      { n:5, opts:{a:'Nachhaltige Investitionen wachsen schnell.',b:'Die Integration von Environmental-, Social- und Governance-Kriterien in Investitionsentscheidungen reflektiert die wachsende Erkenntnis, dass systemische Risiken wie der Klimawandel die langfristige Wertschöpfung gefährden und traditionelle Risikomodelle inadäquat sind.',c:'Grüne Anleihen sind populär.',d:'Investoren achten auf Nachhaltigkeit.'}, answer:'b', evidence:'ESG-Kriterien gewinnen an Bedeutung', vocab:[{word:'systemisches Risiko',type:'Nomen',meaning:'systemic risk'}] },
      { n:6, opts:{a:'Menschen handeln nicht immer rational.',b:'Daniel Kahnemans und Amos Tverskys Forschung zu kognitiven Verzerrungen, Verlustaversion und Framingeffekten hat demonstriert, dass reale Entscheidungsträger systematisch von den Rationalitätsannahmen der neoklassischen Ökonomie abweichen.',c:'Emotionen beeinflussen Entscheidungen.',d:'Psychologie und Ökonomie hängen zusammen.'}, answer:'b', evidence:'Homo oeconomicus infrage gestellt', vocab:[{word:'Verlustaversion',type:'Nomen',meaning:'loss aversion'}] },
      { n:7, opts:{a:'Die Reichen werden reicher.',b:'Ungleichheit ist ein Problem.',c:'Thomas Pikettys empirisch gestützte These, dass die Rendite auf Kapital strukturell die Wachstumsrate der Wirtschaft übersteigt und damit die Vermögenskonzentration inhärent zunimmt, hat die Frage nach redistributiver Gerechtigkeit wieder ins Zentrum der ökonomischen Debatte gerückt.',d:'Steuern sollten gerecht sein.'}, answer:'c', evidence:'gerechten Verteilung von Wohlstand', vocab:[{word:'redistributiv',type:'Adjektiv',meaning:'redistributive'}] },
      { n:8, opts:{a:'Die Umwelt muss geschützt werden.',b:'Wachstum hat Grenzen.',c:'Nachhaltigkeit ist wichtig.',d:'Die Einsicht, dass ein unendliches Wirtschaftswachstum auf einem endlichen Planeten physikalisch unmöglich ist, erfordert eine fundamentale Revision des Wachstumsparadigmas und die Entwicklung von Wohlstandsmodellen, die menschliches Gedeihen von materiellem Durchsatz entkoppeln.'}, answer:'d', evidence:'ökologische Grenzen als absolute Restriktionen', vocab:[{word:'Wachstumsparadigma',type:'Nomen',meaning:'growth paradigm'}] },
    ]
  },
]

async function main() {
  console.log('🚀 Seeding — Batch 8 (C2-T2-005 to 008)')
  for (const entry of batch) {
    const ex = await prisma.readingExercise.findFirst({ where: { exerciseId: entry.exerciseId }, include: { questions: true } })
    if (!ex) { console.log(`⏭️ ${entry.exerciseId} not found`); continue }
    if (ex.questions.length > 0) { console.log(`⏭️ ${entry.exerciseId} already has questions`); continue }
    await prisma.readingExercise.update({ where: { id: ex.id }, data: { textsJson: entry.texts } })
    for (const q of entry.questions) {
      await prisma.readingQuestion.create({ data: {
        exerciseId: ex.id, questionNumber: q.n, questionType: 'lueckentext', linkedText: 'TextA',
        statement: `Welcher Textabschnitt passt in Lücke ${q.n}?`, options: q.opts, correctAnswer: q.answer, points: 1, sortOrder: q.n,
        explanation: { reasoning: 'Der Textabschnitt fügt sich inhaltlich und argumentativ kohärent in den Kontext ein.', key_evidence: q.evidence, key_vocabulary: q.vocab }
      }})
    }
    console.log(`✅ ${entry.exerciseId} — ${entry.texts[0].title}`)
  }
  console.log('🎉 Batch 8 complete!')
}
main().catch(console.error).finally(() => prisma.$disconnect())
