import { PrismaClient } from '../apps/web/generated/prisma'
const prisma = new PrismaClient()

const batch = [
  {
    exerciseId: 'C1-T3-005',
    texts: [{ id: 'TextA', type: 'sachtext', title: 'Konformität und Individualismus in der Massengesellschaft',
      content: 'Die Spannung zwischen individuellem Selbstausdruck und gesellschaftlichem Anpassungsdruck ist ein zentrales Thema der Sozialpsychologie. ___(1)___ Zahlreiche Experimente haben gezeigt, dass Menschen selbst offensichtlich falsche Urteile übernehmen, wenn die Mehrheit dies tut. ___(2)___ In der digitalen Welt verstärken sich diese Dynamiken durch soziale Medien. ___(3)___ Gleichzeitig ermöglichen Online-Plattformen auch die Bildung nonkonformer Gemeinschaften. ___(4)___ Die Frage nach Authentizität wird in einer Gesellschaft der permanenten Selbstinszenierung virulent. ___(5)___ Psychologische Forschung zeigt, dass chronische Anpassung zu erhöhtem Stresserleben führen kann. ___(6)___ Kulturvergleichende Studien belegen zudem erhebliche Unterschiede in der Bewertung von Konformität. ___(7)___ Die Balance zwischen sozialer Zugehörigkeit und Selbstverwirklichung bleibt eine lebenslange Entwicklungsaufgabe. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Die wegweisenden Konformitätsexperimente von Solomon Asch in den 1950er-Jahren haben die Grundlagen für die systematische Erforschung sozialen Einflusses gelegt.',b:'Jeder Mensch ist einzigartig.',c:'Die Gesellschaft fordert Anpassung.',d:'Psychologie ist eine junge Wissenschaft.'}, answer:'a', evidence:'individuellem Selbstausdruck und gesellschaftlichem Anpassungsdruck', vocab:[{word:'Konformität',type:'Nomen',meaning:'conformity'}] },
      { n:2, opts:{a:'Die Experimente waren umstritten.',b:'Dies verdeutlicht, dass soziale Einflussnahme nicht nur über expliziten Zwang, sondern subtil über normative und informationelle Mechanismen wirkt.',c:'Kinder sind besonders anfällig.',d:'Nur wenige Menschen widerstehen dem Gruppendruck.'}, answer:'b', evidence:'offensichtlich falsche Urteile', vocab:[{word:'normativ',type:'Adjektiv',meaning:'normative'}] },
      { n:3, opts:{a:'Algorithmisch gesteuerte Feedback-Schleifen erzeugen Bestätigungsblasen, in denen abweichende Meinungen systematisch unterrepräsentiert werden und gruppenkonformes Denken begünstigt wird.',b:'Social Media ist beliebt.',c:'Jeder nutzt Facebook.',d:'Das Internet verändert die Kommunikation.'}, answer:'a', evidence:'In der digitalen Welt verstärken sich diese Dynamiken', vocab:[{word:'Bestätigungsblase',type:'Nomen',meaning:'confirmation bubble'}] },
      { n:4, opts:{a:'Manche Menschen lehnen soziale Medien ab.',b:'Subkulturen, Nischeninteressen und marginalisierte Perspektiven finden im virtuellen Raum eine Sichtbarkeit und Vernetzungsmöglichkeit, die ihnen in der physischen Öffentlichkeit häufig verwehrt bleibt.',c:'Es gibt viele Online-Foren.',d:'Die Internetnutzung steigt stetig.'}, answer:'b', evidence:'Bildung nonkonformer Gemeinschaften', vocab:[{word:'marginalisiert',type:'Adjektiv',meaning:'marginalized'}] },
      { n:5, opts:{a:'Wenn das präsentierte Selbstbild zunehmend von der inneren Realität abweicht, entsteht eine kognitive Dissonanz, die langfristig das psychische Wohlbefinden beeinträchtigen kann.',b:'Soziale Medien machen unglücklich.',c:'Jeder möchte beliebt sein.',d:'Die Jugend ist besonders betroffen.'}, answer:'a', evidence:'Authentizität', vocab:[{word:'kognitive Dissonanz',type:'Nomen',meaning:'cognitive dissonance'}] },
      { n:6, opts:{a:'Stress ist ein weit verbreitetes Problem.',b:'Insbesondere die Unterdrückung eigener Überzeugungen und Bedürfnisse zugunsten sozialer Erwartungen korreliert signifikant mit Burnout-Symptomatik und depressiven Episoden.',c:'Sport hilft gegen Stress.',d:'Viele Menschen sind überarbeitet.'}, answer:'b', evidence:'chronische Anpassung zu erhöhtem Stresserleben', vocab:[{word:'Burnout-Symptomatik',type:'Nomen',meaning:'burnout symptoms'}] },
      { n:7, opts:{a:'Japan und die USA unterscheiden sich stark.',b:'Alle Kulturen schätzen Individualismus.',c:'Während in westlich-individualistischen Gesellschaften Nonkonformität oft positiv konnotiert ist, gilt sie in kollektivistisch geprägten Kulturen häufiger als sozial destruktiv.',d:'Kulturelle Unterschiede nehmen ab.'}, answer:'c', evidence:'erhebliche Unterschiede in der Bewertung von Konformität', vocab:[{word:'kollektivistisch',type:'Adjektiv',meaning:'collectivist'}] },
      { n:8, opts:{a:'Jeder muss seinen eigenen Weg finden.',b:'Die Gesellschaft braucht beides.',c:'Entwicklungspsychologisch betrachtet erfordert diese Balance die Fähigkeit zur mentalen Selbstregulation, die durch sichere Bindungserfahrungen und reflexive Identitätsarbeit gefördert wird.',d:'Ältere Menschen sind angepasster.'}, answer:'c', evidence:'sozialer Zugehörigkeit und Selbstverwirklichung', vocab:[{word:'Selbstregulation',type:'Nomen',meaning:'self-regulation'}] },
    ]
  },
  {
    exerciseId: 'C1-T3-006',
    texts: [{ id: 'TextA', type: 'sachtext', title: 'Die Falsifizierbarkeit als Abgrenzungskriterium',
      content: 'Karl Poppers Falsifikationsprinzip revolutionierte die Wissenschaftstheorie des 20. Jahrhunderts. ___(1)___ Im Gegensatz zum logischen Positivismus forderte Popper nicht die Verifizierbarkeit, sondern die prinzipielle Widerlegbarkeit wissenschaftlicher Aussagen. ___(2)___ Dieses Kriterium erlaubt es, Wissenschaft von Pseudowissenschaft abzugrenzen. ___(3)___ In der wissenschaftlichen Praxis gestaltet sich die Anwendung des Falsifikationsprinzips jedoch komplexer als in der Theorie. ___(4)___ Thomas Kuhn widersprach Popper mit seinem Konzept der Paradigmenwechsel. ___(5)___ Imre Lakatos versuchte, beide Positionen zu versöhnen. ___(6)___ Die Debatte zwischen diesen Ansätzen prägt die Wissenschaftsphilosophie bis heute. ___(7)___ Für die Praxis der Forschungsförderung haben diese theoretischen Fragen unmittelbare Konsequenzen. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Seine 1934 veröffentlichte „Logik der Forschung" stellte die bis dahin vorherrschende induktivistische Erkenntnistheorie grundlegend infrage und begründete den kritischen Rationalismus.',b:'Popper wurde in Wien geboren.',c:'Er war Professor in London.',d:'Wissenschaft ist wichtig für die Gesellschaft.'}, answer:'a', evidence:'Poppers Falsifikationsprinzip revolutionierte die Wissenschaftstheorie', vocab:[{word:'kritischer Rationalismus',type:'Nomen',meaning:'critical rationalism'}] },
      { n:2, opts:{a:'Popper war ein bekannter Philosoph.',b:'Eine Theorie, die keine denkbaren Beobachtungen benennen kann, die sie widerlegen würden, besitzt demnach keinen empirischen Gehalt und fällt nicht in den Bereich der Wissenschaft.',c:'Verifikation ist wichtiger als Falsifikation.',d:'Die meisten Wissenschaftler kennen Popper nicht.'}, answer:'b', evidence:'prinzipielle Widerlegbarkeit wissenschaftlicher Aussagen', vocab:[{word:'empirischer Gehalt',type:'Nomen',meaning:'empirical content'}] },
      { n:3, opts:{a:'Disziplinen wie die Astrologie oder die Psychoanalyse, die ihre Theorien so formulieren, dass sie jedes mögliche Ergebnis erklären können, erweisen sich nach diesem Kriterium als unwissenschaftlich.',b:'Pseudowissenschaft ist gefährlich.',c:'Viele Menschen glauben an Astrologie.',d:'Die Grenze ist nicht immer klar.'}, answer:'a', evidence:'Wissenschaft von Pseudowissenschaft abzugrenzen', vocab:[{word:'Pseudowissenschaft',type:'Nomen',meaning:'pseudoscience'}] },
      { n:4, opts:{a:'Forschung ist teuer.',b:'Einzelne Experimente können Theorien selten definitiv widerlegen, da Hilfsannahmen, Messungenauigkeiten und die Duhem-Quine-These die eindeutige Zuordnung eines Scheiterns erschweren.',c:'Wissenschaftler machen selten Fehler.',d:'Laborexperimente sind der Goldstandard.'}, answer:'b', evidence:'die Anwendung des Falsifikationsprinzips komplexer als in der Theorie', vocab:[{word:'Duhem-Quine-These',type:'Nomen',meaning:'Duhem-Quine thesis'}] },
      { n:5, opts:{a:'Kuhn war Physiker und Philosoph.',b:'Er argumentierte, dass Wissenschaftler innerhalb eines Paradigmas arbeiten und anomale Befunde zunächst ignorieren oder umdeuten, bis die Anomalien eine kritische Masse erreichen und einen revolutionären Umbruch auslösen.',c:'Paradigmen ändern sich selten.',d:'Kuhn und Popper waren Freunde.'}, answer:'b', evidence:'Kuhn widersprach Popper mit seinem Konzept der Paradigmenwechsel', vocab:[{word:'Anomalie',type:'Nomen',meaning:'anomaly'}] },
      { n:6, opts:{a:'Sein Konzept der „Forschungsprogramme" unterscheidet zwischen einem unwiderlegbaren harten Kern und einem revidierbaren Schutzgürtel von Hilfsannahmen, der die progressive oder degenerative Entwicklung eines Programms bestimmt.',b:'Er war ein ungarischer Philosoph.',c:'Kompromisse sind in der Philosophie selten.',d:'Seine Theorie setzte sich nicht durch.'}, answer:'a', evidence:'Lakatos versuchte, beide Positionen zu versöhnen', vocab:[{word:'Forschungsprogramm',type:'Nomen',meaning:'research programme'}] },
      { n:7, opts:{a:'Alle drei Ansätze haben Schwächen.',b:'Die Philosophie ist eine kontroverse Disziplin.',c:'Im Kern geht es um die Frage, ob wissenschaftlicher Fortschritt rational rekonstruierbar ist oder ob soziologische, psychologische und institutionelle Faktoren die Theorieentwicklung maßgeblich bestimmen.',d:'Diese Debatte ist für die Praxis irrelevant.'}, answer:'c', evidence:'Die Debatte zwischen diesen Ansätzen', vocab:[{word:'rational rekonstruierbar',type:'Adjektiv',meaning:'rationally reconstructable'}] },
      { n:8, opts:{a:'Forschungsförderung ist politisch.',b:'Die Kriterien, anhand derer Förderinstitutionen über die Vergabe von Forschungsmitteln entscheiden, beruhen implizit auf wissenschaftstheoretischen Vorannahmen über die Qualität und Produktivität wissenschaftlicher Arbeit.',c:'Es gibt zu wenig Forschungsgelder.',d:'Die Industrie finanziert die meiste Forschung.'}, answer:'b', evidence:'für die Praxis der Forschungsförderung unmittelbare Konsequenzen', vocab:[{word:'Vorannahme',type:'Nomen',meaning:'presupposition'}] },
    ]
  },
  {
    exerciseId: 'C1-T3-007',
    texts: [{ id: 'TextA', type: 'sachtext', title: 'Algorithmen und die Zukunft des Journalismus',
      content: 'Die Digitalisierung hat den Journalismus grundlegend verändert. ___(1)___ Redaktionen stehen vor der Herausforderung, Qualitätsjournalismus in einem Umfeld zu produzieren, das von Gratiskultur und sinkenden Werbeeinnahmen geprägt ist. ___(2)___ Algorithmen übernehmen zunehmend redaktionelle Funktionen. ___(3)___ Die Verbreitung von Desinformation stellt eine existenzielle Bedrohung für die öffentliche Meinungsbildung dar. ___(4)___ Neue Finanzierungsmodelle sollen die Unabhängigkeit journalistischer Arbeit sichern. ___(5)___ Die Ausbildung von Journalisten muss an die veränderten Anforderungen angepasst werden. ___(6)___ Lokaler Journalismus ist besonders von der Medienkrise betroffen. ___(7)___ Die Zukunft des Qualitätsjournalismus hängt davon ab, ob es gelingt, Vertrauen und Relevanz zurückzugewinnen. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Der Übergang vom analogen zum digitalen Medienkonsum hat nicht nur die Distributionskanäle, sondern auch die Rezeptionsgewohnheiten und Erwartungshaltungen des Publikums fundamental verändert.',b:'Das Internet hat viele Vorteile.',c:'Zeitungen verlieren Leser.',d:'Die Digitalisierung betrifft alle Branchen.'}, answer:'a', evidence:'Die Digitalisierung hat den Journalismus grundlegend verändert', vocab:[{word:'Rezeptionsgewohnheit',type:'Nomen',meaning:'reception habit'}] },
      { n:2, opts:{a:'Viele Zeitungen mussten schließen.',b:'Das traditionelle Geschäftsmodell, bei dem Anzeigenerlöse den investigativen Journalismus quersubventionierten, ist durch die Abwanderung von Werbeetats auf digitale Plattformen unwiederbringlich erodiert.',c:'Journalisten verdienen weniger.',d:'Online-Werbung ist günstiger.'}, answer:'b', evidence:'Gratiskultur und sinkenden Werbeeinnahmen', vocab:[{word:'quersubventionieren',type:'Verb',meaning:'to cross-subsidize'}] },
      { n:3, opts:{a:'Von der automatisierten Erstellung von Börsennachrichten über die algorithmische Kuratierung von News-Feeds bis hin zur KI-gestützten Faktenprüfung transformiert Technologie die gesamte journalistische Wertschöpfungskette.',b:'Computer können keine guten Texte schreiben.',c:'Roboterjournalismus ist unethisch.',d:'Die meisten Redaktionen nutzen keine KI.'}, answer:'a', evidence:'Algorithmen übernehmen redaktionelle Funktionen', vocab:[{word:'Wertschöpfungskette',type:'Nomen',meaning:'value chain'}] },
      { n:4, opts:{a:'Fake News sind ein Problem.',b:'Social Media verbreitet Falschnachrichten.',c:'Die systematische Produktion und virale Verbreitung von Falschinformationen durch staatliche und nichtstaatliche Akteure untergräbt das epistemische Fundament demokratischer Gesellschaften.',d:'Jeder sollte Quellen überprüfen.'}, answer:'c', evidence:'Die Verbreitung von Desinformation', vocab:[{word:'epistemisch',type:'Adjektiv',meaning:'epistemic'}] },
      { n:5, opts:{a:'Abonnements werden wichtiger.',b:'Dazu zählen Paywall-Modelle, genossenschaftliche Organisationsformen, Stiftungsfinanzierung und innovative Formate wie Newsletter-basierte Mikromedien, die eine direkte Bindung an spezialisierte Zielgruppen ermöglichen.',c:'Staatliche Förderung ist notwendig.',d:'Werbung bleibt die Haupteinnahmequelle.'}, answer:'b', evidence:'Neue Finanzierungsmodelle', vocab:[{word:'Paywall',type:'Nomen',meaning:'paywall'}] },
      { n:6, opts:{a:'Journalistenschulen gibt es viele.',b:'Die Ausbildung ist praxisorientiert.',c:'Neben klassischen Kompetenzen wie Recherche und Textkompetenz müssen angehende Journalisten heute Datenkompetenz, algorithmisches Verständnis und die Fähigkeit zur multimodalen Narration beherrschen.',d:'Ein Studium ist nicht zwingend nötig.'}, answer:'c', evidence:'Die Ausbildung von Journalisten', vocab:[{word:'multimodal',type:'Adjektiv',meaning:'multimodal'}] },
      { n:7, opts:{a:'Das Sterben lokaler Medien hinterlässt informationelle Wüsten, in denen kommunalpolitische Kontrolle entfällt, bürgerschaftliches Engagement schwindet und die demokratische Teilhabe erodiert.',b:'Regionale Zeitungen haben treue Leser.',c:'Online-Portale ersetzen lokale Medien.',d:'Lokalnachrichten sind weniger interessant.'}, answer:'a', evidence:'Lokaler Journalismus ist besonders betroffen', vocab:[{word:'informationelle Wüste',type:'Nomen',meaning:'news desert'}] },
      { n:8, opts:{a:'Die Zukunft ist ungewiss.',b:'Journalismus wird überleben.',c:'Dies setzt voraus, dass Medienhäuser ihre Rolle als Gatekeeper und Kuratoren von Wirklichkeit kritisch reflektieren und gleichzeitig Formate entwickeln, die den veränderten Mediennutzungsgewohnheiten Rechnung tragen.',d:'Die Leser müssen kritischer werden.'}, answer:'c', evidence:'Vertrauen und Relevanz zurückzugewinnen', vocab:[{word:'Gatekeeper',type:'Nomen',meaning:'gatekeeper'}] },
    ]
  },
  {
    exerciseId: 'C1-T3-008',
    texts: [{ id: 'TextA', type: 'sachtext', title: 'Digitale Souveränität und Grundrechte im Netz',
      content: 'Die Durchsetzung von Grundrechten im digitalen Raum gehört zu den drängendsten juristischen Fragestellungen unserer Zeit. ___(1)___ Das Recht auf informationelle Selbstbestimmung, vom Bundesverfassungsgericht 1983 formuliert, gewinnt im Zeitalter der Datenökonomie neue Relevanz. ___(2)___ Die europäische Datenschutz-Grundverordnung gilt als wegweisender Versuch, digitale Bürgerrechte zu kodifizieren. ___(3)___ Die Regulierung von Plattformen stellt eine besondere Herausforderung dar. ___(4)___ Cyberattacken auf kritische Infrastruktur werfen Fragen der digitalen Souveränität auf. ___(5)___ Die internationale Dimension des Cyberrechts erfordert multilaterale Kooperation. ___(6)___ Künstliche Intelligenz wirft neuartige Haftungsfragen auf. ___(7)___ Die Zukunft des digitalen Rechts wird davon abhängen, ob es gelingt, technologische Innovation und Grundrechtsschutz in Einklang zu bringen. ___(8)___' }],
    questions: [
      { n:1, opts:{a:'Die Diskrepanz zwischen der Geschwindigkeit technologischer Entwicklung und der Trägheit legislativer Prozesse führt zu einem wachsenden Regulierungsdefizit, das grundrechtliche Schutzlücken entstehen lässt.',b:'Das Internet ist schwer zu regulieren.',c:'Juristen verstehen die Technik nicht.',d:'Neue Gesetze brauchen Zeit.'}, answer:'a', evidence:'drängendsten juristischen Fragestellungen', vocab:[{word:'Regulierungsdefizit',type:'Nomen',meaning:'regulatory deficit'}] },
      { n:2, opts:{a:'Der Datenschutz ist ein Grundrecht.',b:'Wenn persönliche Daten zur wertvollsten Ressource der digitalen Wirtschaft werden, wandelt sich das Verhältnis zwischen Bürger und Staat ebenso wie zwischen Verbraucher und Unternehmen fundamental.',c:'Das Gericht sitzt in Karlsruhe.',d:'1983 war ein wichtiges Jahr.'}, answer:'b', evidence:'informationelle Selbstbestimmung', vocab:[{word:'Datenökonomie',type:'Nomen',meaning:'data economy'}] },
      { n:3, opts:{a:'Die EU hat viele Verordnungen.',b:'Sie ist jedoch nicht unumstritten.',c:'Trotz ihrer extraterritorialen Reichweite und hohen Bußgelder zeigt die Praxis, dass die Durchsetzung gegenüber global agierenden Technologiekonzernen weiterhin erhebliche strukturelle Defizite aufweist.',d:'Die DSGVO gilt seit 2018.'}, answer:'c', evidence:'Datenschutz-Grundverordnung', vocab:[{word:'extraterritorial',type:'Adjektiv',meaning:'extraterritorial'}] },
      { n:4, opts:{a:'Social-Media-Unternehmen sind mächtig.',b:'Als privatwirtschaftliche Akteure, die de facto öffentliche Kommunikationsräume kontrollieren, nehmen Plattformen eine quasi-staatliche Rolle ein, ohne demokratisch legitimiert zu sein.',c:'Die Nutzer sollten vorsichtiger sein.',d:'Es gibt zu viele Plattformen.'}, answer:'b', evidence:'Die Regulierung von Plattformen', vocab:[{word:'quasi-staatlich',type:'Adjektiv',meaning:'quasi-governmental'}] },
      { n:5, opts:{a:'Die zunehmende Verwundbarkeit vernetzter Systeme in den Bereichen Energie, Gesundheit und Verkehr macht deutlich, dass Cybersicherheit nicht nur eine technische, sondern eine gesamtgesellschaftliche Aufgabe ist.',b:'Hacker sind eine große Gefahr.',c:'Die Polizei ist schlecht ausgestattet.',d:'Cyberangriffe nehmen zu.'}, answer:'a', evidence:'Cyberattacken auf kritische Infrastruktur', vocab:[{word:'Cybersicherheit',type:'Nomen',meaning:'cybersecurity'}] },
      { n:6, opts:{a:'Die UNO sollte eingreifen.',b:'Die territorial gebundene Souveränität des Nationalstaats kollidiert fundamental mit dem entgrenzten Charakter des Cyberspace, was die Entwicklung eines kohärenten internationalen Rechtsrahmens erheblich erschwert.',c:'Internationale Zusammenarbeit ist schwierig.',d:'Jedes Land hat eigene Gesetze.'}, answer:'b', evidence:'multilaterale Kooperation', vocab:[{word:'Souveränität',type:'Nomen',meaning:'sovereignty'}] },
      { n:7, opts:{a:'KI ist noch nicht ausgereift.',b:'Roboter sollten reguliert werden.',c:'Wenn ein autonomes System einen Schaden verursacht, stellt sich die Frage, ob der Hersteller, der Betreiber, der Nutzer oder das System selbst haftbar gemacht werden kann — eine Frage, für die das bestehende Deliktsrecht keine befriedigenden Antworten bereithält.',d:'Die Haftung muss geklärt werden.'}, answer:'c', evidence:'Künstliche Intelligenz wirft neuartige Haftungsfragen auf', vocab:[{word:'Deliktsrecht',type:'Nomen',meaning:'tort law'}] },
      { n:8, opts:{a:'Die Zukunft ist digital.',b:'Beide Ziele sind wichtig.',c:'Die Technologie wird sich durchsetzen.',d:'Dies erfordert einen regulatorischen Ansatz, der technologieneutral, risikoadaptiv und grundrechtssensibel zugleich ist und der die Innovationskraft des Marktes nutzt, ohne die Würde und Freiheit des Einzelnen preiszugeben.',d2:'test'}, answer:'d', evidence:'Innovation und Grundrechtsschutz in Einklang zu bringen', vocab:[{word:'technologieneutral',type:'Adjektiv',meaning:'technology-neutral'}] },
    ]
  },
]

async function main() {
  console.log('🚀 Seeding — Batch 5 (C1-T3-005 to 008)')
  for (const entry of batch) {
    const ex = await prisma.readingExercise.findFirst({ where: { exerciseId: entry.exerciseId }, include: { questions: true } })
    if (!ex) { console.log(`⏭️ ${entry.exerciseId} not found`); continue }
    if (ex.questions.length > 0) { console.log(`⏭️ ${entry.exerciseId} already has questions`); continue }
    await prisma.readingExercise.update({ where: { id: ex.id }, data: { textsJson: entry.texts } })
    for (const q of entry.questions) {
      await prisma.readingQuestion.create({ data: {
        exerciseId: ex.id, questionNumber: q.n, questionType: 'lueckentext', linkedText: 'TextA',
        statement: `Welcher Satz passt in Lücke ${q.n}?`, options: q.opts, correctAnswer: q.answer, points: 1, sortOrder: q.n,
        explanation: { reasoning: `Der Satz passt inhaltlich und logisch in den Kontext.`, key_evidence: q.evidence, key_vocabulary: q.vocab }
      }})
    }
    console.log(`✅ ${entry.exerciseId} — ${entry.texts[0].title}`)
  }
  console.log('🎉 Batch 5 complete!')
}
main().catch(console.error).finally(() => prisma.$disconnect())
