/**
 * seed-speaking.ts
 * 
 * Seeds SpeakingTopic + SpeakingLesson from rich content JSON files
 * generated by generate-speaking-content.ts.
 * 
 * Falls back to Audio Factory scripts if no rich content exists.
 *
 * Usage:
 *   DATABASE_URL="..." npx tsx prisma/seed-speaking.ts
 */

import { PrismaClient } from '@prisma/client'
import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'

const prisma = new PrismaClient()

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const CONTENT_DIR = path.resolve(__dirname, '../../../content/a1/speaking')
const AUDIO_FACTORY = path.resolve(__dirname, '../../../../8-Audio-Factory')
const SCRIPTS_DIR = path.join(AUDIO_FACTORY, 'data/scripts/Sprechen-Nachsprechen')

// Topic metadata
const TOPIC_META: Record<string, { titleDe: string; titleVi: string; icon: string }> = {
  'a1-alltag': { titleDe: 'Alltag', titleVi: 'Cuộc sống hàng ngày', icon: '🌅' },
  'a1-begruessung': { titleDe: 'Begrüßung & Vorstellung', titleVi: 'Chào hỏi & giới thiệu', icon: '👋' },
  'a1-einkaufen': { titleDe: 'Einkaufen', titleVi: 'Mua sắm', icon: '🛒' },
  'a1-essen-trinken': { titleDe: 'Essen & Trinken', titleVi: 'Ăn uống', icon: '🍽️' },
  'a1-familie': { titleDe: 'Familie', titleVi: 'Gia đình', icon: '👨‍👩‍👧' },
  'a1-freizeit': { titleDe: 'Freizeit & Hobbys', titleVi: 'Thời gian rảnh & sở thích', icon: '⚽' },
  'a1-koerper-gesundheit': { titleDe: 'Körper & Gesundheit', titleVi: 'Cơ thể & sức khỏe', icon: '💪' },
  'a1-wegbeschreibung': { titleDe: 'Wegbeschreibung', titleVi: 'Chỉ đường', icon: '🗺️' },
  'a1-wetter-jahreszeiten': { titleDe: 'Wetter & Jahreszeiten', titleVi: 'Thời tiết & mùa', icon: '🌤️' },
  'a1-wohnen': { titleDe: 'Wohnen', titleVi: 'Nhà ở', icon: '🏠' },
}

interface RichContentFile {
  topicSlug: string
  titleDe: string
  titleVi: string
  cefrLevel: string
  lessons: Array<{
    lessonId: string
    topicSlug: string
    lessonNumber: number
    titleDe: string
    titleVi: string
    originalSentence: string
    sentences: Array<{
      id: string
      textDe: string
      textVi: string
      ipa: string
      audioUrl: string
      expectedDurationSec: number
      pronunciationNotes: string
    }>
  }>
}

interface LegacyScript {
  lesson_id: string
  level: string
  title: string
  topic: string
  lines: Array<{ text: string }>
}

async function seedFromRichContent() {
  const contentFiles = fs.readdirSync(CONTENT_DIR).filter(f => f.endsWith('.json')).sort()
  if (contentFiles.length === 0) return false

  console.log(`📂 Found ${contentFiles.length} rich content files\n`)

  let topicCount = 0
  let lessonCount = 0
  let sentenceCount = 0

  for (const file of contentFiles) {
    const data: RichContentFile = JSON.parse(fs.readFileSync(path.join(CONTENT_DIR, file), 'utf-8'))
    const meta = TOPIC_META[data.topicSlug]
    if (!meta) continue

    // Upsert topic
    const topic = await prisma.speakingTopic.upsert({
      where: { slug: data.topicSlug },
      update: {
        titleDe: meta.titleDe,
        titleVi: meta.titleVi,
        description: meta.icon,
        cefrLevel: 'A1',
        sortOrder: topicCount + 1,
        status: 'PUBLISHED',
      },
      create: {
        slug: data.topicSlug,
        titleDe: meta.titleDe,
        titleVi: meta.titleVi,
        description: meta.icon,
        cefrLevel: 'A1',
        sortOrder: topicCount + 1,
        status: 'PUBLISHED',
      },
    })
    topicCount++
    console.log(`  🎤 ${data.topicSlug}: ${data.lessons.length} lessons`)

    // Upsert lessons
    for (let i = 0; i < data.lessons.length; i++) {
      const lesson = data.lessons[i]!
      const config = {
        maxRecordingSec: 10,
        minAccuracyToPass: 60,
        attemptsAllowed: 3,
        showIPA: true,
        showTranslation: true,
        autoPlayModel: true,
      }

      await prisma.speakingLesson.upsert({
        where: { id: lesson.lessonId },
        update: {
          topicId: topic.id,
          level: 'A1',
          lessonType: 'E',
          lessonNumber: lesson.lessonNumber,
          titleDe: lesson.titleDe,
          titleVi: lesson.titleVi,
          exerciseType: 'nachsprechen',
          exercisesJson: { sentences: lesson.sentences },
          configJson: config,
          estimatedMin: Math.max(3, Math.ceil(lesson.sentences.length * 0.5)),
          sortOrder: i + 1,
          status: 'PUBLISHED',
        },
        create: {
          id: lesson.lessonId,
          topicId: topic.id,
          level: 'A1',
          lessonType: 'E',
          lessonNumber: lesson.lessonNumber,
          titleDe: lesson.titleDe,
          titleVi: lesson.titleVi,
          exerciseType: 'nachsprechen',
          exercisesJson: { sentences: lesson.sentences },
          configJson: config,
          estimatedMin: Math.max(3, Math.ceil(lesson.sentences.length * 0.5)),
          sortOrder: i + 1,
          status: 'PUBLISHED',
        },
      })
      lessonCount++
      sentenceCount += lesson.sentences.length
    }
  }

  console.log(`\n  Topics: ${topicCount}`)
  console.log(`  Lessons: ${lessonCount}`)
  console.log(`  Sentences: ${sentenceCount}`)
  return true
}

async function seedFromLegacyScripts() {
  console.log('⚠️ No rich content found, falling back to Audio Factory scripts\n')

  if (!fs.existsSync(SCRIPTS_DIR)) {
    console.error('❌ Scripts not found:', SCRIPTS_DIR)
    return
  }

  const scriptFiles = fs.readdirSync(SCRIPTS_DIR).filter(f => f.endsWith('.json')).sort()
  const byTopic = new Map<string, LegacyScript[]>()
  for (const file of scriptFiles) {
    try {
      const data: LegacyScript = JSON.parse(fs.readFileSync(path.join(SCRIPTS_DIR, file), 'utf-8'))
      const topic = data.topic || 'unknown'
      if (!byTopic.has(topic)) byTopic.set(topic, [])
      byTopic.get(topic)!.push(data)
    } catch {}
  }

  let topicCount = 0
  let lessonCount = 0

  for (const [topicSlug, scripts] of byTopic) {
    const meta = TOPIC_META[topicSlug]
    if (!meta) continue

    const topic = await prisma.speakingTopic.upsert({
      where: { slug: topicSlug },
      update: { titleDe: meta.titleDe, titleVi: meta.titleVi, cefrLevel: 'A1', sortOrder: topicCount + 1, status: 'PUBLISHED' },
      create: { slug: topicSlug, titleDe: meta.titleDe, titleVi: meta.titleVi, cefrLevel: 'A1', sortOrder: topicCount + 1, status: 'PUBLISHED' },
    })
    topicCount++

    scripts.sort((a, b) => {
      const numA = parseInt(a.lesson_id.split('-').pop() || '0')
      const numB = parseInt(b.lesson_id.split('-').pop() || '0')
      return numA - numB
    })

    for (let i = 0; i < scripts.length; i++) {
      const script = scripts[i]!
      const lessonNum = parseInt(script.lesson_id.split('-').pop() || `${i + 1}`)
      const lessonId = `${topicSlug}-${String(lessonNum).padStart(2, '0')}-nachsprechen`
      const sentenceText = script.lines[0]?.text || ''

      const sentences = [{
        id: 's1',
        textDe: sentenceText,
        textVi: '',
        ipa: '',
        audioUrl: `/audio/speaking/a1/${topicSlug}/s${String(lessonNum).padStart(2, '0')}.mp3`,
        expectedDurationSec: Math.max(2, Math.ceil(sentenceText.split(' ').length * 0.6)),
        pronunciationNotes: '',
      }]

      await prisma.speakingLesson.upsert({
        where: { id: lessonId },
        update: {
          topicId: topic.id, level: 'A1', lessonType: 'E', lessonNumber: lessonNum,
          titleDe: script.title, titleVi: `Nhắc lại: ${meta.titleVi}`,
          exerciseType: 'nachsprechen', exercisesJson: { sentences },
          estimatedMin: 3, sortOrder: i + 1, status: 'PUBLISHED',
        },
        create: {
          id: lessonId, topicId: topic.id, level: 'A1', lessonType: 'E', lessonNumber: lessonNum,
          titleDe: script.title, titleVi: `Nhắc lại: ${meta.titleVi}`,
          exerciseType: 'nachsprechen', exercisesJson: { sentences },
          estimatedMin: 3, sortOrder: i + 1, status: 'PUBLISHED',
        },
      })
      lessonCount++
    }
  }

  console.log(`  Topics: ${topicCount}`)
  console.log(`  Lessons: ${lessonCount}`)
}

async function main() {
  console.log('🎤 Fuxie Speaking Seed')
  console.log('========================\n')

  let seeded = false
  if (fs.existsSync(CONTENT_DIR)) {
    seeded = await seedFromRichContent()
  }
  if (!seeded) {
    await seedFromLegacyScripts()
  }

  console.log('\n✅ Speaking seed complete! 🦊')
}

main()
  .catch(e => { console.error('❌ Seed failed:', e); process.exit(1) })
  .finally(async () => { await prisma.$disconnect() })
