export const FUXIE_GLOBAL_WORLD_LOCATIONS = {
    grammarWorkshopInterior: '/mascot-3d/world/global/fuxie-global-grammar-workshop-interior.webp',
    reviewGardenGreenhouse: '/mascot-3d/world/global/fuxie-global-review-garden-greenhouse.webp',
    badgeMuseumShelfRoom: '/mascot-3d/world/global/fuxie-global-badge-museum-shelf-room.webp',
    campaignFestivalBoard: '/mascot-3d/world/global/fuxie-global-campaign-festival-board.webp',
    leaderboardGuildHall: '/mascot-3d/world/global/fuxie-global-leaderboard-guild-hall.webp',
    sessionFocusDojo: '/mascot-3d/world/global/fuxie-global-session-focus-dojo.webp',
    vocabularyMicrogameBooth: '/mascot-3d/world/global/fuxie-global-vocabulary-microgame-booth.webp',
    speakingRoleplayCafeRoom: '/mascot-3d/world/global/fuxie-global-speaking-roleplay-cafe-room.webp',
    examResultHall: '/mascot-3d/world/global/fuxie-global-exam-result-hall.webp',
    cefrGatePlaza: '/mascot-3d/world/global/fuxie-global-cefr-gate-plaza.webp',
    teacherAcademyExterior: '/mascot-3d/world/global/fuxie-global-teacher-academy-exterior.webp',
    teacherClassroomInterior: '/mascot-3d/world/global/fuxie-global-teacher-classroom-interior.webp',
    studentProgressDesk: '/mascot-3d/world/global/fuxie-global-student-progress-desk.webp',
    adminCommandCenter: '/mascot-3d/world/global/fuxie-global-admin-command-center.webp',
    analyticsObservatory: '/mascot-3d/world/global/fuxie-global-analytics-observatory.webp',
    contentQualityLab: '/mascot-3d/world/global/fuxie-global-content-quality-lab.webp',
    operationsServerRoom: '/mascot-3d/world/global/fuxie-global-operations-server-room.webp',
    rewardsApprovalDesk: '/mascot-3d/world/global/fuxie-global-rewards-approval-desk.webp',
    authWelcomeGate: '/mascot-3d/world/global/fuxie-global-auth-welcome-gate.webp',
    liveQaControlBooth: '/mascot-3d/world/global/fuxie-global-live-qa-control-booth.webp',
} as const

export const FUXIE_GLOBAL_BUILDINGS = {
    rathausExamHall: '/mascot-3d/world/buildings/fuxie-global-rathaus-exam-hall.webp',
    schoolhouse: '/mascot-3d/world/buildings/fuxie-global-fuxie-schoolhouse.webp',
    readingLibrary: '/mascot-3d/world/buildings/fuxie-global-reading-library.webp',
    writingPostOffice: '/mascot-3d/world/buildings/fuxie-global-writing-post-office.webp',
    marketStall: '/mascot-3d/world/buildings/fuxie-global-fuxie-market-stall.webp',
    radioListeningTower: '/mascot-3d/world/buildings/fuxie-global-radio-listening-tower.webp',
    speakingStageCafe: '/mascot-3d/world/buildings/fuxie-global-speaking-stage-cafe.webp',
    badgeMuseum: '/mascot-3d/world/buildings/fuxie-global-badge-museum.webp',
    reviewGreenhouse: '/mascot-3d/world/buildings/fuxie-global-review-greenhouse.webp',
    onboardingWelcomeInn: '/mascot-3d/world/buildings/fuxie-global-onboarding-welcome-inn.webp',
} as const

export const FUXIE_GLOBAL_WORLD_PROPS = {
    villageSignpostCluster: '/mascot-3d/world/props/fuxie-global-village-signpost-cluster.webp',
    blueLanternPost: '/mascot-3d/world/props/fuxie-global-blue-lantern-post.webp',
    cobblestonePathTile: '/mascot-3d/world/props/fuxie-global-cobblestone-path-tile.webp',
    fountainRewardPlinth: '/mascot-3d/world/props/fuxie-global-fountain-reward-plinth.webp',
    woodenBench: '/mascot-3d/world/props/fuxie-global-wooden-bench.webp',
    noticePinsAndRibbons: '/mascot-3d/world/props/fuxie-global-notice-pins-and-ribbons.webp',
    villageMapBoard: '/mascot-3d/world/props/fuxie-global-village-map-board.webp',
    bridgeCheckpoint: '/mascot-3d/world/props/fuxie-global-bridge-checkpoint.webp',
    festivalBunting: '/mascot-3d/world/props/fuxie-global-festival-bunting.webp',
    progressLanternTrail: '/mascot-3d/world/props/fuxie-global-progress-lantern-trail.webp',
} as const

export const FUXIE_GLOBAL_LEARNING_PROPS = {
    grammarGearScroll: '/mascot-3d/world/learning-props/fuxie-global-grammar-gear-scroll.webp',
    vocabularyFlashcardBox: '/mascot-3d/world/learning-props/fuxie-global-vocabulary-flashcard-box.webp',
    readingBookmarkLamp: '/mascot-3d/world/learning-props/fuxie-global-reading-bookmark-lamp.webp',
    listeningHeadphonesStand: '/mascot-3d/world/learning-props/fuxie-global-listening-headphones-stand.webp',
    speakingMicrophoneCharm: '/mascot-3d/world/learning-props/fuxie-global-speaking-microphone-charm.webp',
    writingEnvelopeStack: '/mascot-3d/world/learning-props/fuxie-global-writing-envelope-stack.webp',
    examTimerBell: '/mascot-3d/world/learning-props/fuxie-global-exam-timer-bell.webp',
    reviewSeedPacket: '/mascot-3d/world/learning-props/fuxie-global-review-seed-packet.webp',
    chatPhraseCards: '/mascot-3d/world/learning-props/fuxie-global-chat-phrase-cards.webp',
    cefrCompass: '/mascot-3d/world/learning-props/fuxie-global-cefr-compass.webp',
} as const

export const FUXIE_GLOBAL_REWARD_ITEMS = {
    streakFreezeCrystal: '/reward-assets/global/fuxie-global-streak-freeze-crystal.webp',
    fucoinPouch: '/reward-assets/global/fuxie-global-fucoin-pouch.webp',
    xpStarBundle: '/reward-assets/global/fuxie-global-xp-star-bundle.webp',
    coachHintTicket: '/reward-assets/global/fuxie-global-coach-hint-ticket.webp',
    mocktestUnlockKey: '/reward-assets/global/fuxie-global-mocktest-unlock-key.webp',
    speakingFeedbackPass: '/reward-assets/global/fuxie-global-speaking-feedback-pass.webp',
    fuxieSkyOutfitToken: '/reward-assets/global/fuxie-global-fuxie-sky-outfit-token.webp',
    learningGiftVoucher: '/reward-assets/global/fuxie-global-learning-gift-voucher.webp',
    rewardChestSmall: '/reward-assets/global/fuxie-global-reward-chest-small.webp',
    dailyGoalStamp: '/reward-assets/global/fuxie-global-daily-goal-stamp.webp',
    pronunciationMicCharm: '/reward-assets/global/fuxie-global-pronunciation-mic-charm.webp',
    writingStampSeal: '/reward-assets/global/fuxie-global-writing-stamp-seal.webp',
    reviewGardenSeed: '/reward-assets/global/fuxie-global-review-garden-seed.webp',
    badgePolishKit: '/reward-assets/global/fuxie-global-badge-polish-kit.webp',
    cefrGateKey: '/reward-assets/global/fuxie-global-cefr-gate-key.webp',
    classroomInviteCard: '/reward-assets/global/fuxie-global-classroom-invite-card.webp',
    radioReplayPass: '/reward-assets/global/fuxie-global-radio-replay-pass.webp',
    grammarRepairToken: '/reward-assets/global/fuxie-global-grammar-repair-token.webp',
    focusShield: '/reward-assets/global/fuxie-global-focus-shield.webp',
    comebackCandle: '/reward-assets/global/fuxie-global-comeback-candle.webp',
} as const

export const FUXIE_GLOBAL_MASCOT_STATES = {
    grammarMentor: '/mascot-3d/states/global/fuxie-global-fuxie-grammar-mentor.webp',
    reviewGardener: '/mascot-3d/states/global/fuxie-global-fuxie-review-gardener.webp',
    badgeCurator: '/mascot-3d/states/global/fuxie-global-fuxie-badge-curator.webp',
    campaignHost: '/mascot-3d/states/global/fuxie-global-fuxie-campaign-host.webp',
    leaderboardAnnouncer: '/mascot-3d/states/global/fuxie-global-fuxie-leaderboard-announcer.webp',
    sessionFocusCoach: '/mascot-3d/states/global/fuxie-global-fuxie-session-focus-coach.webp',
    microgameReferee: '/mascot-3d/states/global/fuxie-global-fuxie-microgame-referee.webp',
    roleplayWaiter: '/mascot-3d/states/global/fuxie-global-fuxie-roleplay-waiter.webp',
    examProctor: '/mascot-3d/states/global/fuxie-global-fuxie-exam-proctor.webp',
    cefrGateGuide: '/mascot-3d/states/global/fuxie-global-fuxie-cefr-gate-guide.webp',
    teacherCoach: '/mascot-3d/states/global/fuxie-global-fuxie-teacher-coach.webp',
    classroomHelper: '/mascot-3d/states/global/fuxie-global-fuxie-classroom-helper.webp',
    adminAnalyst: '/mascot-3d/states/global/fuxie-global-fuxie-admin-analyst.webp',
    contentReviewer: '/mascot-3d/states/global/fuxie-global-fuxie-content-reviewer.webp',
    opsMechanic: '/mascot-3d/states/global/fuxie-global-fuxie-ops-mechanic.webp',
    rewardClerk: '/mascot-3d/states/global/fuxie-global-fuxie-reward-clerk.webp',
    authWelcomer: '/mascot-3d/states/global/fuxie-global-fuxie-auth-welcomer.webp',
    privacyGuardian: '/mascot-3d/states/global/fuxie-global-fuxie-privacy-guardian.webp',
    qaInspector: '/mascot-3d/states/global/fuxie-global-fuxie-qa-inspector.webp',
    errorRepairHelper: '/mascot-3d/states/global/fuxie-global-fuxie-error-repair-helper.webp',
} as const

export const FUXIE_GLOBAL_UI_FRAMES = {
    villageQuestCard: '/mascot-3d/ui/global/fuxie-global-village-quest-card-frame.webp',
    skillPlayerMotivation: '/mascot-3d/ui/global/fuxie-global-skill-player-motivation-frame.webp',
    cefrPathNode: '/mascot-3d/ui/global/fuxie-global-cefr-path-node-frame.webp',
    resultRewardReveal: '/mascot-3d/ui/global/fuxie-global-result-reward-reveal-frame.webp',
    badgeReceipt: '/mascot-3d/ui/global/fuxie-global-badge-receipt-frame.webp',
    shopItemShelf: '/mascot-3d/ui/global/fuxie-global-shop-item-shelf-frame.webp',
    dailyGoalNotice: '/mascot-3d/ui/global/fuxie-global-daily-goal-notice-frame.webp',
    emptyStateSign: '/mascot-3d/ui/global/fuxie-global-empty-state-sign-frame.webp',
    errorRetryRepair: '/mascot-3d/ui/global/fuxie-global-error-retry-repair-frame.webp',
    chatBubbleVillage: '/mascot-3d/ui/global/fuxie-global-chat-bubble-village-frame.webp',
    authWelcomePanel: '/mascot-3d/ui/global/fuxie-global-auth-welcome-panel.webp',
    onboardingPathPanel: '/mascot-3d/ui/global/fuxie-global-onboarding-path-panel.webp',
    teacherClassroomCard: '/mascot-3d/ui/global/fuxie-global-teacher-classroom-card.webp',
    studentProgressPanel: '/mascot-3d/ui/global/fuxie-global-student-progress-panel.webp',
    adminAnalyticsPanel: '/mascot-3d/ui/global/fuxie-global-admin-analytics-panel.webp',
    contentQaWarningPanel: '/mascot-3d/ui/global/fuxie-global-content-qa-warning-panel.webp',
    opsHealthConsolePanel: '/mascot-3d/ui/global/fuxie-global-ops-health-console-panel.webp',
    rewardApprovalReceipt: '/mascot-3d/ui/global/fuxie-global-reward-approval-receipt.webp',
    liveQaChecklistPanel: '/mascot-3d/ui/global/fuxie-global-live-qa-checklist-panel.webp',
    privacySafetyNoticeFrame: '/mascot-3d/ui/global/fuxie-global-privacy-safety-notice-frame.webp',
} as const

export const FUXIE_GLOBAL_ASSET_RENDERING = {
    cutout: 'transparent-cutout',
    frame: 'transparent-ui-frame',
    scene: 'design-scene-only',
} as const

